### ISSUE TITLE
Spark generating rta call-graph: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by damorosodaragona** [Sable/soot#1020]
When i try to generating a spark call graph i have this error:
java.lang.OutOfMemoryError: GC overhead limit exceeded

	at java.util.concurrent.ConcurrentHashMap$KeySetView.iterator(ConcurrentHashMap.java:4578)
	at java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1039)
	at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1038)
	at soot.FastHierarchy.canStoreClass(FastHierarchy.java:324)
	at soot.FastHierarchy.canStoreType(FastHierarchy.java:233)
	at soot.jimple.toolkits.callgraph.VirtualCalls.resolve(VirtualCalls.java:147)
	at soot.jimple.toolkits.callgraph.VirtualCalls.resolveAnySubType(VirtualCalls.java:196)
	at soot.jimple.toolkits.callgraph.VirtualCalls.resolve(VirtualCalls.java:180)
	at soot.jimple.toolkits.callgraph.VirtualCalls.resolve(VirtualCalls.java:130)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.addType(OnFlyCallGraphBuilder.java:549)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:118)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:154)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at com.company.Project.runPacks(Project.java:130)
	at com.company.Project.<init>(Project.java:60)
	at com.test.TestTemporary.loadP1(TestTemporary.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

My code work as this:
1) I set soot option like this:

```
private void setSootOptions() {
        List<String> argsList = new ArrayList<>();
        argsList.add("-verbose");
        argsList.add("-w"); // whole program mode
        argsList.add("-cp"); // Soot class-path
        argsList.add(path + ";C:\\soot\\soot-3.1.0-jar-with-dependencies.jar;C:\\Program Files\\Java\\jdk1.8.0_112\\jre\\lib\\rt.jar;C:\\Program Files\\Java\\jdk1.8.0_112\\jre\\lib\\jce.jar;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2018.1.5\\lib\\junit-4.12.jar;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2018.1.5\\lib\\hamcrest-core-1.3.jar;");
        Options.v().parse(argsList.toArray(new String[0]));

    }
```
 2) given a directory  i add all .class files in directory as application class in soot (after have loaded it with  Scene.v().loadClassAndSupport())
3) i find all junit tests methods in the given project and set all as entry-points
4) i generate a spark call graph:
 
```
 private void runPacks() {
        Transform sparkTranform = new Transform("cg.spark", null);

        PhaseOptions.v().setPhaseOption(sparkTranform, "enabled:true");
        PhaseOptions.v().setPhaseOption(sparkTranform, "rta:true");
        PhaseOptions.v().setPhaseOption(sparkTranform, "verbose:true");
        PhaseOptions.v().setPhaseOption(sparkTranform, "propagator:worklist");
        PhaseOptions.v().setPhaseOption(sparkTranform, "simple-edges-bidirectional:false");
        PhaseOptions.v().setPhaseOption(sparkTranform, "on-fly-cg:false");
        PhaseOptions.v().setPhaseOption(sparkTranform, "set-impl:double");
        PhaseOptions.v().setPhaseOption(sparkTranform, "double-set-old:hybrid");
        PhaseOptions.v().setPhaseOption(sparkTranform, "double-set-new:hybrid");
        PhaseOptions.v().setPhaseOption(sparkTranform, "force-cg:true");

        Map opt = PhaseOptions.v().getPhaseOptions(sparkTranform);
        System.out.println("rta call graph building...");

        SparkTransformer.v().transform(sparkTranform.getPhaseName(), opt);
        System.out.println("...rta call graph builded");

        CallGraph c = Scene.v().getCallGraph();
        setCallGraph(c);
        System.out.println("Serialize call graph start...");
        serializeCallGraph(callGraph, path + "//" + "-call-grsph" + DotGraph.DOT_EXTENSION);
        System.out.println("...Serialize call graph completed");
     }
```
   I have test this my code on 2 project, with one project i don't have problems, with the second project i have the error reported before (GC overhead limit exceeded). I understand that the problem is  when soot,in call graph generating, try to analyze this 2 methods:
```
@Test
    public void realPassTest(){
        ArrayList<String> a = st.realMethodToTest();
        Assert.assertTrue(a.contains("real"));
    }

    @Test
    public void realFailureTest(){
        ArrayList<String> a = st.realMethodToTest();
        Assert.assertTrue(a.contains("fail"));
    }
```
 [...]

```
public ArrayList<String> realMethodToTest() {
        ArrayList a = new ArrayList<>();
        a.add("real");
        a.add("method");
        a.add("toTest");
        return a;
    }
```
With the debugger i see that soot in generating call graph load all java method for ArrayList. How ca i resolve this?

**Comment by ericbodden** [comment]
Hi.

Can you try giving the VM more heap space?

Best wishes
Eric

**Comment by damorosodaragona** [comment]
I have setup the memory jvm at 10gb, but after 44min the result is the same : java.lang.OutOfMemoryError: GC overhead limit exceeded

In the project that i try to analyze with soot i have only 5 classes very very simply, with some methods with empty body, i have wrote this project only to test soot analysis, it's normal that run for all this time? 
If i delete this two methods, 
```
@Test
    public void realPassTest(){
        ArrayList<String> a = st.realMethodToTest();
        Assert.assertTrue(a.contains("real"));
    }

    @Test
    public void realFailureTest(){
        ArrayList<String> a = st.realMethodToTest();
        Assert.assertTrue(a.contains("fail"));
   } 
```
all is ok.
I use some wrong soot or spark options? Maybe i could use soot in application mode? But if i try to change soot option from "-w" to "-app" i have some errors like this:
 java.lang.runtimeexception: no method source set for method [..].

**Comment by mbenz89** [comment]
With your configuration, you also analyze the JUnit library and the JDK (and even more). Is this what you want?
Otherwise, remove everything you do not want to analyze from the classpath (`path + ";C:\\soot\\soot-3.1.0-jar-with-dependencies.jar;C:\\Program Files\\Java\\jdk1.8.0_112\\jre\\lib\\rt.jar;C:\\Program Files\\Java\\jdk1.8.0_112\\jre\\lib\\jce.jar;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2018.1.5\\lib\\junit-4.12.jar;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2018.1.5\\lib\\hamcrest-core-1.3.jar;`) and run Soot with the `allow-phantom-refs` and `no-bodies-for-excluded` options to replace all used classes that are not on the class path with empty dummies.

The call graph will then have an edge from, e.g., `realPassTest` to `Assert.asserTrue` but none from `Assert.assertTrue` to internal calls since the interanals of `Assert.assertTrue` are not analyzed.

Btw. you can always also exlude classes or entire packages from the analysis by using the `excludes` option.

**Comment by damorosodaragona** [comment]
Ohh, ok, perfect. 
I had tried to remove that libraries from soot path but i had `soot.SootResolver$SootClassNotFoundException`; i had tried to use `allow-phantom-refs` and` no-bodies-for-excluded` options but without remove that class and i had `java.lang.OutOfMemoryError: GC overhead limit exceeded`. But if i remove that libraries and use that options it would seem all right. 
Thank's.
But, if i use `-excludes` options, i can exclude all `java`, `sun`, `org `etc. classes?

**Comment by mbenz89** [comment]
You could, for example, exclude all classes in the `java` package (and all sub-packages) by adding `java.*` to your exclude list. Then Soot will not analyze classes that are located in a package starting with `java.` even if these classes are on the classpath.

**Comment by damorosodaragona** [comment]
Hi,
I have the same problems with closure-compiler, I need to analyze the whole project so also the lib classes. 
If I try to analyze it in rta mode I got java.lang.OutOfMemoryError: GC overhead limit exceeded error or java heap space error. I tried different setup for set-impl because I understood that the problem is there, but for now, I got in each case the same error. 
But I'm a little confused about "apponly" option. I set spark options like this: 
   ```
 private void createCallgraph() {


        LOGGER.info("rta call graph building...");
        long start = new Date().getTime();

        Transform sparkTransform = PackManager.v().getTransform("cg.spark");
        PhaseOptions.v().setPhaseOption(sparkTransform, "enabled:true"); //enable spark transformation
        PhaseOptions.v().setPhaseOption(sparkTransform, "rta:true"); //enable rta mode for call-graph
        PhaseOptions.v().setPhaseOption(sparkTransform, "verbose:true");
        PhaseOptions.v().setPhaseOption(sparkTransform, "set-impl:bit");
        PhaseOptions.v().setPhaseOption(sparkTransform, "on-fly-cg:false"); //disable default call-graph construction mode (soot not permitted to
        PhaseOptions.v().setPhaseOption(sparkTransform, "apponly:true");
        PhaseOptions.v().setPhaseOption(sparkTransform, "force-gc:true");
        PhaseOptions.v().setPhaseOption(sparkTransform, "simplify-offline:true");

        PackManager.v().getPack("cg").apply();
```

but according to the picture below:

![image](https://user-images.githubusercontent.com/15249587/69881139-5e1feb80-12cc-11ea-8b1a-da77bc82bb01.png)

in` soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder#processReachables` at that line there is a check for the apponly options that I set as true, but in this class, it seems to be false, in fact: 

![image](https://user-images.githubusercontent.com/15249587/69881335-02099700-12cd-11ea-8a19-3a111ef31f22.png)

it is normal? In the classes called before that the option apponly it's set as true:

![image](https://user-images.githubusercontent.com/15249587/69881380-29f8fa80-12cd-11ea-91cc-a2ea39084dd4.png)

**Comment by damorosodaragona** [comment]
This is the whole output in verbose mode with debug option enabled notice that i set -Xmx option equal to 4Gb:

[console_output.txt](https://github.com/Sable/soot/files/3916153/console_output.txt)
