### ISSUE TITLE
Get class dependencies

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1021]
Hi,
How is it possible to retrieve class dependencies from Soot?
For example a class use a method which is declared into another class. 
I am trying to extract all the needed dependencies of a specific class in order to analyze it.
Thank you

**Comment by damorosodaragona** [comment]
Yes, for example if you create a CallGraph, the callgraph  analyze all or your project directory (or only class that you give to soot) so you have a graph with all methods and their call.

**Comment by Jacoppy** [comment]
Ok perfect, and how can I extract the jimple of these dependencies and store into files programmatically? I just found how to do it by command line, but it is not what I'm interested in...
And how to load them back also :)
Thank you!

**Comment by Jacoppy** [comment]
I'm asking that because my main idea is to extract a specific class, and all its dependencies, from an apk and the inject those classes into a new apk. 
So I would need to save the jimple representation of the classes into some files and then reload those representations, for injection.

**Comment by mbenz89** [comment]
Question about writeout moved to #1023
