### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by yuhang-lin** [Sable/soot#1022]
The error message shown in the main class has this URL: https://soot-build.cs.uni-paderborn.de/doc/sootoptions/, but I can't access it and get 404 error. Am I the only one who can't view that page?

**Comment by ericbodden** [comment]
@mbenz89 where did this page go?

**Comment by mbenz89** [comment]
You can find the options and documentation for the corresponding version [here](https://github.com/Sable/soot/wiki/Options-and-JavaDoc).

@ericbodden We currently deploy a separate version of the options for each Soot release and the development version. It seems as we missed changing that error message.
