### ISSUE TITLE
Exception when reading jimple file

### ISSUE THREAD

**Issue by mbenz89** [Sable/soot#1023]
```
 try {
                is = new FileInputStream(path);
                Parser p = new Parser(
                        new Lexer(new PushbackReader(new EscapedReader(new BufferedReader(new InputStreamReader(is))), 1024)));
                Start tree = null;

                tree = p.parse();
                Walker w = new Walker(null);
                System.out.println(tree.toString());
                tree.apply(w);
                w.getSootClass();


                is.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } catch (ParserException e) {
                e.printStackTrace();
            } catch (LexerException e) {
                e.printStackTrace();
            }



    }
```

but I get this exception : 
```
Exception in thread "main" java.lang.NullPointerException
	at soot.jimple.parser.Walker.outAMethodSignature(Walker.java:1489)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAMethodSignature(DepthFirstAdapter.java:2985)
	at soot.jimple.parser.node.AMethodSignature.apply(AMethodSignature.java:75)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseANonstaticInvokeExpr(DepthFirstAdapter.java:2666)
	at soot.jimple.parser.node.ANonstaticInvokeExpr.apply(ANonstaticInvokeExpr.java:65)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAInvokeStatement(DepthFirstAdapter.java:2044)
	at soot.jimple.parser.node.AInvokeStatement.apply(AInvokeStatement.java:40)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAFullMethodBody(DepthFirstAdapter.java:1392)
	at soot.jimple.parser.node.AFullMethodBody.apply(AFullMethodBody.java:56)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAMethodMember(DepthFirstAdapter.java:663)
	at soot.jimple.parser.node.AMethodMember.apply(AMethodMember.java:71)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAFileBody(DepthFirstAdapter.java:470)
	at soot.jimple.parser.node.AFileBody.apply(AFileBody.java:46)
	at soot.jimple.parser.Walker.caseAFile(Walker.java:309)
	at soot.jimple.parser.node.AFile.apply(AFile.java:61)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseStart(DepthFirstAdapter.java:34)
	at soot.jimple.parser.node.Start.apply(Start.java:37)
	at Jimple_parser.parse(Jimple_parser.java:35)
	at Instrumenter.main(Instrumenter.java:42)
```

with the attached jimple file  (I had to rename it txt or git doesn't like it )
[cxim.qngg.TEhr.sFiQa (copy).txt](https://github.com/Sable/soot/files/2397989/cxim.qngg.TEhr.sFiQa.copy.txt)

_Originally posted by @Jacoppy in https://github.com/Sable/soot/issues/726#issuecomment-422877943_

**Comment by mbenz89** [comment]
@Jacoppy Writeout usually is done by calling `PackManager.writeOuput`. If this does not serve your purpose (e.g. you just want to write out certain classes), I suggest having a look at the implementation.

**Comment by Jacoppy** [comment]
Well probably I'm doing things wrong.. I'm trying to load back a SootClass from a jimple file that I have made in a previous execution.
The file that is pointed by the inputStream is a jimple file.
I'm trying to use the same logic as here : https://github.com/Sable/soot/blob/develop/src/main/java/soot/jimple/parser/Parse.java

I don't need a writeout, I need to load back a SootClass from a jimple file  :)

**Comment by mbenz89** [comment]
Ah, I see. Why don't you use the input format `jimple` and point Soot to the Jimple files as you would do for classes and Apks as well?

**Comment by Jacoppy** [comment]
Maybe my code is wrong, I just cannot understand the source of this exception...

**Comment by mbenz89** [comment]
Have you still tried if the error also rises when using the general input mechanic?

There are quite a few ways to accomplish that. In case reading in the Jimple works in general, you should be good to go with the `src_prec_apk_c_j` input format. As can be seen in `soot/SourceLocator.java:258`, this input mode will activate apk, class and jimple input. You can then provide a directory with your jimple files to Soot by adding it to the classpath.

In case the jimple read in does not work properly and you are not able to fix ist, you might as well just do the same thing but writing/reading a dex file.

**Comment by Jacoppy** [comment]
no I haven't tried because I have not found any example for loading jimple file programmatically except the one I linked you. I will try to set 'src_prec_apk_c_j' flag and retry .
I suppose it should work correctly.

**Comment by Jacoppy** [comment]
As first if I set that flag I get this : 

APK file on process dir, but chosen src-prec does not support loading APKs
 and the same error keep appearing.

**Comment by Jacoppy** [comment]
Have you got any example for reading jimple files provided in the classpath?
I couldn't find it, just examples via cmd...

**Comment by mbenz89** [comment]
Sorry, I don't.
Can you post your setup code?

Please try to use jimple input only first!

Jacoppy <notifications@github.com> schrieb am Mi., 19. Sep. 2018, 19:48:

**Comment by Jacoppy** [comment]
I have probably sorted this out. I have one last question: how can I select a subset of classes to export as jimple files programmatically? Thank you :)

**Comment by mbenz89** [comment]
The easiest way is probably to set everything you don't want to phantom.

Jacoppy <notifications@github.com> schrieb am Do., 20. Sep. 2018, 19:49:

**Comment by Jacoppy** [comment]
Sorry for reopen but... I'm trying this : 
` for(Iterator<SootClass> iter = Scene.v().getApplicationClasses().snapshotIterator(); iter.hasNext();){
            SootClass c = iter.next();
            for (String i : dependencies){
                if(c.getName().equals(i)){
                    System.out.println("NICE!");
                }
                else{
                    c.setPhantomClass();
                }
            }`
but I have no output. My configs are : 

`  public void initSoot(String apkPath){


        Options.v().set_src_prec(Options.src_prec_apk);

        Options.v().set_process_dir(Collections.singletonList(apkPath));

        Options.v().set_output_format(Options.output_format_jimple);

        Options.v().set_output_dir("/home/jacopo/Downloads/Instrumenter/try_jimple/");

        String androidJarPath = Scene.v().getAndroidJarPath(jarsPath, apkPath);

        List<String> pathList = new ArrayList<String>();

        pathList.add(apkPath);

        pathList.add(androidJarPath);

        Options.v().set_process_dir(pathList);

        Options.v().set_force_android_jar(apkPath);

        Options.v().set_keep_line_number(true);

        Options.v().set_process_multiple_dex(true);

        Options.v().set_allow_phantom_refs(true);

        Options.v().set_whole_program(true);

        Options.v().set_wrong_staticness(Options.wrong_staticness_ignore);

        Options.v().set_exclude(excludePackagesList);

        Options.v().set_no_bodies_for_excluded(true);


        Scene.v().addBasicClass("java.lang.Object", SootClass.SIGNATURES);

        Scene.v().loadNecessaryClasses();

        PackManager.v().runPacks();


    }`
