### ISSUE TITLE
Library package not excluded ?

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1024]
Hi all,
I'm using soot for instrumenting an Android application. The weird this is that the instrumented apk in the end includes also packages as  java , javax, dalvik etc... 
I paste here my configs : 

`
protected static List<String> excludePackagesList = new ArrayList<String>();
   static
    {
        excludePackagesList.add("java.");
        excludePackagesList.add("android.");
        excludePackagesList.add("javax.");
        excludePackagesList.add("android.support.");
        excludePackagesList.add("sun.");
        excludePackagesList.add("com.google.");
        excludePackagesList.add("com.android.");
        excludePackagesList.add("dalvik.");
    }
`

        Options.v().set_src_prec(Options.src_prec_apk_c_j);
        
        Options.v().set_process_dir(Collections.singletonList(apkPath));

        Options.v().set_output_format(Options.output_format_dex);

        String androidJarPath = Scene.v().getAndroidJarPath(jarsPath, apkPath);

        List<String> pathList = new ArrayList<String>();

        pathList.add(apkPath);

        pathList.add(androidJarPath);

        for(File i : jimplePath) {

            pathList.add(i.getAbsolutePath());

        }
        Options.v().set_process_dir(pathList);

        Options.v().set_force_android_jar(apkPath);

        Options.v().set_keep_line_number(true);

        Options.v().set_process_multiple_dex(true);

        Options.v().set_allow_phantom_refs(true);

        Options.v().set_whole_program(true);

        Options.v().set_wrong_staticness(Options.wrong_staticness_ignore);

        Options.v().set_exclude(excludePackagesList);

        Options.v().set_no_bodies_for_excluded(true);

        Scene.v().addBasicClass("java.lang.Object", SootClass.SIGNATURES);

        Scene.v().loadNecessaryClasses();

        PackManager.v().runPacks();

and for output the apk i just call the ' PackManager.v().writeOutput(); '
There is something wrong in them?

**Comment by mbenz89** [comment]
Excludes are generally ignored if the output format is set to apk/dex,
since missing some classes in the written apk usually renders the app
unusable.
So even with excludes set, soot will read in, analyze and write out the
complete content of the provided dex file.

It might be possible to set some classes to phantom manually after the
readin process, so that these are ignored during writeout.

Jacoppy <notifications@github.com> schrieb am Do., 20. Sep. 2018, 22:25:

**Comment by mbenz89** [comment]
Actually, classes do not necessarily be set to phantom to be excluded from the write-out process. They just mustn't be application classes.

**Comment by Jacoppy** [comment]
Weel for example in the output I have java.io.BufferedInputStream and I'm pretty sure it already included in standars java.
Thhose are just redundant classes.
So the only option is just trying to set all of the as phantom?

**Comment by mbenz89** [comment]
While `BufferedInputStream` is indeed part of the Java standard lib, for Android, all required classes are packed into the APK, even standard library classes...

I think there might be more options, but this should be the easiest for you. For each application class, check if it in your exclusion list and if so, set it to library class.  You can basically just leave your options as they are and check use `soot.Scene#isExcluded` to check if a class matches your exclusion pattern.

**Comment by Jacoppy** [comment]
Okay, I have made a function of mine which understand if a SootClass is excluded or not and I'm trying this : 
 `public void exclude_classes(){
        for(SootClass c : Scene.v().getApplicationClasses()){
            if(isExcludeClass(c)){
                c.setLibraryClass();
            }
        }
    }`

But I get :

`Exception in thread "main" java.util.ConcurrentModificationException
	at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:563)
	at Soot_utlilty.exclude_classes(Soot_utlilty.java:157)`

Probably I'm not modifying the Scene correctly, I suppose :thinking:

**Comment by mbenz89** [comment]
You have to use the `snapshotIterator` when modifying classes during
iteration:

`Scene.v().getApplicationClasses().snapshotIterator() `


Jacoppy <notifications@github.com> schrieb am Fr., 21. Sep. 2018, 17:31:

**Comment by Jacoppy** [comment]
Perfect it works !
