### ISSUE TITLE
[Question] There is any in depth material on Jimple ?

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1033]
Hi, I would like to ask you if there is any in depth documentation on Jimple.
I am searching a way for recover programmatically the ouput of ActiveBody.toString(), but I'm not getting how all components interact between each others.
Thank you very much !

**Comment by mbenz89** [comment]
I suggest reading a bit through the wiki. Unfortunately, though, we do not have much in-depth material...
https://github.com/Sable/soot/wiki/Fundamental-Soot-objects
