### ISSUE TITLE
Cyclomatic complexity with soot?

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1036]
Hi again,
I would like to include also Cyclomatic complexity in my static analysis process.
I am trying to use this method : https://www.leepoint.net/principles_and_practices/complexity/complexity-java-method.html but I was wondering if it is possible to do in Soot, because I don't know how the switches, the operators and all the loops are represented.
Thank you in advance :)

**Comment by ericbodden** [comment]
Hi.

You would need to find or derive a formulation of cyclomatic complexity for generic control-flow graphs. I am sure that should be possible and I am almost sure somebody must have done this before.

**Comment by mbenz89** [comment]
For that, you can just take the `Body` of a `SootMethod` to construct an implementation of [`UnitGraph`](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/jdoc/)  of your choice. `UnitGraph` is the superclass for all control flow graphs in Soot.

**Comment by Jacoppy** [comment]
Ok nice, are all blocks saved as Units? How am I supposed to gather all the edges of the graph ?

**Comment by Jacoppy** [comment]
Should I consider the usage of BlockGraph for accomplish that?

**Comment by mbenz89** [comment]
In the `UnitGraph`each node is a Unit, i.e. a statement. 
In a `BlockGraph` each node is a basic block, which is a collection of Units.

Have a look at the APIs of the classes. `UnitGraph` has `getHeads()` and `getSuccsOf()` methods which you can use to iterate over the Graph.

**Comment by ericbodden** [comment]
A BlockGraph consists of basic blocks, and each basic block consists of a sequence of units/statements. A UnitGraph instead consists directly of units, they are not summarized by blocks.

Both types of graphs are CFGs. You should be able to use either kind of graph.

**Comment by Jacoppy** [comment]
Yup, I got my Cyclomatic Complexity :) ty mates!
