### ISSUE TITLE
How can I get the definition of a value?

### ISSUE THREAD

**Issue by FlyingOnion** [Sable/soot#1038]
For example, I have an invoke expression `a.foo(arg0);`
Then how could I find the definition (the `Unit` object) of `arg0`?
I have tried using `stmt.getInvokeExpr().getArg(0)` but this returns a `Value` object and it could only use `getUseBoxes()`.

**Comment by mbenz89** [comment]
You might want to use one of the existing DefUse analyses.
Have a look at the implementing classes of [`LocalDefs`](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/jdoc/soot/toolkits/scalar/LocalDefs.html)
