### ISSUE TITLE
Added activities to manifest out from application tag?

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1040]
Hi all, I am instrumenting the AndroidManifest.xml of some Android application but apparently the added activites, receivers, etc are all out from the <application> tag.
For example adding an activity:

```
AXmlNode activity = new AXmlNode("activity", null, axmlh.getDocument().getRootNode());
                activity.addAttribute(new AXmlAttribute<String>("name", name, namespace));
                processManifest.addActivity(activity);
byte[] axmlBA = processManifest.getAXml().toByteArray();

        FileOutputStream fileOuputStream = new FileOutputStream("./AndroidManifest.xml");
        fileOuputStream.write(axmlBA);
        fileOuputStream.close();
        List<File> fileList = new ArrayList<File>();
        File newManifest = new File("./AndroidManifest.xml");
        fileList.add(newManifest);
        ApkHandler apkH = new ApkHandler(apkPath);
        apkH.addFilesToApk(fileList);
```

How can I fix this issue? cause otherwise it seems malformed...

**Comment by mbenz89** [comment]
> etc are all out from the tag.

What do you mean by this?

As far as I know, FlowDroid's `ProcessManifest` class was never meant to be used for writing out the manifest. Thus, it might not be adding the activity as you would expect when calling `processManifest.addActivity(activity)`.

Anyway, @StevenArzt might be more able to help here...

**Comment by StevenArzt** [comment]
The ```ProcessManifest``` class doesn't have a feature to write out modified manifests at the moment. You can add data objects at runtime, but you can't write the modified manifest into a file. If you need this feature, feel free to implement it and open a merge request to contribute your work to the FlowDroid open source project.

**Comment by Jacoppy** [comment]
Oh ok, Thank you for the answer
