### ISSUE TITLE
Error: Could not find or load main class soot.Main

### ISSUE THREAD

**Issue by jessicq** [Sable/soot#1052]
Hi!

I am currently attempting to use soot with FlowCog on the command line terminal. However, while running FlowCog, I come across the error with not being able to detect the Main driver program. So with further troubleshooting, I am deducing the problem exists with not being able to find soot.jar because when attempting to run soot.Main, I receive the error shown on the title. 

I use the command: `java-cp C:\User\<username>\Documents\AndroidDataFlow\soot\eclipse\ca.mcgill.sable.soot.updatesite\plugins\ca.mcgill.sable.soot_2.5.2 jar soot.Main`

Here, I am assuming ca.mcgill.sable.soot_2.5.2.jar is equivalent to soot.jar. Otherwise, there does not seem to be a file simply named soot.jar.

If anyone could kindly shed light on this, it will be greatly appreciated. Thank you for your time.

**Comment by mbenz89** [comment]
Hi.

You are using a very old version of Soot, please retry with the [current one](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/sootclasses-trunk-jar-with-dependencies.jar).

**Comment by jessicq** [comment]
Hi mbenz89, 

It seems that using the current version fixed the issue of finding soot.Main. Thank you for taking the time to solve the issue - it is greatly appreciated!
