### ISSUE TITLE
Get args from a "new" expression

### ISSUE THREAD

**Issue by FlyingOnion** [Sable/soot#1063]
For example, `Foo foo = new Foo("bar")`
soot will treat this statement (unit) as a `JAssignStmt` object.
However, this statement does not contains any invoke expressions. 
Then how could I get the args (`Value` object of `"bar"`)?

**Comment by mbenz89** [comment]
Soot splits object allocation and the constructor call in two statement (which is also so case for bytecode).
There should be a `specialInvoke` instruction to `<Foo: void <init>(java.lang.Object)>` right after the `new` statement. This is your constructor call.
