### ISSUE TITLE
Wrong variable name, what is the correct way to get localnames as in the java class file?

### ISSUE THREAD

**Issue by TheJokerrrr** [Sable/soot#1068]
I am using soot-3.1.0-20180918.123728-71-jar-with-dependencies.jar . To get the original variable name (as in .class file) i configured,

PhaseOptions.v().setPhaseOption("jb", "use-original-names:true");
PhaseOptions.v().setPhaseOption("jj", "use-original-names:true");

options in my code, But it not give original variable names as in class files, and it give wrong variable names, it gives name of other variable which means variable names duplicated, a single variable name used by many objects, how can i avoid this? What phaseoptions i need to set?

**Comment by mbenz89** [comment]
You are only able to get variable names if the `class` files actually contain them. This is only the case if the class files were compiled with debug information.

If you do not want to have variables re-assigned, you may try to disable the local packer [1](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/options/soot_options.htm#phase_1_7) and [2](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/options/soot_options.htm#phase_19_5).
