### ISSUE TITLE
a problem about building callgraph

### ISSUE THREAD

**Issue by wshasha** [Sable/soot#1069]
hello, I design a very simple Android demo with a button and a listener(named MyListener) on it, and use soot to get its' call graph, and then I find a problem, the call graph doesn't contains the  onClick() in MyListener. Why doesn't the call graph contains the methods in listener?

**Comment by mbenz89** [comment]
`onClick()` is a callback for which Soot cannot find any callers. So there will be no edge into this method in the callgraph. Either use `FlowDroid` to build an artificial main method which calls such callbacks for callgraph generation, or try the option `all-reachable'.

**Comment by wshasha** [comment]
Thanks, I tried to set 'all-reachable' to be true, but it didn't work. So recently I am trying to find a way to produce dummy main   method for callbacks.I read the paper about flowdroid, says it supports callbacks, but when I read the flowdroid code, find out it only produces entry points for Activity, Service, Provider and receiver which appears in the manifest. Maybe I should I should find a way to build main method, thanks for your advice.

yours
Jane

**Comment by wshasha** [comment]
well, I still don't find the code to handle UI callbacks and would you mind tell me what the relative java classes or methods?

Thanks, yours
Jane

**Comment by StevenArzt** [comment]
FlowDroid collects the callbacks and places them into the dummy main method within the "running" state of the respective component. This is done automatically, you don't need any special code or handling. FlowDroid looks for callbacks registered in the code and in the layout XML files. If you're curious about how it works, you can have a look at the ```calculateCallbackMethods()``` method in the ```SetupApplication``` class. However, as I said, this is all triggered under the hood, you only call ```SetupApplication.constructCallgraph()```.

**Comment by wshasha** [comment]
well, I still don't find the code to handle UI callbacks and would you mind tell me what the relative java classes or methods?

Thanks, yours
Jane

**Comment by wshasha** [comment]
Would you mind tell me what the relative java classes or method? Thanks for your teply.

yours
Jane

**Comment by wshasha** [comment]
Okay, thanks~

**Comment by wshasha** [comment]
I am such a fool that forgot to copy AndroidCallbacks.txt to my new project💀 .Thus empty AndroidCallbacks.txt led to this problem. 
     Thank you guys.

yours
Jane
