### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by husam88** [Sable/soot#1072]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-w -p cg.gui enabled:true -f n -keep-line-number -allow-phantom-refs -process-multiple-dex -process-dir /home/husam/Desktop/APK/a2dp.apk -cp /home/husam/platforms/android-25/android.jar:</pre>

Max Memory:
<pre>10923MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path &#39;/home/husam/platforms/android-25/android.jar&#39; does not exist.
	at soot.SourceLocator.getClassSourceTyp

**Comment by mbenz89** [comment]
Do not pass the Android jar by using the `-cp` (classpath) option. There is an Android jar dir option: `-android-jars path` which you have to pass the `platforms` dir of your sdk or `-force-android-jar path` which you can use to pass a specific jar directly.
