### ISSUE TITLE
Soot Analysis of Android Application Problems

### ISSUE THREAD

**Issue by DavideLin** [Sable/soot#1076]
When I used Soot to analyze Android applications, I added Sdk/platforms/android-* and APK files to the command line, but an error message prompted Scene. V (). loadNecessaryClasses () method to have problems.
Error:
      soot.JastAddJ.Program.initPaths(Program.java:336)
      soot.SootResolver.<init>(SootResolver.java:88)
      soot.Singletons.soot_SootResolver(Singletons.java:1913)
      soot.SootResolver.v(SootResolver.java:93)
      soot.Scene.tryLoadClass(Scene.java:841)
      soot.Scene.loadBasicClasses(Scene.java:1504)
      soot.Scene.loadNecessaryClasses(Scene.java:1583)
      soot_analysis.SootAnalysis.run(SootAnalysis.java:511)
      soot_analysis.SootAnalysis.fp1(SootAnalysis.java:80)
      soot_analysis.SootAnalysis.main(SootAnalysis.java:57)
Is there anything wrong with this?

**Comment by mbenz89** [comment]
First of all, to better help you, it's in your interestest to provide comprehensive information on your problem, i.e., what is the exact command line you are trying to execute?
From what I can tell, you are providing the wrong thing as android platforms dir. It should be `/PATH/TO/ANDROID/SDK/platforms`.

This should help: https://github.com/Sable/soot/wiki/Instrumenting-Android-Apps-with-Soot
And here are the command-line options: https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/options/soot_options.htm#section_2

**Comment by DavideLin** [comment]
I'm sorry for the way I asked my questions.
In the output string, he prompts that:
Using "/PATH/TO/ANDROID/SDK/platforms/android-26/android,jar"as android.jar
