### ISSUE TITLE
Why classes in folder are not found 

### ISSUE THREAD

**Issue by Garenyan** [Sable/soot#1097]
![image](https://user-images.githubusercontent.com/25759992/51229945-3916d880-1999-11e9-94e4-9c07488f5b6e.png)

**Comment by mbenz89** [comment]
This is a very old version of Soot. Please download an [up-to-date one](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/sootclasses-trunk-jar-with-dependencies.jar).

Also, `-process-path` and `-process-dir` are both the same option! You only need to set either of them. [For reference](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/options/soot_options.htm).
