### ISSUE TITLE
Soot does not handle methods with polymorphic signature correctly

### ISSUE THREAD

**Issue by anddann** [Sable/soot#1108]
As described in https://docs.oracle.com/javase/specs/jls/se11/html/jls-15.html#jls-15.12.4.4
method references to the methods with a polymorphic signature, which are the methods in `java.lang.invoke.MethodHandle` and `java.lang.invoke.VarHandle`, require special treatment.
see pr #1109

**Comment by anddann** [comment]
Proposal: If a reference to such a method is resolved, we create a native method without body for it.
This is exactly what the JVM does https://stackoverflow.com/questions/13978355/on-signature-polymorphic-methods-in-java-7 and the JVM spec above.
Does this have any side-effects when writing out code? Are we writing out code for native methods anyway?

**Comment by mbenz89** [comment]
Fixed by #1108
