### ISSUE TITLE
How to exclude unnecessary analysis when generating callgraph?

### ISSUE THREAD

**Issue by yuhang-lin** [Sable/soot#1113]
I tried using callgraph to analyze a simple package written by myself. Soot ran for 1 minutes and generated a giant callgraph with lots of edges from Java libraries, which I don't need. How can I only analyze the package I want when generating the callgraph?

**Comment by ShengliangD** [comment]
I have exactly the same question.

**Comment by ShengliangD** [comment]
#1024 seems to show somethings useful, though I haven't tried yet.

**Comment by mbenz89** [comment]
You can add packages (`com.xy.*`) or classes (`com.xy.z`) to Soot's exclude list. Excluded classes will not be set to phantom and not processed by Soot in any way. These will thus not be contained in your call graph.

Use exclusions like this:

```
List<String> excludePackagesList = Arrays.asList({"com.xy.*", "com.zzz.Klass"});
Options.v().set_exclude(excludePackagesList);
Options.v().set_allow_phantom_refs(true);
Options.v().set_no_bodies_for_excluded(true);
```

**Comment by Kenzku** [comment]
@mbenz89 a followup question:

I tried to find out what syntax I can put in the `set_exclude` list, but the API doc seems pretty empty:

https://www.sable.mcgill.ca/soot/doc/soot/options/Options.html#set_exclude(java.util.List)

```
set_exclude

public void set_exclude(List setting)
```

then I tried to exclude some libs for testing purpose, it feels like it works, but not fully excluding as per the list:

```
List<String> excludePackagesList = Arrays.asList("java.*", "com.google.*", "com.*", "javax.*");
Options.v().set_exclude(excludePackagesList);
Options.v().set_no_bodies_for_excluded(true);
Options.v().set_allow_phantom_refs(true);
```

then I have a breakpoint here

```
SootClass[] libClasses = Scene.v().getLibraryClasses().toArray(new SootClass[0]);
System.out.println("Lib classes: " + libClasses.length);
```

I can see the libClasses still contains e.g. `java.lang.Integer` which was supposed to be excluded

<img width="857" alt="Screenshot 2021-01-28 at 16 12 54" src="https://user-images.githubusercontent.com/1387249/106167090-c2666580-6184-11eb-8492-161c6ae2418f.png">

there were around 700 lib classes, for a 2 simple classes, less than 20 lines each. e.g. I am pretty sure my classes do not call any of the `com.google.*` but they still appear in the `Scene.v().getLibraryClasses().toArray(new SootClass[0]);`

Do you have some pointers to docs or resources related to how to exclude libs, before they are loaded to the memory by soot? and what do `set_no_bodies_for_excluded` and `set_allow_phantom_refs` mean please

**Comment by patricklam** [comment]
I'm not sure why com.google shows up, but 700 library classes is consistent
with what we've seen in the distant past: you use String and then it brings
in everything. Allow phantom refs should decrease that but your call graph
is going to be incomplete.

**Comment by Kenzku** [comment]
@patricklam 

Hej, thanks for your reply, but I guess my questions really were, 

1. do you have a pointer to the exclusion syntax? e.g. if I want  too exclude all `com.*` packages, but I want to keep `com.ibm.*`
2. API docs having descriptions for me to understand what does `set_no_bodies_for_excluded` and `set_allow_phantom_refs` do?

or could you please let me know some active communication channels where I may find some pointers. thanks

**Comment by chaicho** [comment]
@Kenzku 
I have encountered the same problem. Have you got any idea why this happens? It would be helpful if you can help me with it.
