### ISSUE TITLE
How work -exclude option

### ISSUE THREAD

**Issue by damorosodaragona** [Sable/soot#1133]
Hi, 
i have a simple question, what happen when i use this tree options together?
```
-allow-phantom-refs
-no-bodies-for-excluded
-exclude
[pkg to exclude]
```
For example in this situation: 
```
 public class Main {   
    public static void main(String[] args) { 
        MyHashMap<String,String> myHashMap = new MyHashMap<String,String>();      
       System.out.println(myHashMap); } }

public class MyHashMap<K,V> extends HashMap<K,V> { 
    public void clear() { } 
    public int size() { return 0; } 
    public String toString() { return "MyHashMap"; } }
```
I know that normally spark generate this call-graph:
![image](https://user-images.githubusercontent.com/15249587/54535257-73e3bf80-498e-11e9-900d-e3697a530062.png)

With that option, if i exclude java packages, what happens?
Soot load, only if necessary, the class excluded?

**Comment by mbenz89** [comment]
Soot will not analyze the internals of classes that are in excluded packages. Therefore, the call graph will, for example, contain edges into methods in excluded classes but would not contain edges that origin from the excluded method due to not analyzing its internals.
