### ISSUE TITLE
Issue loading Java Class

### ISSUE THREAD

**Issue by franceme** [Sable/soot#1140]
- Soot Version - 3.3.0_Nightly-With-Dependencies
- Java Version (Stable) - 1.7.80
- Java Version (Issue) - 1.8.192
- Steps to reproduce - I can attach steps to reproduce later if needed.
---
Currently within my project, this scenario reads in a single java file (*.java), loads it into Soot's Scene, scans it, and displays information.

The java class loading method (used and working in other scenarios) is as shown below. 
```Java
Options.v().setsrc_prec(Options.src_prec_only_class);
Options.v().set_output_format(Options.output_format_jimple);
...
Options.v().set_prepend_classpath(true);
Options.v().set_whole_program(true);
...
Options.v().set_keep_line_number(true);
Options.v().set_allow_phantom_refs(true);
...
/**
 * Java File Package = tester
 * Java File = UrlFrameWorks.java
 *
 * variable clazz = tester.UrlFrameWorks
**/
Scene.v().loadClassAndSupport(clazz);
```
When the project is run on Java 1.7.80, the java file is loaded successfully and scanned with no issues.
However when run with the later Java Version (1.8.192), it throws a failure loading java.lang.CharSequence.
A trimmed excerpt of the stacktrace is shown below.

```
java.lang.Error: Error: Failed to load java.lang.CharSequence.
	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:109)
	at soot.JastAddJ.Program.getCompilationUnit(Program.java:873)
	at soot.JastAddJ.Program.getLibCompilationUnit_compute(Program.java:1517)
	at soot.JastAddJ.Program.getLibCompilationUnit(Program.java:1500)
	at soot.JastAddJ.Program.lookupLibType_compute(Program.java:1465)
	at soot.JastAddJ.Program.lookupLibType(Program.java:1433)
	at soot.JastAddJ.Program.lookupType_compute(Program.java:1412)
	at soot.JastAddJ.Program.lookupType(Program.java:1393)
	at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:1981)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
```

Is there an extra step to be called due to the version upgrade?

---
##### An important note to add, the java file being loaded may or may not have the entry point (main(...)) of the entire program.
---

**Comment by franceme** [comment]
I would like to add the following update.

It seems as though this is an issue when using any version of Java past 1.7.
I have found this due to the following other related issues: [775 ](https://github.com/Sable/soot/issues/775)and [896](https://github.com/Sable/soot/issues/896).

As the new question (or clarification), scanning Java source files (*.java) are not supported?

**Comment by anddann** [comment]
Unfortunately, the Java Source Code frontend is outdated.
I suggest to use Soot's ASM bytecode frontend. It supports more
language features and is more powerful.
