### ISSUE TITLE
Does soot support Arbitrary Number of Arguments?

### ISSUE THREAD

**Issue by RichardHoOoOo** [Sable/soot#1159]
Does soot support Arbitrary Number of Arguments (i.e., "...")?

For example, I have a static method which takes arbitrary number of String arguments as input:

`public static void foo(String... s)`

Then I get this method using `myMethod = myClass.getMethodByName("foo")` where myClass is the class that contains foo.

But when I invoked this method using `Jimple.v().newStaticInvokeExpr(myMethod.makeRef(), values)` where values is a list of String constants, I got the following error: _**Worker thread execution failed: Invalid number of arguments**_. It is because soot is calling this method like this: `void foo(java.lang.String[])>("s1", "s2", "s3")`

Obviously the number of arguments is invalid (1 vs. 3), but how can I call a method that takes arbitrary number of arguments? Should I create a local array that holds the Strings every time I want to use this method?

**Comment by mbenz89** [comment]
The feature you are describing is called **varargs**. Varargs is a convenience feature in source code and is just syntactic sugar for an array of the given type. 

Sourcecode:
```
public static void foo(String... s) 

foo("s1", "s2");
```

Bytecode:
```
public static void foo(String[] s) 

foo(new String[] {"s1", "s2"});
```

In this regard, Jimple is closer to the bytecode representation. Thus, you need to create an array with your values first and pass it to `foo`.

**Comment by RichardHoOoOo** [comment]
I see. Thanks for your prompt reply!
