### ISSUE TITLE
Trap splitter stuck after performance update

### ISSUE THREAD

**Issue by mbenz89** [Sable/soot#1165]
After the performance update in ef9ce0e3025f8c48f702904df155fd2f30113d80, the `soot.toDex.TrapSplitter` seems to run in an infinite loop when trying to write-out arbitrary apps.

To reproduce, run the provided code analyzing the provided app. Set a breakpoint in `soot.toDex.TrapSplitter#internalTransform` either after some time or do it conditionally to halt when the problematic body is transformed. (Condition: `b.getMethod().toString().equals("<android.support.v7.graphics.drawable.AnimatedStateListDrawableCompat: android.support.v7.graphics.drawable.AnimatedStateListDrawableCompat create(android.content.Context,int,android.content.res.Resources$Theme)>")`) 

```
package soot;

import java.util.Collections;
import soot.options.Options;

/**
 * @author Manuel Benz at 2019-06-14
 */
public class ReproduceStuckWriteout {

  public static void main(String[] args) {
    Options op = Options.v();
    op.set_output_format(Options.output_format_force_dex);
    op.set_process_multiple_dex(true);
    op.set_src_prec(Options.src_prec_apk);
    op.set_process_dir(Collections.singletonList("./menus-debug.apk"));
    op.set_android_jars(System.getenv("ANDROID_HOME") + "/platforms");

    Scene.v().loadNecessaryClasses();

    PackManager.v().runPacks();
    PackManager.v().writeOutput();
  }
}

``` 

This makes Soot impossible to use for reading-in and writing-out apps afterward. We should either fix this quickly or revert the performance update.

Note that the attached zip file is indeed an apk file, I had to rename it so that GitHub accepts it.

[menus-debug.zip](https://github.com/Sable/soot/files/3290747/menus-debug.zip)

**Comment by StevenArzt** [comment]
I'll have a look. The changes should normally be semantics-preserving, maybe there is a bug in the range-limited iterator. I need to debug this to be sure.

**Comment by StevenArzt** [comment]
The iterator with start and end unit includes the end unit in its iteration range, which is incorrect for traps, because the end unit is the first unit after the trap, i.e., is in itself not part of the trap. Fixed by reverting the optimization for traps.
