### ISSUE TITLE
Wrong ClassConstant value when loading classfile built with Jasmin

### ISSUE THREAD

**Issue by Aztorius** [Sable/soot#1167]
Tested with Soot 3.3.0 and Java 1.8
Inside a bytecode we may have some Class constants but for some reasons i can generate an invalid classfile from a valid classfile using the Jasmin backend with soot.
Let me explain in details : 
- Test.java uses some Class<?> and is compiled with javac to get a valid Test.class (1)
- This Test.class (1) is then used as an input with Soot to get a valid Test.jimple (1)
- Then Test.jimple (1) is transformed into a Test.class (2) using the Jasmin backend. The resulting Test.class (2) works with java but the bytecode instructions differs from the ASM backend.
- Finally we load Test.class (2) inside Soot to get a Test.jimple (2) that is invalid. In fact class constants becomes LLjava/lang/...;; which is invalid.

As the bytecode generated by the Jasmin back-end works with java, it is most likely a parser issue than a back-end issue.

The main differences between Jasmin and ASM backend regarding Class constants is the use of ldc_w instead of ldc and different corresponding Utf8 string (Ljava/lang/...; instead of simply java/lang/...). Everything can be analysed with `javap -verbose Test.class`.

All the files described are joined with this issue.
[bug_class_constant.tar.gz](https://github.com/Sable/soot/files/3324443/bug_class_constant.tar.gz)

**Comment by mbenz89** [comment]
Thanks for investigating this issue!

Jasmin is not maintained anymore so I wouldn't be surprised if it would produce bytecode that can be executed but does not correspond to the assumptions made by ASM.

Though, the fix might be to make ASM aware of this special case "ldc_w" rather than touching ASM. 

We would be happy to accept a pull request if you find time to fix this!

**Comment by Aztorius** [comment]
In fact when loading Test.class (2) with Java 9+ we get `java.lang.ClassFormatError: Illegal class name "Ljava/lang/String;" in class file Test`.
So Jasmin build an invalid class file, but JVM before Java 9 does not properly reject the class and try to continue anyway. Also according to bytecode spec it should be using the ldc instruction and not ldc_w (which is used for wide formats like long and double only).

It may be related with https://gitlab.ow2.org/asm/asm/issues/317801 . ASM seems to not check at all the class constant format and just suppose that it is the correct one (and thus append L...;). Either ASM should reject such class files or check and fix the CONSTANT_Class value.
Also I quickly check soot/asm/AsmUtil.java but it seems good to me, so the bug seems to be in ASM itself.

**Comment by mbenz89** [comment]
We should then probably fix the wrong instruction in Jasmin then. 

Is there a reason you are using Jasmin over ASM? ASM should be the default (and indeed only maintained) bytecode parser in Soot.

**Comment by Aztorius** [comment]
No reason except it was the recommended way in the Wiki https://github.com/Sable/soot/wiki/Creating-a-class-from-scratch#write-to-class-file . I committed a small change to provide source code of how to use ASM instead of Jasmin when using directly the backend.
My project is running with ASM backend now, so I don't have this issue any more.

**Comment by mbenz89** [comment]
Thanks for fixing the Wiki. I appreciate that!
