### ISSUE TITLE
sunrsasign.jar does not exist

### ISSUE THREAD

**Issue by askary94** [Sable/soot#1177]
Hello.
I use of java8 and Soot3.3
I when use of `(Scene.v()).loadClassAndSupport(className);`, I give a follow error 
`java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/usr/lib/jvm-oracle/jdk1.8.0_172/jre/lib/sunrsasign.jar' does not exist.`
Does soot use `sunrsasign` ? I search and found that `sunrsasign` is in rt.jar file (based on `https://www.findjar.com/class/sun/security/rsa/SunRsaSign.html`)
how can correct it?
Regards

**Comment by anddann** [comment]
what application/classes/code are you trying to analyze?
What is your classpath?
