### ISSUE TITLE
Empty SootClass java.lang.invoke.MethodHandle

### ISSUE THREAD

**Issue by Aztorius** [Sable/soot#1187]
When calling `Scene.v().loadClassAndSupport("java.lang.invoke.MethodHandle")` the returned SootClass is at the resolving level SIGNATURES (0x2) but no methods are included (https://docs.oracle.com/javase/8/docs/api/java/lang/invoke/MethodHandle.html).

Is there any reason why it happens only with MethodHandle ? It works well with MethodHandles or any other class.

**Comment by anddann** [comment]
When I execute the following code on JDK 1.8
```
    G.reset();
    Options.v().set_prepend_classpath(true);
    Scene.v().loadBasicClasses();
    SootClass sootClass = Scene.v().loadClassAndSupport("java.lang.invoke.MethodHandle")
```
I get the class on resolving level 3, with a method list of length 43.


What soot version are you using and which JDK?

**Comment by Aztorius** [comment]
```
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```
With Soot 3.3.1-SNAPSHOT (latest).
I will double check this bug with a simple program.

**Comment by Aztorius** [comment]
It appears that getSootClassUnsafe("java.lang.invoke.MethodHandle") returns a non-null SootClass but with no methods while calling this method for other classes returns null. I then call loadClassAndSupport() only if getSootClassUnsafe() returns null in order to not load two times the same class.

**Comment by Aztorius** [comment]
Well, it appears it works well (and fast !) with `loadClassAndSupport(...)` so it is not an issue for me anymore. Maybe the `getSootClassUnsafe()` deserves investigations for its return value.
For now I close this.
