### ISSUE TITLE
Exposing SourceLocator.v().getClassesUnder(path, prefix)

### ISSUE THREAD

**Issue by karimhamdanali** [Sable/soot#1195]
Hi Soot maintainers,

I was wondering if there is a reason why [SourceLocator.v().getClassesUnder(path, prefix)](https://github.com/Sable/soot/blob/develop/src/main/java/soot/SourceLocator.java#L306) is a private method and not exposed publicly?

I have been in many situations now (and more recently in a research project that I'm working on) where I find myself in need of knowing the classes (as a list of strings) in a certain directory that may contain subdirectories, class files, jar files, zip archives etc. Setting the Options.v().process_dir() is not enough because it assumes that this directory is the root package of the classes within, which is not necessarily true.

My current solution is basically to duplicate all the work that [SourceLocator.v().getClassesUnder(path, prefix)](https://github.com/Sable/soot/blob/develop/src/main/java/soot/SourceLocator.java#L306) in my own code to be able to provide a package prefix for the class names, which I find redundant given that that code is right there in Soot, just in a private method.

Any plans on exposing that method in the public API?

Thanks.

- Karim

**Comment by mbenz89** [comment]
Hi Karim.

I guess there is no apparent reason other than encapsulation. I don't see any reason why we should keep this method hidden from external use.

I would be happy to merge a pr that opens up the method for public usage. However, a few lines of jdoc would help to understand what to expect of its usage :).

Best,
Manuel

**Comment by karimhamdanali** [comment]
Thanks Manuel. I looked further into what I wanted to do with Soot for my use case, and I was able to achieve it without having to expose that method publicly. For the sake of encapsulation, I agree that it's best to keep this method private.

Thanks again!

**Comment by karimhamdanali** [comment]
It turns out that my workaround eventually evolved to me more or less what this method does. So I've created the PR #1202 that exposes this method publicly.

**Comment by anddann** [comment]
PR merged.
