### ISSUE TITLE
Roadmap for Soot

### ISSUE THREAD

**Issue by sdibernardo** [Sable/soot#1215]
I was wondering if there is an official roadmap of Soot, especially with regards to the latest Java versions. Is the ongoing development already including the changes introduced with the latest versions? When is Java 9 going to be fully supported in the releases? 

Any information regarding the longterm development of Soot will be appreciated, as we highly rely on Soot to analyze given source code.

Best regards

**Comment by mbenz89** [comment]
Are you aware of the Java 9 branch? It contains all sorts of supporting features for Java 9-11. Not sure about feature completeness. Maybe @anddann can give a statement about that.
We will soon merge and release those features...

Regarding the longterm development of Soot, @ericbodden might be able to say more about that.

**Comment by sdibernardo** [comment]
Yes I know of the Java 9 branch, but due to security restrictions we rely on official releases available in Maven Central. As of now, no such release including Java 9-11 is available (correct me if I'm wrong). Do you plan on integrating the support for those versions into the upcoming release versions?

**Comment by mbenz89** [comment]
Yes, a proper release of the java9 branch (containing support for all current java versions beyond 8) is scheduled for the next to weeks.

**Comment by sdibernardo** [comment]
Awesome, thank you 💯

**Comment by mbenz89** [comment]
As you might have noticed, there are _slight_ delays in merging in the Java > 8 features. Unfortunately, we are a bit out of manpower currently. We are working on merging the feature asap.

**Comment by mbenz89** [comment]
__Soot 4.0.0__ with support for Java > 8 was just released. Please have a look at the [README](https://github.com/Sable/soot/blob/master/README.md) for further information.

Merry Christmas!

**Comment by ericbodden** [comment]
Thanks a lot Manuel!

--
Sent from my mobile
________________________________
Von: Manuel Benz <notifications@github.com>
Gesendet: Samstag, 28. Dezember 2019 01:30
An: Sable/soot
Cc: Eric Bodden; Mention
Betreff: Re: [Sable/soot] Roadmap for Soot (#1215)


Soot 4.0.0 with support for Java > 8 was just released. Please have a look at the README<https://github.com/Sable/soot/blob/master/README.md> for further information.

Merry Christmas!

-
