### ISSUE TITLE
java.lang.RuntimeException: Could not load classfile: java.lang.CharSequence

### ISSUE THREAD

**Issue by PetePro** [Sable/soot#1223]
When I use soot to develop eclipse plugin, in statement
`Scene.v().loadClassAndSupport(StructureCoverageTransformer.MONITOR);`
where `StructureCoverageTransformer.MONITOR` is a string, I ran into this error:
`java.lang.RuntimeException: Could not load classfile: java.lang.CharSequence`. 
Is there any solutions to this problem. 
My OS is Windows10 and jdk is 1.8.

**Comment by anddann** [comment]
What classpath are you using on which jdk? Closed until more information is provided.
