### ISSUE TITLE
[Question] Recognize nested conditions

### ISSUE THREAD

**Issue by JordanSamhi** [Sable/soot#1226]
Hello,

A major feature of Java bytecode transformation into Jimple is the flattening of the code which is convenient for analysis.
But I happen to need to recognize if in a method, 2 conditions are nested, regarless of the length of the separation of the two conditions.
Example:

```java
if(condition1){
    //code
    if(condition2){
        //code
    }
    //code
}
```
I have analyzed Jimple classes with nested and not nested conditions, I am not able to find any pattern with nested conditions, only gotos in both cases.

Is there a way -in Jimple- to detect that kind of Java code structure ?

Thank you in advance.

**Comment by Alexandre-Bartel** [comment]
You might want to computer dominance frontiers.
In your example, the statement if(condition1) dominates statement if(condition2).
Soot provides classes to compute this. Have a look at the javadoc here: 
https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/jdoc/

Please use the mailing list for your next questions:
https://github.com/Sable/soot/wiki/Getting-help

**Comment by JordanSamhi** [comment]
I didn't know about those classes, thank you !
