### ISSUE TITLE
soot

### ISSUE THREAD

**Issue by Shabnam-t** [Sable/soot#1235]
hello, I try to install soot as plug in of Eclipse but the link is not working.

**Comment by qc1iu** [comment]
I think it better to use soot as an independent tool.

**Comment by Shabnam-t** [comment]
Thank you so much,I am beginner user soot.if I want using independent soot
how can I do?could you have any suggestion for learning it step by step?
Cheers

**Comment by qc1iu** [comment]
https://github.com/Sable/soot/wiki

**Comment by Shabnam-t** [comment]
Thank you so much
