### ISSUE TITLE
soot.jimpl.ClassConstant  LongType  error

### ISSUE THREAD

**Issue by 344389541** [Sable/soot#1242]
soot.jimpl.ClassConstant

 private static String sootTypeToString(Type tp) {
    if (tp instanceof RefType) {
      return "L" + ((RefType) tp).getClassName().replaceAll("\\.", "/") + ";";
    } else if (tp instanceof ArrayType) {
      ArrayType at = (ArrayType) tp;
      return "[" + sootTypeToString(at.getElementType());
    } else if (tp instanceof PrimType) {
      if (tp instanceof IntType) {
        return "I";
      } else if (tp instanceof ByteType) {
        return "B";
      } else if (tp instanceof CharType) {
        return "C";
      } else if (tp instanceof DoubleType) {
        return "D";
      } else if (tp instanceof FloatType) {
        return "F";
      } else if (tp instanceof LongType) {
        return "L";
      } else if (tp instanceof ShortType) {
        return "S";
      } else if (tp instanceof BooleanType) {
        return "Z";
      } else {
        throw new RuntimeException("Unsupported primitive type");
      }
    } else {
      throw new RuntimeException("Unsupported type" + tp);
    }
  }

LongType should  return "J",  not "L"。

**Comment by qc1iu** [comment]
Good catch! This problem seems not effect the correctness  , but it's not in line with the convention.

**Comment by user501254** [comment]
I think this can be closed. https://github.com/Sable/soot/blob/de3dd7e0667b7f7bfdf47e1c41d7ae302d73deb7/src/main/java/soot/jimple/ClassConstant.java#L75-L76
