### ISSUE TITLE
How to access to real names of variables in Soot?

### ISSUE THREAD

**Issue by setareA** [Sable/soot#1246]
I am using Soot to analyze android applications. In my analysis class, I can access the jimple representation code. 
for example, the jimple representation of the following code 
```
button =  findViewById(R.id.button);
```
is:
```
$r4 = virtualinvoke $r0.<com.setare.myapplication.MainActivity: android.view.View
findViewById(int)>(2131165218)
```
Is there any way to access the real name of **r4**  which is "button"?
or Is there any way to get the real **id**  which is passed as an argument in "findViewById" method?

This is how I create the call graph:
```
public static void main(String[] args) {
   SetupApplication app = new SetupApplication(args[1], args[0]);
        Options.v().setPhaseOption("jb", "use-original-names:true");
        G.reset();
        app.constructCallgraph();
        Scene.v().loadNecessaryClasses();
        SootMethod dummyMain = app.getDummyMainMethod();
        icfg = new InfoflowCFG();
        DirectedGraph<Unit> dummyMainGraph = icfg.getOrCreateUnitGraph(dummyMain);
        new ResourceAndWakelockAnalysis(dummyMainGraph);
}
```
This is how I access r4 (left operand of the statement):
```
AssignStmt assignStmt = (AssignStmt) s;
assignStmt.getLeftOp();
```

**Comment by sdibernardo** [comment]
Afaik, during the translation to Jimple, the real names are replaced by the names you see, i.e. `$r = xy `or `r = xy`.

**Comment by ericbodden** [comment]
Hi.

Soot has this option:

-p jb use-original-names:true

If this is enabled, it tries to keep original variable names. For this to work, the names must be embedded in the app’s bytecode, though, which is not always the case.

Cheers
Eric

**Comment by setareA** [comment]
@ericbodden  thanks.
