### ISSUE TITLE
can not find rt.jar in jdk 13

### ISSUE THREAD

**Issue by Shabnam-t** [Sable/soot#1255]
hello I give this error when run my code in eclipse.

**Comment by sdibernardo** [comment]
Since Java 9, the rt.jar library has been removed due to modularization of the JKD. Additionally, the official release of Soot currently only supports up to Java 8. You might want to check the java9 branch and see if the problem persists.

**Comment by Shabnam-t** [comment]
Thank you for your response

**Comment by Shabnam-t** [comment]
ANSWERING MY QUESTION
