### ISSUE TITLE
Interactive lab to view translated Soot IR

### ISSUE THREAD

**Issue by thepalbi** [Sable/soot#1324]
Hi!
I'm working with soot for some static analysis course, and while working I figured it be nice to have a tool similar to [SharpLab](http://sharplab.io/), that let's one view the translated version (in Jimple for example) of some Java code.
I'm in the process of building it, but I'm having some trouble with the following situation:
1. Configure the `Options.v()` to have in the classpath a newly generated JAR file with the input source code (let's call the class I'm interested in `A1`).
2. Run the following snippet to run the `Jimple Body Pack` and have the `Scence` contain the Jimple-compiled class.
```java
        Scene.v().addBasicClass(classDeclaration.get().getFullyQualifiedName().get());
        Scene.v().loadNecessaryClasses();
        PackManager.v().runBodyPacks();
```
3. Extract the class. To sth. with it.
3. Configure `Options.v()` with yet another JAR, containing `A2`.
4. Run the same snippet as in 2.
5. When I try to extract the `SootClass` for `A2`, it seems the class has been discovered, but the body has not been parsed/translated.

I'm just interested in the `Java Bytecode` to `Jimple` stage. Do you have any recommendations on how to achieve this?

**Comment by StevenArzt** [comment]
Are you resetting Soot before changing the options and trying to continue with a different imput JAR? ``G.reset()`` should do the trick. Then simply repeat the initialization from step 2. Alternatively, you can also put all of the JARs on the process-dir right from the start. That might save some time, because Soot doesn't need to re-initialize (although you might need more memory, because you load everything at once instead of one JAR at a time).

**Comment by thepalbi** [comment]
Thanks @StevenArzt , that did the trick.
Regarding the second answer, that can't be done since I'm using Soot in a per-request basis. For example, a user writes some Java code, submits the request to the backed, and Soot compiles/translates the source to Jimple. When another request comes, Soot will re-run the JBP to generate the new Jimple code.
Here's a a simplified version of what I'm doing:
```
sourceCodeToJimple(String sourceCode):

    sourceCode = modify class name to be unique
    compile and package source code in a JAR file
    Options.v().set_process_dir(path to JAR)
    Scene.v().loadNecessaryClasses()
    PackManager.v().runBodyPacks()
    sootClass = Scene.v().getSootClass(unique temporary class fully qualified name)
    return "translate class with Printer.v()"
```
I'm wondering if there's some way to just leverage the Jimple translation by using something other than what I wrote?

**Comment by StevenArzt** [comment]
In your case, you will have to re-initialize Soot, I guess. If the indivdual JARs are not enormously big, and you don't get dozens of requests per second, you should be fine.

**Comment by thepalbi** [comment]
Perfect! Also, Soot maintains a state at a static-class level, right? So two `sourceCodeToJimple` request won't be handled concurrently?

**Comment by StevenArzt** [comment]
You should synchronize your method, since you can't easily have two Soot instances running concurrently inside the same JVM. A ``synchronized`` keyword on your method should be enough.

**Comment by thepalbi** [comment]
Thanks for the help @StevenArzt ! Will post a link once I have something running.
