### ISSUE TITLE
Failed to resolve .java file with jdk 1.8 in command line

### ISSUE THREAD

**Issue by Isaac-Graham** [Sable/soot#1332]
Hello there. I am trying to use soot to convert .java file to jimple representation in the command line. In my PC, I have tried with the command `java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp .;%JAVA_HOME%/jre/lib/rt.jar -src-prec java Main` and `java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp -src-prec java Main` without Main.class but Main.java. However, both of them failed because `Exception in thread "main" java.lang.Error: Error: Failed to load java.lang.CharSequence.` Is there anything wrong in my configuration?

The whole stack trace is given as follows:

> Soot started on Thu Apr 02 14:02:33 CST 2020
> Exception in thread "main" java.lang.Error: Error: Failed to load java.lang.CharSequence.
>         at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:109)
>         at soot.JastAddJ.Program.getCompilationUnit(Program.java:873)
>         at soot.JastAddJ.Program.getLibCompilationUnit_compute(Program.java:1517)
>         at soot.JastAddJ.Program.getLibCompilationUnit(Program.java:1500)
>         at soot.JastAddJ.Program.lookupLibType_compute(Program.java:1465)
>         at soot.JastAddJ.Program.lookupLibType(Program.java:1433)
>         at soot.JastAddJ.Program.lookupType_compute(Program.java:1412)
>         at soot.JastAddJ.Program.lookupType(Program.java:1393)
>         at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:1981)
>         at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
>         at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
>         at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
>         at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
>         at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
>         at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
>         at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
>         at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
>         at soot.JastAddJ.Expr.lookupType(Expr.java:1186)
>         at soot.JastAddJ.TypeAccess.decls_compute(TypeAccess.java:425)
>         at soot.JastAddJ.TypeAccess.decls(TypeAccess.java:414)
>         at soot.JastAddJ.TypeAccess.refined_TypeScopePropagation_TypeAccess_decl(TypeAccess.java:387)
>         at soot.JastAddJ.TypeAccess.decl_compute(TypeAccess.java:460)
>         at soot.JastAddJ.TypeAccess.decl(TypeAccess.java:452)
>         at soot.JastAddJ.TypeAccess.type_compute(TypeAccess.java:590)
>         at soot.JastAddJ.TypeAccess.type(TypeAccess.java:583)
>         at soot.JastAddJ.ParameterDeclaration.type_compute(ParameterDeclaration.java:479)
>         at soot.JastAddJ.ParameterDeclaration.type(ParameterDeclaration.java:472)
>         at soot.JastAddJ.MethodDecl.signature_compute(MethodDecl.java:1503)
>         at soot.JastAddJ.MethodDecl.signature(MethodDecl.java:1488)
>         at soot.JastAddJ.TypeDecl.localMethodsSignatureMap_compute(TypeDecl.java:2683)
>         at soot.JastAddJ.TypeDecl.localMethodsSignatureMap(TypeDecl.java:2669)
>         at soot.JastAddJ.ClassDecl.methodsSignatureMap_compute(ClassDecl.java:1102)
>         at soot.JastAddJ.ClassDecl.methodsSignatureMap(ClassDecl.java:1094)
>         at soot.JastAddJ.TypeDecl$2.<init>(TypeDecl.java:513)
>         at soot.JastAddJ.TypeDecl.methodsIterator(TypeDecl.java:512)
>         at soot.JastAddJ.TypeDecl.methodsNameMap_compute(TypeDecl.java:2619)
>         at soot.JastAddJ.TypeDecl.methodsNameMap(TypeDecl.java:2608)
>         at soot.JastAddJ.TypeDecl.memberMethods(TypeDecl.java:2578)
>         at soot.JastAddJ.AbstractDot.Define_Collection_lookupMethod(AbstractDot.java:766)
>         at soot.JastAddJ.Expr.lookupMethod(Expr.java:1032)
>         at soot.JastAddJ.MethodAccess.decls_compute(MethodAccess.java:1094)
>         at soot.JastAddJ.MethodAccess.decls(MethodAccess.java:1086)
>         at soot.JastAddJ.MethodAccess.decl_compute(MethodAccess.java:1128)
>         at soot.JastAddJ.MethodAccess.decl(MethodAccess.java:1120)
>         at soot.JastAddJ.MethodAccess.nameCheck(MethodAccess.java:206)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1283)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
>         at soot.JastAddJ.CompilationUnit.errorCheck(CompilationUnit.java:178)
>         at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:67)
>         at soot.JavaClassSource.resolve(JavaClassSource.java:66)
>         at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
>         at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
>         at soot.SootResolver.bringToSignatures(SootResolver.java:292)
>         at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
>         at soot.SootResolver.resolveClass(SootResolver.java:141)
>         at soot.Scene.loadClass(Scene.java:1067)
>         at soot.Scene.loadClassAndSupport(Scene.java:1052)
>         at soot.Scene.loadNecessaryClass(Scene.java:1834)
>         at soot.Scene.loadNecessaryClasses(Scene.java:1846)
>         at soot.Main.run(Main.java:241)
>         at soot.Main.main(Main.java:141)
> Caused by: java.lang.NullPointerException
>         at soot.JastAddJ.BytecodeParser.parseThisClass(BytecodeParser.java:439)
>         at soot.JastAddJ.BytecodeParser.parseTypeDecl(BytecodeParser.java:423)
>         at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:331)
>         at soot.JastAddJ.BytecodeParser.read(BytecodeParser.java:27)
>         at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:87)
>         ... 73 more

**Comment by mbenz89** [comment]
Hi. Soot's Java frontend is heavily outdated. Please compile the code and use Soot to process the compiled code, thereafter.
