### ISSUE TITLE
Simplifying building of Soot from sources

### ISSUE THREAD

**Issue by saswatanand** [Sable/soot#135]
It would be great if building Soot from sources could be a made a bit simpler (e.g., just run one script) than what it is now. Currently, after checking out the three repos and copying the ant.settings.template files, one has to tweak the ant.settings before Soot builds successfully. To avoid the hassle, we could make minor changes to the ant.settings.template inside soot and jasmin as follows. The changes assume that three repos are cloned into three subdirectories "soot", "heros", and "jasmin".

I wonder if these changes would significantly affect other things (e.g., nightly builds).

Saswat

saswat@stamplabs:~/work/soot-repo/soot$ git diff ant.settings.template
diff --git a/ant.settings.template b/ant.settings.template
index 051366b..572cbc8 100644
--- a/ant.settings.template
+++ b/ant.settings.template
@@ -7,10 +7,10 @@ baksmali.jar=libs/baksmali-1.3.2.jar
 baksmali2.jar=libs/baksmali-2.0b5.jar
 
 ## Location of JastAdd classes jar file to link Soot against
-jastaddfrontend.loc=../JastAddExtensions/SootJastAddJ
+#jastaddfrontend.loc=../JastAddExtensions/SootJastAddJ
 
 ## Location of Jasmin classes jar file
-jasmin.jar=../libs/jasminclasses-custom.jar
+jasmin.jar=../jasmin/lib/jasminclasses-custom.jar
 
 heros.jar=../heros/heros-trunk.jar
 
@@ -31,4 +31,4 @@ javaapi.url=http://java.sun.com/j2se/1.6.0/docs/api/
 
 junit.jar=/home/user/ebodde/eclipse/plugins/org.junit_3.8.2/junit.jar
 
-javacup.jar=../libs/java_cup.jar
+javacup.jar=../jasmin/libs/java_cup.jar

saswat@stamplabs:~/work/soot-repo/jasmin$ git diff ant.settings.template
diff --git a/ant.settings.template b/ant.settings.template
index c90e953..ffddc75 100644
--- a/ant.settings.template
+++ b/ant.settings.template
@@ -1,9 +1,9 @@
 ## Location of Java Cup classes jar file to link Jasmin against
 # either classes dir or jar - note polyglot comes with cup-classes
-java_cup.jar=${user.home}/cup-classes/
+java_cup.jar=libs/java_cup.jar
 
 # Location in which to generate Jasmin release tarballs
 release.loc=lib
 
 # Version of Jasmin for tagging tarballs
-jasmin.version=2.2.1
+jasmin.version=custom

**Comment by StevenArzt** [comment]
We now have a script called "nightly" in the root folder that you can use to automatically download and build all required files. Our actual nightly build server does not use this script for various reasons (two of them being test case integration and artifact archival for the website), but for a single end-developer it should certainly be an improvement.
