### ISSUE TITLE
[couldn't find existing class] - soot.SootResolver$SootClassNotFoundException: couldn't find class

### ISSUE THREAD

**Issue by OnurOezcan** [Sable/soot#1355]
i use soot in my application. 
My application loads the artifacts of other applications and i want to scan over them.
This means that i can get to the class<?> objects and get all information (also location).

But I constantly get the error 

> soot.SootResolver$SootClassNotFoundException: could't find class: CLASSPATH.SEPERATED.WITH.POINTS

My use case:
I would like to create PlantUML graphs from CallGraph using soot, to keep the documentation of individual projects automatically up-to-date.

my code:

```
// String[] args from Main
        List<String> argsList = new ArrayList<String>(Arrays.asList(args));
        argsList.addAll(Arrays.asList(new String[]{
                "-w", "-main-class",MYCLASSFILE.getPackageName() + "." + MYCLASSFILE.getSimpleName(), // main-class
                MYCLASSFILE.getPackageName() + "." + MYCLASSFILE.getSimpleName(), // argument classes
                MYCLASSFILE.getSimpleName() //
        }));
```

the tutorial i used is from this YouTube:
https://www.youtube.com/watch?v=I6eAA7tmgsQ

can somebody help me pls?

**Comment by mbenz89** [comment]
You need to set Soot's process dir to point to the root folder (or jar) of the classfiles you want to analyze. This is the folder where the package structure of your project is located and would be "folder" in the following example:

folder/com/foo/bar/someclass.class

**Comment by OnurOezcan** [comment]
Hello,

thank you for the answer.
I followed your advice and tried different ways.
However, I am still getting an error:

java.lang.RuntimeException: Attempt to create RefType containing a / --> C:/codebase/mavenRepository/com/bla/bli/blubb/1.11.1/cheese-1.11.1.jar/com/bla/bli/blubb/cheese/service/someClass.class

my code:
  


  public static void analyze(Class<?> myClass, String[] args)
    {
        String classLocation = myClass.getProtectionDomain().getCodeSource().getLocation().toString().replace("file:/", "");
        String packageStructureOfClass = myClass.getPackageName() + "." + myClass.getSimpleName();
        String pathToClass = packageStructureOfClass.replace(".", "/") + ".class";

        List<String> argsList = new ArrayList<>(Arrays.asList(args));
        argsList.addAll(Arrays.asList(new String[]{
                "-w", "-main-class", classLocation, // main-class
                classLocation + "/" + pathToClass, // argument classes
                 myClass.getSimpleName() //
        }));

**Comment by OnurOezcan** [comment]
Okay, the path must have a \ and not /.
I'm sorry, for that misunderstanding.
i have now adjusted the path so that it looks like this:

`C:\codebase\mavenRepository\com\bla\bli\blubb\1.11.1\cheese-1.11.1.jar\com\bla\bli\blubb\cheese\service\someClass.class`

Now I get the exception again like at the beginning:

`soot.SootResolver$SootClassNotFoundException: couldn't find class: C:\codebase\mavenRepository\com\bla\bli\blubb\1.11.1\cheese-1.11.1.jar\com\bla\bli\blubb\cheese\service\someClass.class`

but if i navigate through my directory structure and also open the .jar file with 7zip, i find the .class file without any problems. that means that it does exist.

**Comment by linghuiluo** [comment]
use C:\codebase\mavenRepository\com\bla\bli\cheese\1.11.1\cheese-1.11.1.jar as class path

**Comment by OnurOezcan** [comment]
Hey Linghuiluo,

thank you very much for your answer.
I tried your advice but i still get that error.

more Context:

i'm calling soot in this way:
`soot.Main.main(myArgs);`

the String[] myArgs contains this value at the moment:

> {"-w", "main-class", "C:\codebase\mavenRepository\com\bla\bli\cheese\1.11.1\cheese-1.11.1.jar", "C:\codebase\mavenRepository\com\bla\bli\cheese\1.11.1\cheese-1.11.1.jar", "com\bla\bli\cheese\service\someClass.class"}

i really don't know, what i'm doing wrong

**Comment by mbenz89** [comment]
Your main class should be given as `com.bla.bli.cheese.service.someClass`. The jar has to be given to the `-process-dir` option not the main class option!

**Comment by linghuiluo** [comment]
yes as @mbenz89 said, try the following in your args for soot
-process-dir %targetJar% -pp -allow-phantom-refs -main-class %mainClassName%

**Comment by OnurOezcan** [comment]
Thank you very much.
that worked for me.

to close this issue, my Code:

```
        List<String> argsList = new ArrayList<>(Arrays.asList(args));
        argsList.addAll(Arrays.asList(new String[]{
                "-process-dir", classLocation, "-pp", "-allow-phantom-refs", "-main-class", packageStructure
        }));
```

classLocation contains the path to the JAR-File (ending with .jar)
packageStructure has to end with .class.
