### ISSUE TITLE
How to write code according to the command line

### ISSUE THREAD

**Issue by sscui** [Sable/soot#1358]
If I want to achieve the same effect of this command line in the program, how should my argslist be set
`java -cp soot-3.3.0-jar-with-dependencies.jar soot.Main -cp ./android.jar;./BaiduLBS_Android.jar com.baidu.location.LocationClient`
when I set parameters like this, I was always prompted that I could not find the class `com.baidu.location.LocationClient`, But in fact I have no problem running on the command line

![image](https://user-images.githubusercontent.com/22017601/82518931-0499ca80-9b53-11ea-936d-932cad92ddff.png)

![image](https://user-images.githubusercontent.com/22017601/82302793-a8b53180-99ec-11ea-9796-b287ca01e654.png)
I hope there can be a tutorial like a table where the command line corresponds to the code,

**Comment by sscui** [comment]
@elavoie I am so sorry to bother you, and I am a soot beginner, I also searched a lot of information about this issue, but it has no effect, I hope you can help me

**Comment by linghuiluo** [comment]
you should try to give absolute path to the directory of the class.  Where is this class com.baidu.location.LocationClient?

**Comment by sscui** [comment]
@linghuiluo In the jar package BaiduLBS_Android.jar. I can find this class correctly by running this on the command line but failing in the program. I can't understand it.

**Comment by sscui** [comment]
However, the class in rt.jar like java.util.Set can run correctly. Through the command line, I'm sure the path com.baidu.location.LocationClient is right

![image](https://user-images.githubusercontent.com/22017601/82563570-e6ab8480-9ba9-11ea-81f3-17bab50919b7.png)

**Comment by linghuiluo** [comment]
maybe some library classes used by your jar are not on the class path. 
Try to add the option -allow-phantom-refs for allowing unresolved classes

**Comment by sscui** [comment]
Oh, great. Then I won’t get an error, but I can’t get any information about the class either. I can only get an empty class however this is not the result I want.
![image](https://user-images.githubusercontent.com/22017601/82657585-2cbf2180-9c58-11ea-9c47-b9229ab79664.png)

**Comment by linghuiluo** [comment]
Probably this class is not in the jar. Did you check the jar file if it contains the .class file?

**Comment by sscui** [comment]
I had checked it, and I'm sure the class is in the jar. Fortunately, when I delete the code `Scene.v().loadClassAndSupport("com.lang.Object");` , My program can run rightly. Why the code make the program wrong?

**Comment by mbenz89** [comment]
Because `com.lang.Object` is not a valid class in the jdk. The class you are actually trying to resolve is probably rather `java.lang.Object`.
