### ISSUE TITLE
Automated regression test suite for dexpler & toDex.

### ISSUE THREAD

**Issue by KJamrozik** [Sable/soot#147]
If I count correctly, in total I have reported at least 11 bugs related to the processing of dalvik bytecode. All of them have been fixed (@StevenArzt @Alexandre-Bartel, you are my heroes), but new (regression) bugs seem to be constantly popping out. I think having a proper test suite would significantly reduce the time spent diagnosing the bugs, both for me and for the person who fixes it. The test suite will enable early bug discovery and easy reproduction.

I am planning to write such test suite in incoming weeks and submit a pull request. Just letting you know if you wanted to do something similar.

Related issue for general purpose test suite: #61

**Comment by StevenArzt** [comment]
We already have an internal test suite by now that runs on our nightly build server. Since no further comments have been made to this thread for quite a while, I consider this done for now.
