### ISSUE TITLE
Develop transformer that gets rid of indy calls for lambda capture

### ISSUE THREAD

**Issue by ericbodden** [Sable/soot#226]
Java 8 introduces invokedynamic (indy) calls to capture lambda expressions. Those calls can confuse Soot's call graph construction. This document gives more information on how the calls are created:
http://cr.openjdk.java.net/~briangoetz/lambda/lambda-translation.html

According to Brian Götz it should be entirely possible to get rid of those invokedynamic-calls introduced by lambda captures. In fact, J2ME does exactly that, replacing them by invokevirtual/static calls. One has to analyze how the lamba metafactory is called, extracting information about the method handles in place. Then, indy calls should be replaced by appropriate direct invokevirtual/static calls.

**Comment by ddiepo-pjr** [comment]
Is this now OBE by #1078 ?

**Comment by mbenz89** [comment]
Yes, thanks for the note!
