### ISSUE TITLE
Uncaught exceptions after instrumenting with soot

### ISSUE THREAD

**Issue by juliarubin** [Sable/soot#236]
When I run an apk instrumented by soot, it seems that exceptions that were caught in the original version are not caught any more and cause the instrumented application to fail with a FATAL_ERROR. My instrumentation does nothing and I can reproduce this behavior for more than one application, so I assume that is likely to be a problem with soot. 

For example, the logcat file of the com.facebook.orca apk (downloaded from GooglePlay a few days ago) is below. The application recovers from a failed attempt to load a library and proceeds. That is not the case for the instrumented version which fails permanently and exits -- see the log below as well. 

A somewhat smaller example is ly.secret.android.apk. Logs are below as well. 

Would be great if you could take a look,
Thanks,
Julia

------------------------ Original facebook ------------------------

I/ActivityManager( 1289): Start proc com.facebook.orca for activity com.facebook.orca/.auth.StartScreenActivity: pid=2113 uid=10057 gids={50057, 3003, 1028, 1015}
D/ACRA    ( 2113): ACRA is enabled for com.facebook.orca, intializing...
D/ACRA    ( 2113): Looking for error files in /data/data/com.facebook.orca/app_acra-reports
D/ACRA    ( 2113): Looking for error files in /data/data/com.facebook.orca/app_minidumps
W/SoLoader( 2113): Failed to load library!
W/SoLoader( 2113): java.lang.UnsatisfiedLinkError: Couldn't load fb_stl_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.facebook.orca-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.facebook.orca-1, /vendor/lib, /system/lib]]]: findLibrary returned null
W/SoLoader( 2113): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
W/SoLoader( 2113): 	at java.lang.System.loadLibrary(System.java:526)
W/SoLoader( 2113): 	at com.facebook.s.b.a(SoLoader.java:135)
W/SoLoader( 2113): 	at com.facebook.breakpad.BreakpadManager.b(BreakpadManager.java:62)
W/SoLoader( 2113): 	at com.facebook.messenger.app.MessengerApplication.b(MessengerApplication.java:46)
W/SoLoader( 2113): 	at com.facebook.base.a.h.attachBaseContext(DelegatingApplication.java:58)
W/SoLoader( 2113): 	at android.app.Application.attach(Application.java:181)
W/SoLoader( 2113): 	at android.app.Instrumentation.newApplication(Instrumentation.java:991)
W/SoLoader( 2113): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
W/SoLoader( 2113): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
W/SoLoader( 2113): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
W/SoLoader( 2113): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
W/SoLoader( 2113): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
W/SoLoader( 2113): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/SoLoader( 2113): 	at android.os.Looper.loop(Looper.java:136)
W/SoLoader( 2113): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
W/SoLoader( 2113): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/SoLoader( 2113): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/SoLoader( 2113): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/SoLoader( 2113): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/SoLoader( 2113): 	at dalvik.system.NativeStart.main(Native Method)
E/BreakpadManager( 2113): Breakpad init failed: 
E/BreakpadManager( 2113): java.lang.UnsatisfiedLinkError: Application context is not set - will not try alternative load
E/BreakpadManager( 2113): 	at com.facebook.s.b.a(SoLoader.java:200)
E/BreakpadManager( 2113): 	at com.facebook.s.b.a(SoLoader.java:155)
E/BreakpadManager( 2113): 	at com.facebook.breakpad.BreakpadManager.b(BreakpadManager.java:62)
E/BreakpadManager( 2113): 	at com.facebook.messenger.app.MessengerApplication.b(MessengerApplication.java:46)
E/BreakpadManager( 2113): 	at com.facebook.base.a.h.attachBaseContext(DelegatingApplication.java:58)
E/BreakpadManager( 2113): 	at android.app.Application.attach(Application.java:181)
E/BreakpadManager( 2113): 	at android.app.Instrumentation.newApplication(Instrumentation.java:991)
E/BreakpadManager( 2113): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
E/BreakpadManager( 2113): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
E/BreakpadManager( 2113): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
E/BreakpadManager( 2113): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/BreakpadManager( 2113): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/BreakpadManager( 2113): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/BreakpadManager( 2113): 	at android.os.Looper.loop(Looper.java:136)
E/BreakpadManager( 2113): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/BreakpadManager( 2113): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/BreakpadManager( 2113): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/BreakpadManager( 2113): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/BreakpadManager( 2113): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/BreakpadManager( 2113): 	at dalvik.system.NativeStart.main(Native Method)
E/BreakpadManager( 2113): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load fb_stl_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.facebook.orca-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.facebook.orca-1, /vendor/lib, /system/lib]]]: findLibrary returned null
E/BreakpadManager( 2113): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/BreakpadManager( 2113): 	at java.lang.System.loadLibrary(System.java:526)
E/BreakpadManager( 2113): 	at com.facebook.s.b.a(SoLoader.java:135)
E/BreakpadManager( 2113): 	... 18 more
W/OrcaGuiceModule( 2113): Sig: ijxLJi1yGs1JpL-X1SExmchvork
V/DexLibLoader( 2113): Preparing secondary program dexes from null
V/DexLibLoader( 2113): Loaded 1 raw lines of metadata.
V/DexLibLoader( 2113): Secondary program dex metadata: secondary-1.dex.jar 22d13e367f1441a5fe39e49f0f610ea91ac3ff41 secondary.dex01.Canary
V/DexLibLoader( 2113): Preparing to extract secondary-1.dex.jar to /data/data/com.facebook.orca/app_secondary_program_dex/program-22d13e367f1441a5fe39e49f0f610ea91ac3ff4178f99528.dex.jar
V/DexLibLoader( 2113): About to extract secondary-program-dex-jars/secondary-1.dex.jar to /data/data/com.facebook.orca/app_secondary_program_dex/program-22d13e367f1441a5fe39e49f0f610ea91ac3ff4178f99528.dex.jar
V/DexLibLoader( 2113): Finished extracting.

------------------------ Instrumented facebook ------------------------

I/ActivityManager( 1289): Start proc com.facebook.orca for activity com.facebook.orca/.auth.StartScreenActivity: pid=2668 uid=10059 gids={50059, 3003, 1028, 1015}
D/ACRA    ( 2668): ACRA is enabled for com.facebook.orca, intializing...
D/ACRA    ( 2668): Looking for error files in /data/data/com.facebook.orca/app_acra-reports
D/ACRA    ( 2668): Looking for error files in /data/data/com.facebook.orca/app_minidumps
W/SoLoader( 2668): Failed to load library!
W/SoLoader( 2668): java.lang.UnsatisfiedLinkError: Couldn't load fb_stl_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.facebook.orca-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.facebook.orca-1, /vendor/lib, /system/lib]]]: findLibrary returned null
W/SoLoader( 2668): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
W/SoLoader( 2668): 	at java.lang.System.loadLibrary(System.java:526)
W/SoLoader( 2668): 	at com.facebook.s.b.a(SoLoader.java:135)
W/SoLoader( 2668): 	at com.facebook.breakpad.BreakpadManager.b(BreakpadManager.java:59)
W/SoLoader( 2668): 	at com.facebook.messenger.app.MessengerApplication.b(MessengerApplication.java:46)
W/SoLoader( 2668): 	at com.facebook.base.a.h.attachBaseContext(DelegatingApplication.java:58)
W/SoLoader( 2668): 	at android.app.Application.attach(Application.java:181)
W/SoLoader( 2668): 	at android.app.Instrumentation.newApplication(Instrumentation.java:991)
W/SoLoader( 2668): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
W/SoLoader( 2668): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
W/SoLoader( 2668): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
W/SoLoader( 2668): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
W/SoLoader( 2668): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
W/SoLoader( 2668): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/SoLoader( 2668): 	at android.os.Looper.loop(Looper.java:136)
W/SoLoader( 2668): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
W/SoLoader( 2668): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/SoLoader( 2668): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/SoLoader( 2668): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/SoLoader( 2668): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/SoLoader( 2668): 	at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime( 2668): Shutting down VM
W/dalvikvm( 2668): threadid=1: thread exiting with uncaught exception (group=0xb3ca8b20)
E/ACRA    ( 2668): ACRA caught a UnsatisfiedLinkError exception for com.facebook.orca. Building report.
E/ACRA    ( 2668): Handling exception for crash
E/ACRA    ( 2668): java.lang.UnsatisfiedLinkError: Application context is not set - will not try alternative load
E/ACRA    ( 2668): 	at com.facebook.s.b.a(SoLoader.java:200)
E/ACRA    ( 2668): 	at com.facebook.s.b.a(SoLoader.java:154)
E/ACRA    ( 2668): 	at com.facebook.breakpad.BreakpadManager.b(BreakpadManager.java:59)
E/ACRA    ( 2668): 	at com.facebook.messenger.app.MessengerApplication.b(MessengerApplication.java:46)
E/ACRA    ( 2668): 	at com.facebook.base.a.h.attachBaseContext(DelegatingApplication.java:58)
E/ACRA    ( 2668): 	at android.app.Application.attach(Application.java:181)
E/ACRA    ( 2668): 	at android.app.Instrumentation.newApplication(Instrumentation.java:991)
E/ACRA    ( 2668): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
E/ACRA    ( 2668): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
E/ACRA    ( 2668): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
E/ACRA    ( 2668): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/ACRA    ( 2668): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/ACRA    ( 2668): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ACRA    ( 2668): 	at android.os.Looper.loop(Looper.java:136)
E/ACRA    ( 2668): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/ACRA    ( 2668): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/ACRA    ( 2668): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/ACRA    ( 2668): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/ACRA    ( 2668): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/ACRA    ( 2668): 	at dalvik.system.NativeStart.main(Native Method)
E/ACRA    ( 2668): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load fb_stl_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.facebook.orca-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.facebook.orca-1, /vendor/lib, /system/lib]]]: findLibrary returned null
E/ACRA    ( 2668): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/ACRA    ( 2668): 	at java.lang.System.loadLibrary(System.java:526)
E/ACRA    ( 2668): 	at com.facebook.s.b.a(SoLoader.java:135)
E/ACRA    ( 2668): 	... 18 more
D/ACRA    ( 2668): Generating report file for crash
D/dalvikvm( 2668): GC_FOR_ALLOC freed 331K, 12% free 2825K/3208K, paused 23ms, total 24ms
V/ACRA    ( 2668): About to start ReportSenderWorker from #handleException
D/ACRA    ( 2668): #checkAndSendReports - start
D/ACRA    ( 2668): Looking for error files in /data/data/com.facebook.orca/app_acra-reports
D/ACRA    ( 2668): Loading file 1408135098821-UnsatisfiedLinkError-3587183.stacktrace
I/ACRA    ( 2668): Sending file 1408135098821-UnsatisfiedLinkError-3587183.stacktrace
D/ACRA    ( 2668): Connect to https://www.facebook.com/mobile/orca_android_crash_logs/
D/dalvikvm( 2668): GC_FOR_ALLOC freed 453K, 15% free 2883K/3388K, paused 43ms, total 43ms
D/ACRA    ( 2668): #checkAndSendReports - finish
E/AndroidRuntime( 2668): FATAL EXCEPTION: main
E/AndroidRuntime( 2668): Process: com.facebook.orca, PID: 2668
E/AndroidRuntime( 2668): java.lang.UnsatisfiedLinkError: Application context is not set - will not try alternative load
E/AndroidRuntime( 2668): 	at com.facebook.s.b.a(SoLoader.java:200)
E/AndroidRuntime( 2668): 	at com.facebook.s.b.a(SoLoader.java:154)
E/AndroidRuntime( 2668): 	at com.facebook.breakpad.BreakpadManager.b(BreakpadManager.java:59)
E/AndroidRuntime( 2668): 	at com.facebook.messenger.app.MessengerApplication.b(MessengerApplication.java:46)
E/AndroidRuntime( 2668): 	at com.facebook.base.a.h.attachBaseContext(DelegatingApplication.java:58)
E/AndroidRuntime( 2668): 	at android.app.Application.attach(Application.java:181)
E/AndroidRuntime( 2668): 	at android.app.Instrumentation.newApplication(Instrumentation.java:991)
E/AndroidRuntime( 2668): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
E/AndroidRuntime( 2668): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
E/AndroidRuntime( 2668): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
E/AndroidRuntime( 2668): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 2668): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 2668): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2668): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2668): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 2668): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2668): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2668): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 2668): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 2668): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2668): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load fb_stl_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.facebook.orca-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.facebook.orca-1, /vendor/lib, /system/lib]]]: findLibrary returned null
E/AndroidRuntime( 2668): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime( 2668): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime( 2668): 	at com.facebook.s.b.a(SoLoader.java:135)
E/AndroidRuntime( 2668): 	... 18 more
W/ActivityManager( 1289):   Force finishing activity com.facebook.orca/.auth.StartScreenActivity

------------------------ Original secret ------------------------
E/ActivityThread( 3957): Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
E/ActivityThread( 3957): Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
E/BluetoothAdapter( 3957): Bluetooth binder is null
V/WebViewChromium( 3957): Binding Chromium to the background looper Looper (main, tid 1) {b3f9ad00}
I/chromium( 3957): [INFO:library_loader_hooks.cc(112)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserProcessMain( 3957): Initializing chromium process, renderers=0
W/System.err( 3957): java.io.FileNotFoundException: /data/data/ly.secret.android/files/secret_posts3: open failed: ENOENT (No such file or directory)
W/System.err( 3957): 	at libcore.io.IoBridge.open(IoBridge.java:409)
W/System.err( 3957): 	at java.io.FileInputStream.<init>(FileInputStream.java:78)
W/System.err( 3957): 	at android.app.ContextImpl.openFileInput(ContextImpl.java:780)
W/System.err( 3957): 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:179)
W/System.err( 3957): 	at ly.secret.android.utils.DiskPersistenceUtil$LoadSecretsFromDisk.a(DiskPersistenceUtil.java:113)
W/System.err( 3957): 	at ly.secret.android.utils.DiskPersistenceUtil$LoadSecretsFromDisk.doInBackground(DiskPersistenceUtil.java:98)
W/System.err( 3957): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err( 3957): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err( 3957): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 3957): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 3957): 	at java.lang.Thread.run(Thread.java:841)
W/System.err( 3957): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err( 3957): 	at libcore.io.Posix.open(Native Method)
D/        ( 3957): HostConnection::get() New Host Connection established 0xb997d800, tid 3957
W/chromium( 3957): [WARNING:proxy_service.cc(888)] PAC support disabled because there is no system implementation
D/dalvikvm( 3957): GC_FOR_ALLOC freed 1553K, 18% free 7436K/9052K, paused 150ms, total 151ms
W/System.err( 3957): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err( 3957): 	at libcore.io.IoBridge.open(IoBridge.java:393)
W/System.err( 3957): 	... 10 more
I/Choreographer( 3957): Skipped 59 frames!  The application may be doing too much work on its main thread.
W/EGL_emulation( 3957): eglSurfaceAttrib not implemented
D/OpenGLRenderer( 3957): Enabling debug mode 0
I/ActivityManager( 1288): Displayed ly.secret.android/.ui.splash.SplashActivity: +12s70ms (total +13s718ms)

------------------------ Instrumented secret ------------------------
E/ActivityThread( 2533): Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
E/ActivityThread( 2533): Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
W/dalvikvm( 2533): threadid=26: thread exiting with uncaught exception (group=0xb3cbab20)
E/AndroidRuntime( 2533): FATAL EXCEPTION: Timer-0
E/AndroidRuntime( 2533): Process: ly.secret.android, PID: 2533
E/AndroidRuntime( 2533): java.io.FileNotFoundException: /data/data/ly.secret.android/files/AppEventsLogger.persistedevents: open failed: ENOENT (No such file or directory)
E/AndroidRuntime( 2533): 	at libcore.io.IoBridge.open(IoBridge.java:409)
E/AndroidRuntime( 2533): 	at java.io.FileInputStream.<init>(FileInputStream.java:78)
E/AndroidRuntime( 2533): 	at android.app.ContextImpl.openFileInput(ContextImpl.java:780)
E/AndroidRuntime( 2533): 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:179)
E/AndroidRuntime( 2533): 	at com.facebook.AppEventsLogger$PersistedEvents.readAndClearStore(AppEventsLogger.java:1276)
E/AndroidRuntime( 2533): 	at com.facebook.AppEventsLogger$PersistedEvents.readAndClearStore(AppEventsLogger.java:1218)
E/AndroidRuntime( 2533): 	at com.facebook.AppEventsLogger.accumulatePersistedEvents(AppEventsLogger.java:900)
E/AndroidRuntime( 2533): 	at com.facebook.AppEventsLogger.flushAndWait(AppEventsLogger.java:744)
E/AndroidRuntime( 2533): 	at com.facebook.AppEventsLogger.access$100(AppEventsLogger.java:106)
E/AndroidRuntime( 2533): 	at com.facebook.AppEventsLogger$2.run(AppEventsLogger.java:605)
E/AndroidRuntime( 2533): 	at java.util.Timer$TimerImpl.run(Timer.java:284)
E/AndroidRuntime( 2533): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
E/AndroidRuntime( 2533): 	at libcore.io.Posix.open(Native Method)
E/AndroidRuntime( 2533): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
E/AndroidRuntime( 2533): 	at libcore.io.IoBridge.open(IoBridge.java:393)
E/AndroidRuntime( 2533): 	... 10 more
W/ActivityManager( 1288):   Force finishing activity ly.secret.android/.ui.splash.SplashActivity

**Comment by Alexandre-Bartel** [comment]
I cannot reproduce the fatal exceptions with Soot e871fbe6152f23f88cebc9a6220cb1dfa8df24b9. None of the two applications (processed by Soot) are crashing when started on an emulator.
