### ISSUE TITLE
Getting java.lang.RuntimeException: not found: anp

### ISSUE THREAD

**Issue by juliarubin** [Sable/soot#240]
I am getting the exception below when running an empty soot transformation on the Battery Doctor application (com.ijinshan.kbatterydoctor_en.apk) downloaded from GooglePlay. The decompiled code of the problematic RecmmmendUniversalActivity class is also attached. 

Am I doing anything wrong?
Thanks in advance for looking into that!
Julia

------------------------------------------------------
Transforming com.ijinshan.kbatterydoctor.recommendapps.RecmmmendUniversalActivity... 
java.lang.RuntimeException: not found: anp
	at soot.toDex.PrimitiveType.getByName(PrimitiveType.java:24)
	at soot.toDex.ExprVisitor.castPrimitive(ExprVisitor.java:582)
	at soot.toDex.ExprVisitor.caseCastExpr(ExprVisitor.java:543)
	at soot.jimple.internal.AbstractCastExpr.apply(AbstractCastExpr.java:134)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:294)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:974)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:900)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:797)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:485)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1103)
	at soot.PackManager.writeClass(PackManager.java:983)
	at soot.PackManager.writeOutput(PackManager.java:592)
	at soot.PackManager.writeOutput(PackManager.java:500)
	at soot.Main.run(Main.java:206)
	at soot.Main.main(Main.java:147)

------------------------------------------------------

package com.ijinshan.kbatterydoctor.recommendapps;

import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;
import android.text.Html;
import android.text.TextUtils;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import bbv;
import bhu;
import bhw;
import bkj;
import bkl;

public class RecmmmendUniversalActivity extends Activity
  implements View.OnClickListener
{
  private static final boolean a;
  private Button b;
  private ImageView c;
  private TextView d;
  private TextView e;
  private Context f;
  private int g = 0;
  private int h = 1;
  private final BroadcastReceiver i = new bkj(this, (byte)0);

  static
  {
    if (bbv.a);
    for (boolean bool = true; ; bool = false)
    {
      a = bool;
      return;
    }
  }

  public void onClick(View paramView)
  {
    if (paramView == this.b)
    {
      bhu.a(this.f, "recommend_activity_confirm_click", bhw.b(String.valueOf(this.g)), "1");
      if (1 != this.h);
    }
    while (paramView != this.c)
    {
      bkl.a(this.f, this.g);
      while (true)
      {
        finish();
        return;
        if (2 == this.h)
          bkl.b(this.f, this.g);
      }
    }
    bhu.a(this.f, "recommend_activity_close_click", bhw.b(String.valueOf(this.g)), "1");
    if (1 == this.h)
      bkl.a("app_uninst_rcmd_cm_close_time", "app_uninst_rcmd _cm_close_date");
    while (true)
    {
      finish();
      return;
      if (2 == this.h)
        bkl.a("app_uninst_rcmd_lb_close_time", "app_uninst_rcmd _lb_close_date");
    }
  }

  protected void onCreate(Bundle paramBundle)
  {
    super.onCreate(paramBundle);
    this.f = getApplicationContext();
    Intent localIntent = getIntent();
    String str3;
    String str2;
    String str1;
    if (localIntent != null)
    {
      this.g = localIntent.getIntExtra("src", 0);
      String str4 = localIntent.getStringExtra("title");
      String str5 = localIntent.getStringExtra("text");
      String str6 = localIntent.getStringExtra("btn");
      this.h = localIntent.getIntExtra("rcmdtype", 1);
      str3 = str4;
      str2 = str5;
      str1 = str6;
    }
    while (true)
    {
      setContentView(2130903044);
      this.b = ((Button)findViewById(2131361922));
      this.b.setOnClickListener(this);
      if (!TextUtils.isEmpty(str1))
        this.b.setText(Html.fromHtml(str1));
      this.c = ((ImageView)findViewById(2131361923));
      this.c.setOnClickListener(this);
      this.d = ((TextView)findViewById(2131361918));
      if (!TextUtils.isEmpty(str3))
        this.d.setText(str3);
      this.e = ((TextView)findViewById(2131361920));
      if (!TextUtils.isEmpty(str2))
        this.e.setText(Html.fromHtml(str2));
      bhu.a(this.f, "recommend_activity_show", bhw.b(String.valueOf(this.g)), "1");
      return;
      str1 = null;
      str2 = null;
      str3 = null;
    }
  }

  protected void onDestroy()
  {
    super.onDestroy();
  }

  public boolean onKeyDown(int paramInt, KeyEvent paramKeyEvent)
  {
    if (paramInt == 4)
    {
      bhu.a(this.f, "recommend_activity_return_click", bhw.b(String.valueOf(this.g)), "1");
      finish();
    }
    return super.onKeyDown(paramInt, paramKeyEvent);
  }

  protected void onStart()
  {
    IntentFilter localIntentFilter = new IntentFilter("android.intent.action.CLOSE_SYSTEM_DIALOGS");
    registerReceiver(this.i, localIntentFilter);
    super.onStart();
  }

  protected void onStop()
  {
    unregisterReceiver(this.i);
    super.onStop();
  }
}

**Comment by Alexandre-Bartel** [comment]
I cannot reproduce this with the latest version of Soot db8e4fe4061f14b86e7d68b10e0ac83176b65612.
