### ISSUE TITLE
A recursive call appears after the instrumenting with soot and causes a StackOverflowError

### ISSUE THREAD

**Issue by juliarubin** [Sable/soot#246]
An empty transformation on com.torch.lampe.flashlight.apk from GooglePlay (https://drive.google.com/file/d/0B0zZkQlHQEv9WWhqcV9VcG45cWc/edit?usp=sharing) results in an apk that recursively calls java.lang.Class.getCanonicalName() and eventually fails with the StackOverflowError error. This does not happen in the original application. The code line that causes the problem and the log file are below.

The same problem seems to occur in the instrumented com.mobirix.playmaze app (https://drive.google.com/file/d/0B0zZkQlHQEv9b3o0NGd3YVhfTlE/edit?usp=sharing) and 
me.scan.android.client (https://drive.google.com/file/d/0B0zZkQlHQEv9ZEJsSGhtaUl1WEE/edit?usp=sharing).

Thank you in advance for looking into that and please let me know if I am doing anything wrong!
Julia

----------------------------------------------

private static final String TAG = AppEventsLogger.class.getCanonicalName();

W/dalvikvm( 1697): Exception Ljava/lang/StackOverflowError; thrown while initializing Lcom/facebook/AppEventsLogger;
D/AndroidRuntime( 1697): Shutting down VM
W/dalvikvm( 1697): threadid=1: thread exiting with uncaught exception (group=0xb4a57ba8)
W/System.err( 1697): java.lang.StackOverflowError
W/System.err( 1697): 	at java.lang.Class.getCanonicalName(Class.java:352)
W/System.err( 1697): 	at java.lang.Class.getCanonicalName(Class.java:369)
W/System.err( 1697): 	at java.lang.Class.getCanonicalName(Class.java:369) 
W/System.err( 1697): 	at java.lang.Class.getCanonicalName(Class.java:369)

			( ... a lot of these...)

W/System.err( 1697): 	at java.lang.Class.getCanonicalName(Class.java:369)
W/System.err( 1697): 	at java.lang.Class.getCanonicalName(Class.java:369)
W/System.err( 1697): 	at java.lang.Class.getCanonicalName(Class.java:369)
W/System.err( 1697): 	at com.facebook.AppEventsLogger.<clinit>(AppEventsLogger.java:154)
W/System.err( 1697): 	at com.gpit.android.tools.flashlight.BlackTheme5.onResume(BlackTheme5.java:155)
W/System.err( 1697): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
W/System.err( 1697): 	at android.app.Activity.performResume(Activity.java:5310)
W/System.err( 1697): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2778)
W/System.err( 1697): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2817)
W/System.err( 1697): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
W/System.err( 1697): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
W/System.err( 1697): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
W/System.err( 1697): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 1697): 	at android.os.Looper.loop(Looper.java:136)
W/System.err( 1697): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err( 1697): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 1697): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 1697): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err( 1697): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err( 1697): 	at dalvik.system.NativeStart.main(Native Method)
W/FlurryAgent( 1697): Error logged: uncaught
W/FlurryAgent( 1697): End session with context: com.gpit.android.tools.flashlight.BlackTheme5@b4d216c8 count:0

**Comment by Alexandre-Bartel** [comment]
Flashlight and Scan are working fine with Soot e871fbe6152f23f88cebc9a6220cb1dfa8df24b9.
For some reason (OpenGL?) I could not test Playmaze on an emulator. Feel free to reopen the issue if it still does not work for this app.
