### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by ericbodden** [Sable/soot#248]
For the upcoming release we should clean up all dependencies:

For each of soot, heros and jasmin, make sure that all dependencies are _only_ in the respective `libs`directory. Also make sure that there are no duplicate dependencies. For instance, Soot does not need copies of dependencies that are already packaged with heros.

Clean up the .classpath settings for Eclipse and the ant targets accordingly.
Clean up the ant.settings.template files accordingly.

**Comment by anddann** [comment]
With the migration to the maven build system, we cleaned up all dependencies and published them to maven central.
