### ISSUE TITLE
Soot inserts strange cast within Android APK

### ISSUE THREAD

**Issue by MarcMil** [Sable/soot#271]
Hi there,

In the apk
https://www.dropbox.com/s/25wgl1qt2cso9co/Imported.apk?dl=0

net.osmand.osm.edit.Way
Method getLatLonBBox

The Jimplecode:

      public net.osmand.data.QuadRect getLatLonBBox()
      {
     net.osmand.data.QuadRect r5;
    
      …
      r5 = new net.osmand.data.QuadRect;
      $f0 = (float) r5;
      specialinvoke r5.<net.osmand.data.QuadRect: void <init>()>();
      $d0 = virtualinvoke $r4.<net.osmand.osm.edit.Node: double getLongitude()>();
      …
       }

gets created, involving a strange cast from an object reference to float.

Can be seen via
java -jar soot.jar -process-dir Imported.apk -keep-line-number  --src-prec apk -output-format j  --force-android-jar  sdk/platforms/android-19/android.jar --allow-phantom-refs

The corresponding smali code looks correct to me:

	    .line 155
	    new-instance v2, Lnet/osmand/data/QuadRect;

	    .end local v2           #qr:Lnet/osmand/data/QuadRect;
	    invoke-direct {v2}, Lnet/osmand/data/QuadRect;-><init>()V

	    .line 156
	    .restart local v2       #qr:Lnet/osmand/data/QuadRect;
	    invoke-virtual {v1}, Lnet/osmand/osm/edit/Node;->getLongitude()D

	    move-result-wide v3

	    double-to-float v3, v3

	    float-to-double v3, v3

	    iput-wide v3, v2, Lnet/osmand/data/QuadRect;->left:D

Thanks,
 Marc

**Comment by Alexandre-Bartel** [comment]
I cannot reproduce this with the latest Soot e329db5db5265cd5f3cb4b62d54be95684dde5da.
Could you confirm that the issue has been fixed?
