### ISSUE TITLE
About losing line number when instrument Android application 

### ISSUE THREAD

**Issue by yehjames** [Sable/soot#283]
I have used AndroidInstrument.java(https://gist.github.com/yehjames/b5cf1bc58e3d6549caf8) to instrument Android app in order to insert System.out.println(Thread.currentThread().getStackTrace()[2] ) at every statement.In this example it used tomdroid app.But I found there is some line number would lose. For example this is  a part of our logcat output.

I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.getView(NoteListCursorAdapter.java:110)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.getView(NoteListCursorAdapter.java:112)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.getView(NoteListCursorAdapter.java:112)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.getView(NoteListCursorAdapter.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.bindView(NoteListCursorAdapter.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java:129)
I/System.out(28880): org.tomdroid.util.Time.<init>(Time.java)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java:129)
I/System.out(28880): org.tomdroid.util.NoteListCursorAdapter.populateFields(NoteListCursorAdapter.java:129)
I/System.out(28880): org.tomdroid.util.Time.parseTomboy(Time.java)
I/System.out(28880): org.tomdroid.util.Time.parseTomboy(Time.java:121)
I/System.out(28880): org.tomdroid.util.Time.parseTomboy(Time.java:121)
I/System.out(28880): org.tomdroid.util.Time.parseTomboy(Time.java:122)
I/System.out(28880): org.tomdroid.util.Time.parseTomboy(Time.java:124)
I/System.out(28880): org.tomdroid.util.Time.parseTomboy(Time.java:124)
I/System.out(28880): org.tomdroid.util.Time.parseTomboy(Time.java:124)
I/System.out(28880): org.tomdroid.util.Time.parseTomboy(Time.java:124)

So I used a disassembler tool Dedexer (http://dedexer.sourceforge.net/) to transform apk to assembly-like format ,and I found some line number information in method would lose.

I ran this command : java -Xmx2000m -cp .:./soot-trunk.jar AndroidInstrument -allow-phantom-refs -android-jars /home/user/Downloads/android-platforms-master -process-dir /home/user/Downloads/SUT/tomdroid-0.7.5.apk

Take NoteListCursorAdapter.populateFields as an example

Before instrument
https://gist.github.com/yehjames/18bff2d0c0302b0f8340
After instrument
https://gist.github.com/yehjames/dbd79963b59872df7c96

we can found that some line number tag would lose.For example you can search: .line 120

**Comment by ericbodden** [comment]
@yehjames I think this should work now. If not, please reopen.
