### ISSUE TITLE
where is the online Soot API documentation? 

### ISSUE THREAD

**Issue by tingsu** [Sable/soot#315]
Hi, the Soot world. I found the developers have improved soot webpages recently, and i could not find the online soot API doc anymore.... Where can i visit that API doc?

**Comment by tingsu** [comment]
Thanks, a browseable API document is really convenient and helpful for our new learners to Soot.

**Comment by StevenArzt** [comment]
@ericbodden Here it is: https://ssebuild.cased.de/nightly/soot/javadoc/

**Comment by windflyer** [comment]
https://ssebuild.cased.de/nightly/soot/javadoc/ is unreachable.

**Comment by mbenz89** [comment]
The documentation has moved to http://soot-build.cs.uni-paderborn.de/doc/soot/ 

We might have missed redirecting some links. Can you give me a hint on where you found the stated address?

**Comment by windflyer** [comment]
In this thread: 

StevenArzt commented on Jan 4, 2015
@ericbodden Here it is: https://ssebuild.cased.de/nightly/soot/javadoc/

**Comment by peey** [comment]
None of the above links work anymore but the link specified on the wiki does : https://github.com/Sable/soot/wiki/Options-and-JavaDoc
