### ISSUE TITLE
Bad commit | Broken repository

### ISSUE THREAD

**Issue by vitaliiavdiienko** [Sable/soot#319]
Hi,

this code in the commit e524d81974a533aa9bba796eb0ae47a64ae11604 can not be compiled!
For example, the code after throw new IllegalStateException(); is unreachable! Thus, soot repo is broken...

System.exit(-1);
throw new IllegalStateException();
usedAsObject = true;
if (usedAsObject)
 		doBreak = true;

Best Regards,
Vitalii

**Comment by ericbodden** [comment]
Thanks, we should have checked better. I have reverted for now.
