### ISSUE TITLE
missing "public" modifier in AbstractOpStmt.java

### ISSUE THREAD

**Issue by pw4ever** [Sable/soot#329]
This line (https://github.com/Sable/soot/blob/develop/src/soot/jimple/internal/AbstractOpStmt.java#L10) misses a "public" modifier, which throw

java.lang.IllegalArgumentException: Can't call public method of non-public class: public final soot.Value soot.jimple.internal.AbstractOpStmt.getOp()

at run time.

**Comment by ericbodden** [comment]
This is weird. I have never seen this problem before.

**Comment by StevenArzt** [comment]
Can you give an example on how to reproduce the issue? How do you actually get such an exception at runtime? I have never seen such a problem either and various classes inside Soot itself as well as inside FlowDroid use "getOp()" on various descendants of AbstractOpStmt.

**Comment by pw4ever** [comment]
I do not have a self-contained small example at hand. I ran into this issue when using "StmtSwitch" in the "caseReturnStmt" in my code (shown in this line: https://github.com/pw4ever/tbnl-apk/blob/gh-pages/src/tbnl_apk/apk/dex/soot/simulator.clj#L488)

What suggests to me that "public" is necessary is that other soot.jimple.internal.Abstract*Stmt classes have "public" declared in them. Besides, the  Exception message suggests: Why having a public method in a non-public class?
