### ISSUE TITLE
Is points-to analysis still maintained and supported?

### ISSUE THREAD

**Issue by sertel** [Sable/soot#332]
Hi,

I'm trying to use Soot's points to analysis and found this e-mail from the Soot mailing list that says I should be using SPARK instead of PADDLE:
https://mailman.cs.mcgill.ca/pipermail/soot-list/2012-September/004823.html

So I started trying to use the example from the survivor guide and hit several problems:

1. I'm on a MAC OS X. Scene.getDefaultClasspath is differentiating between the classpaths depending on the OS version. Sadly, it constructed the wrong one for me and I had to copy the code for "normal" OS and define it explicitly in my test code.
2. One has to explicit turn the optimization on via ```opt.put("enabled", "true");``` otherwise the transformation is just not performed. This is not mentioned in the example code of the Soot survivor guide.
3. The "on-fly-cg" option is a no-op. Looking into the source code, it always uses the OnFlyCallGraphBuilder.
4. The transformation finally hits an error in the call graph construction: ```java.lang.ClassCastException: soot.baf.internal.BIdentityInst cannot be cast to soot.jimple.Stmt```. I also looked into the code and saw no easy way to essentially fix this from the outside. Seems like the OnFloyCallGraphBuilder expects an entirely different internal data structure tree at this point.

I was running on the soot-trunk.jar of today (14.01.2015) using Java 1.8.

Here is the code of the test case:
```
public class testSoot {
  
  /*
   * Example taken from the Soot survivors guide.
   */
  public static class Item {
    Object data;
  }
  
  public static class Container {
    private Item item = new Item();
    
    void setItem(Item item) {
      this.item = item;
    }
    
    Item getItem() {
      return this.item;
    }
  }
  
  public static class MyContainer {
    public void go() {
      Container c1 = new Container();
      Item i1 = new Item();
      c1.setItem(i1);
      Container c2 = new Container();
      Item i2 = new Item();
      c2.setItem(i2);
      Container c3 = c2;
    }
  }
  
  private static SootClass loadClass(String name) {
    SootClass c = Scene.v().loadClassAndSupport(name);
    c.setApplicationClass();
    return c;
  }
  
  @SuppressWarnings("unused")
  @Test
  public void testSpark() throws Throwable {
    // code copied from Scene.getDefaultClasspath
    StringBuffer sb = new StringBuffer();
    sb.append(System.getProperty("java.class.path") + File.pathSeparator);
    sb.append(System.getProperty("java.home"));
    sb.append(File.separator);
    sb.append("lib");
    sb.append(File.separator);
    sb.append("rt.jar");
    
    // configure soot (it tries to do something sophisticated in Scene.getDefaultClasspath for
    // MAC OS X and fails)
    Options.v().set_soot_classpath(sb.toString());
        
    // load class to be inspected into Soot
    SootClass i = loadClass(Item.class.getName());
    SootClass s = loadClass(Container.class.getName());
  
    SootClass c = Scene.v().forceResolve(MyContainer.class.getName(), SootClass.BODIES);
    c.setApplicationClass();
    Scene.v().loadNecessaryClasses();
    SootMethod method = c.getMethodByName("go");
    List<SootMethod> entryPoints = new ArrayList<>();
    entryPoints.add(method);
    Scene.v().setEntryPoints(entryPoints);
    PackManager.v().runPacks();

    // call SPARK
    HashMap<String, String> opt = new HashMap<>();
    opt.put("verbose", "true");
    opt.put("propagator", "worklist");
    opt.put("simple-edges-bidirectional", "false");
    opt.put("on-fly-cg", "false"); // <- does not work anymore!
    opt.put("set-impl", "double");
    opt.put("double-set-old", "hybrid");
    opt.put("double-set-new", "hybrid");
    opt.put("enabled", "true"); // <- need to explicitly enable it
    SparkTransformer.v().transform("", opt);
  }
}
```

Cheers,
Sebastian.

**Comment by StevenArzt** [comment]
Please do no invoke SPARK manually. Instead, enable whole-program mode and then call runPacks(). This will automatically prepare everything that is needed and then generate the callgraph. Normally, you don't need to give any options to SPARK aside from enabling it in the Soot options.

Try this:

```
Options.v().set_whole_program(true);
Options.v().setPhaseOption("cg.spark", "on");
Scene.v().loadNecessaryClasses();

Options.v().set_main_class(entryPoint.getSignature());
PackManager.v().runPacks();

// Happily use the callgraph
System.out.println(Scene.v().getCallGraph().size());
```

Of course, you still need to set your Soot classpath and so on, but for SPARK that should be it.

**Comment by sertel** [comment]
Thanks for that advice! I had to add the following line as SPARK requires jimple instead of baf:

```
Options.v().set_output_format(Options.output_format_jimple);
```

If you want I can again paste the code that I have now for this example such that you can maybe put it onto your wiki as an update.

Something that I'm still puzzled about is this: Soot is a byte code analysis framework for Java but I could not find any utility that maps Java types to the internal data structures. There is a soot.javaToJimple package hierarchy, but it only converts from polyglot to jimple. It is desperately needed as a nice Java API is key to Soot's usability. In the SPARK example this occurs at the following point:

```
SootClass c = Scene.v().forceResolve(MyContainer.class.getName(), SootClass.BODIES);
SootMethod goMethod = c.getMethodByName("go");
```

This method of finding the desired SootMethod is not enough. Normally one has a Java method (```java.lang.reflect.Method```) with all parameter types but the according method in ```SootClass``` takes already the inner types of Soot as its parameters. I can also get the ASM signature of the method (```Type.getMethodDescriptor()```) but I also could not find an according method here.

Is there anything like this?

You could use the SPARK example to show how to do this aspect.

**Comment by StevenArzt** [comment]
Soot loads the program it transforms into a so-called Scene which has no connection to the host JVM. If you have a type called "foo" in the host JVM, this need not have anything to do with the type "foo" loaded into the Soot Scene. This is important as Soot can for instance also analyze Android applications. In that case, all the java.* classes are loaded from the Android SDK, not the Java JDK. Android uses an own implementation of these system classes, so mixing up the Java classes from the host JVM and the Android classes in the Scene could even lead to wrong results.

In general, such a mapping is not needed either, as you stay within the Scene. If you need access to e.g., java.lang.String, just call Scene.v().getSootClass("java.lang.String") and you will get the corresponding Soot object.

One more aspect: SPARK is just the callgraph and pointer analysis algorithm. This has nothing to do with type storage in the Scene.

**Comment by sertel** [comment]
Although the answer was not quite what I expected it nevertheless helped to find this solution for my problem:

```java
  private SootMethod findMethod(SootClass c, Method m) {
    // convert the parameters to Soot types
    List<soot.Type> params = new ArrayList<>(m.getParameterCount());
    for(Class<?> jt : m.getParameterTypes())
      params.add(Scene.v().getSootClass(jt.getName()).getType());
    return c.getMethod(m.getName(), params);    
  }  
```
Thanks for your help!

**Comment by StevenArzt** [comment]
This can work, but it can have some subtle issues. You are asking Soot to get the method from the Scene that happens to have the same signature as a certain method in your host JVM. This does not mean that you are actually getting the same method. Your host JVM might for instance run a different Java version than the rt.jar you have loaded into your Scene, or your Scene might contain the Android SDK while your host JVM contains Java.

Yes, your solution might be what you are looking for, but keep in mind that you're mixing two different things here.

**Comment by sertel** [comment]
The soot-classpath is the same as from the "parent" java program. I load the same class into Soot that I loaded in Java. I do not understand what problems could appear here. Can you explain that to me?

I do understand that this could happen when the classpaths are different or when the SDK versions are different. However, when this is not the case then Soot should give me exactly that class.

**Comment by StevenArzt** [comment]
It can still happen in case you perform dynamic class loading the parent JVM. If this is not the case and you make sure that there is absolutely no difference in class path, you should be pretty safe. In practice, I have such mixed-world code fail quite a number of times due to subtle misconfigurations or things that were overlooked, so I'd generally vote against it. Take it as a personal opinion.

Anyway, the issue itself is resolved and so I close this thread.

**Comment by sertel** [comment]
I would have thought that the issue would be resolved once you fixed the documentation ;)

**Comment by sertel** [comment]
Sorry, me again. I'm just doing some simple testing of the analysis and find it not working.

Change the above test case to:
```java
public static class MyContainer {
    public Object go() {
      Container c1 = new Container();
      Item i1 = new Item();
      c1.setItem(i1);
      Container c2 = new Container();
      c2.setItem(i1); // assigned the same item as to c1
      return new Object[]{c1, c2};
    }
  }
```
Check the points-to sets for c1 and c2 against each other. The analysis says that they do not share references which is clearly wrong. Is there any testing that you do on this part of the framework?

**Comment by StevenArzt** [comment]
The points-to-sets of c1 and c2 have an empty intersection which is correct. There is no notion of "share references". Instead, Point-to-Analysis such as the one in SPARK answers the question whether two elements in the code can point to the same runtime object which is not the case for c1 and c2. If you do the check for c1.item (assuming that "setItem" stores its parameter in a field called "item"), you should find that c1.item and c2.item can point to the same runtime object.

**Comment by sertel** [comment]
Can you please point me to some regression tests?

**Comment by StevenArzt** [comment]
Please refer to Ondrej Lhotak's master thesis in which he developed SPARK, there should be some test mechanisms. For the productive branch of Soot, we do not have explicit test cases for SPARK. However, given that SPARK is used by ABC (which we test with the DaCapo benchmark suite every night) and FlowDroid (which we test with more than 300 test cases every night), we are pretty sure that there are no major problems at the moment. Still, if you find an issue, feel free to report it.
