### ISSUE TITLE
Jasmin error when running CallGraphExample

### ISSUE THREAD

**Issue by stream101** [Sable/soot#334]
Hi,

I am trying to run the call graph example under soot/tutorial/guide (https://github.com/Sable/soot/blob/develop/tutorial/guide/examples/call_graph/src/dk/brics/soot/callgraphs/CallGraphExample.java). 

It successfully compiled and generated CallGraphExample.class. Then I execute the following command under examples/call_graph/src directory: 
```java -Xmx512m -cp <soot> dk/brics/soot/callgraphs/CallGraphExample -soot-class-path /lib/jvm/jdk1.7.0_72/jre/lib/rt.jar:/lib/jvm/jdk1.7.0_72/jre/lib/jce.jar:.```

Then I got a weird Jasmin error message: 

```
Soot started on Wed Jan 14 20:07:39 EST 2015
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
Transforming testers.CallGraphs...
Writing to sootOutput/testers/CallGraphs.class
Jasmin:14: Warning - Syntax error.

^
Jasmin:14: Error - Couldn't repair and continue parse.

^
Jasmin: Found 2 errors
Soot finished on Wed Jan 14 20:08:02 EST 2015
Soot has run for 0 min. 23 sec.
```

I use jasmin-2.4 downloaded from sourceforge. 

Since the error message doesn't give any concrete information, I am really confused how to debug it .... I'm not sure if others encountered this problem too. Any help will be appreciated !!

**Comment by MarcMil** [comment]
Maybe it works better using Jasmin from https://github.com/Sable/jasmin

**Comment by StevenArzt** [comment]
@stream101  Is this issue still open? Did you try again using the Jasmin link provided above?

**Comment by stream101** [comment]
Hi Steven,

Yes I applied the link and it works well.

Thanks !

On Thu, Mar 5, 2015 at 12:44 AM, Steven Arzt <notifications@github.com>
wrote:

> @stream101 <https://github.com/stream101> Is this issue still open? Did
> you try again using the Jasmin link provided above?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sable/soot/issues/334#issuecomment-77326809>.
>



-- 
Xinxin Jin
Ph.D. student, Computer Science
University of California, San Diego
http://cseweb.ucsd.edu/~x7jin/
