### ISSUE TITLE
Options.v().set_android_jars not working

### ISSUE THREAD

**Issue by flycrane** [Sable/soot#335]
Hi,

just found that Options.v().set_android_jars("C:\\Users\\txia\\AppData\\Local\\Android\\sdk\\platforms"); not working as I expected, however setting program args in eclipse works, strange. I am using the latest nightly build.

code:
Options.v().set_android_jars("C:\\Users\\txia\\AppData\\Local\\Android\\sdk\\platforms");
Options.v().set_process_dir(Collections.singletonList("c:\\Work\\soot\\enriched1.apk"));
Options.v().set_output_dir("c:\\Work\\soot\\mytest");
...
System.out.println("jars: " + Options.v().android_jars());
System.out.println("process_dir: " + Options.v().process_dir());
System.out.println("output_dir: " + Options.v().output_dir());

output:
jars: C:\Users\txia\AppData\Local\Android\sdk\platforms
process_dir: [c:\Work\soot\enriched1.apk]
output_dir: c:\Work\soot\mytest
Soot version trunk
Copyright (C) 1997-2010 Raja Vallee-Rai and others.
All rights reserved.

Contributions are copyright (C) 1997-2010 by their respective contributors.
See the file 'credits' for a list of contributors.
See individual source files for details.

Soot comes with ABSOLUTELY NO WARRANTY.  Soot is free software,
and you are welcome to redistribute it under certain conditions.
See the accompanying file 'COPYING-LESSER.txt' for details.

Visit the Soot website:
  http://www.sable.mcgill.ca/soot/

For a list of command line options, enter:
  java soot.Main --help

**Comment by StevenArzt** [comment]
Did you mix Options.v() with the Soot main method? That is not guaranteed to work. Either call the Soot main method and pass in the arguments as parameters to this main method *or* use Options.v() and then use the Soot classes directly.

**Comment by flycrane** [comment]
thanks Steven, sorry I am very new to this and Java.  "use the Soot classes directly" you mean like this? but nothing comes out.

c:\Work\soot>java -cp soot-trunk.jar;. AndroidInstrument

code:
import java.util.Collections;
import soot.options.Options;

public class AndroidInstrument {
	public static void main(String[] args) {
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_output_format(Options.output_format_jimple);
		Options.v().set_prepend_classpath(true);
		Options.v().set_allow_phantom_refs(true);
		Options.v().set_android_jars("c:\\Work\\Tools\\adt\\sdk\\platforms");
		Options.v().set_output_dir("c:\\Work\\soot\\testout");
		
		Options.v().set_process_dir(Collections.singletonList("c:\\Work\\soot\\enriched1.apk"));
		Options.v().set_exclude(Collections.singletonList("android.support."));
	} 
}

**Comment by flycrane** [comment]
Options.v().set_main_class("AndroidInstrument"); doesn't work either

**Comment by StevenArzt** [comment]
Try the following:

```
Options.v().set_src_prec(Options.src_prec_apk);
Options.v().set_process_dir(Collections.singletonList("D:/VirtualDispatch3.apk"));
Options.v().set_android_jars("D:/sdk/platforms");
Options.v().set_allow_phantom_refs(true);
Options.v().set_output_format(Options.output_format_jimple);
Options.v().set_output_dir("c:\Work\soot\testout");

Scene.v().loadNecessaryClasses();
PackManager.v().runPacks();
PackManager.v().writeOutput();
```

**Comment by flycrane** [comment]
this works, thanks Steven.
