### ISSUE TITLE
Expected to be within a catch-all for an instruction where a monitor is held

### ISSUE THREAD

**Issue by MarcMil** [Sable/soot#339]
If you run soot on the current version of the official Skype app on Android 5.0/ART

java -jar soot-trunk.jar -src-prec apk --allow-phantom-refs -output-format dex -force-android-jar /home/marc/adt-bundle-linux-x86_64-20140702/sdk/platforms/android-16/android.jar --process-dir /home/marc/Apps/Benign/com.skype.raider.apk

The ART compiler will complain:
I/dex2oat ( 1418): Verification error in boolean com.skype.android.ads.ConfigManager.a(java.lang.String, long, boolean)
I/dex2oat ( 1418): boolean com.skype.android.ads.ConfigManager.a(java.lang.String, long, boolean) failed to verify: expected to be within a catch-all for an instruction where a monitor is heldn): [0x55]
W/dex2oat ( 1418): mismatched stack depths (depth=1, incoming depth=2)
I/dex2oat ( 1418): Verification error in java.lang.String com.skype.android.ads.ConfigManager.i()
I/dex2oat ( 1418): java.lang.String com.skype.android.ads.ConfigManager.i() failed to verify: expected to be within a catch-all for an instruction where a monitor is held
E/dex2oat ( 1418): Verification failed on class com.skype.android.ads.ConfigManager in /data/app/com.skype.raider-2/base.apk because: Verifier rejected class com.skype.android.ads.ConfigManager due to bad method java.lang.String com.skype.android.ads.ConfigManager.i()
I/dex2oat ( 1418): Verification error in boolean com.skype.android.video.capture.MediaCodecCapturer.start(long)
I/dex2oat ( 1418): boolean com.skype.android.video.capture.MediaCodecCapturer.start(long) failed to verify: expected to be within a catch-all for an instruction where a monitor is held6]
E/dex2oat ( 1418): Verification failed on class com.skype.android.video.capture.MediaCodecCapturer in /data/app/com.skype.raider-2/base.apk because: Verifier rejected class com.skype.android.video.capture.MediaCodecCapturer due to bad method boolean com.skype.android.video.capture.MediaCodecCapturer.start(long)
I/dex2oat ( 1418): Verification error in com.google.inject.aa roboguice.RoboGuice.setBaseApplicationInjector(android.app.Application, com.google.inject.ba)
I/dex2oat ( 1418): com.google.inject.aa roboguice.RoboGuice.setBaseApplicationInjector(android.app.Application, com.google.inject.ba) failed to verify: expected to be within a catch-all for an instruction where a monitor is heldapp.Application, com.google.inject.ba): [0x63]
E/dex2oat ( 1418): Verification failed on class roboguice.RoboGuice in /data/app/com.skype.raider-2/base.apk because: Verifier rejected class roboguice.RoboGuice due to bad method com.google.inject.aa roboguice.RoboGuice.setBaseApplicationInjector(android.app.Application, com.google.inject.ba)
W/dex2oat ( 1418): Compilation of void com.skype.android.video.VideoConversation.performUIAction(int, int[]) took 104.617ms

See https://github.com/babycool111/art/blob/master/runtime/verifier/method_verifier.cc for the dex2oat relevant code

**Comment by MarcMil** [comment]
Ok, I have narrowed down the issue. The jimple code from the apk seems to be wrong.

  label10:
      $int_1 = lengthof $arrString_1;

  label11:

The event handler for this section is:
      catch java.lang.Exception from label10 to label11 with label12;
but should be:
      catch java.lang.Exception from label10 to label11 with label12;
      catch java.lang.Throwable from label10 to label11 with label8;

If you look at the original APK file:

26063e: 0792                                   |002f: move-object v2, v9
260640: 2198                                   |0030: array-length v8, v9
260642: 1206                                   |0031: const/4 v6, #int 0 // #0

The exception handlers:
        0x0030 - 0x003f
          Ljava/lang/Exception; -> 0x0069
          <any> -> 0x0070
The <any> exception handler is not being mapped a trap, causing the Art verifier to fail.

**Comment by StevenArzt** [comment]
I'm currently looking into a very similar issue in Soot. Maybe that will fix this problem as well, but I'm still working on it.

**Comment by StevenArzt** [comment]
The problem occurs in the TrapSplitter and TrapMinimizer. There is a trap for java.lang.Exception over the code region, so Soot removes and minimizes the traps on java.lang.Throwable over the same region as the trap on java.lang.Exception will already catch most of the stuff that can then never end up in the trap on java.lang.Throwable.

While this is usually just fine, Android requires code that holds a monitor to be insidea catch-all handler on java.lang.Throwable at any time, regardless of whether there is an exception that might escape any of the other traps or not. Their bytecode verifier is always assuming the worst case here.

I have a fix, but there is still some problem that I need to investigate before I can upload it.
