### ISSUE TITLE
Use soot to analysis 200 android apps,catch many exception!

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#343]
I use latest Soot :https://ssebuild.cased.de/nightly/soot/lib/ , soot threw these exception,then exit(apks downlod url : http://pan.baidu.com/s/1eQlbh4I): 

      Line 94: Caused by: org.jf.dexlib2.dexbacked.DexBackedDexFile$InvalidItemIndex: Field index out of bounds: 54269
	Line 230: Caused by: java.lang.ArrayIndexOutOfBoundsException: 83
	Line 533: Caused by: Unexpected type null
	Line 760: Caused by: Unexpected type null
	Line 872: Caused by: java.lang.OutOfMemoryError: Java heap space
	Line 996: Caused by: Unexpected type null
	Line 1066: Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	Line 1145: Caused by: java.lang.NullPointerException
	Line 1345: Caused by: java.lang.OutOfMemoryError: Java heap space
	Line 1537: Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	Line 1645: Caused by: java.lang.ArrayIndexOutOfBoundsException: 125
	Line 1707: Caused by: java.lang.OutOfMemoryError: Java heap space
	Line 2277: Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	Line 2392: Caused by: java.lang.ArrayIndexOutOfBoundsException: 11

**Comment by ericbodden** [comment]
It looks like you are giving Soot not enough memory. Try:
java -Xmx15g ... soot.Main
