### ISSUE TITLE
How are we dealing with apk files depending on *.so files?

### ISSUE THREAD

**Issue by ZicongLiu** [Sable/soot#348]
When using soot to instrument android app(for example, candycrushsaga), an exception is thrown saying "soot.SootResolver$SootClassNotFoundException: 
                       couldn't find class: com.amazon.android.framework.task.command.AbstractCommandTask (is your soot-class-path set properly?)"
  However, I can't find the given *.class file so I wonder if the class is put in libcandycrushsaga.so. How can we deal with it through Java? Do I need to deal with it with the help of JNI or something else? Or does Soot provide us with some help on this?

**Comment by StevenArzt** [comment]
A native library cannot contain Java classes. Your classes can only be in Java code. Java can only use JNI to call native methods. On the native side, the notion of classes gets lost - there are only methods which get some parameters that give them access to their environment.

Soot can deal with native methods in such a way that it puts them into the respective SootClass (the one declaring e.g., "native void foo()", but does not associate bodies with them. It sets the native flag which can then be taken into consideration by aliases.

**Comment by ZicongLiu** [comment]
Thanks, it solve my problem!
  By the way, does the -allow-phantom-refs means using phantom functions instead of the real ones for non-existing classes? What does soot do with the dependencies since the jars must have been put somewhere in the apk file so that it can be run normally on Android devices?

**Comment by StevenArzt** [comment]
The -allow-phantom-refs options means that Soot creates phantom classes and phantom methods if the real class or method cannot be found. These dependencies are just artificial placeholders - they are not written out into a new APK file after transformation. On the real device, they must be somewehere on the classpath; this is no different to the original APK. If we assume that the original APK worked on a phone despite the classes we could not resolve, this means that these classes must have come from somewhere on the device. The very same assumption holds for the new, transformed APK.
