### ISSUE TITLE
Is there any error with SootMethod.getDeclaringClass()?

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#350]
I have a project extends from soot, In my project, I defined  MyBodyTransformer :

public class MyBodyTransformer extends BodyTransformer{
     protected void internalTransform(Body body, String phaseName,Map options)
    {
        SootMethod method = body.getMethod();
        SootClass     dClass = method.getDeclaringClass();
    
        if(method.getName().equal("openFileOutput")){
                System.out.println("dclass = " + dClass.getName() );
        }
    }
}

While I use my project to analyse my Android app:

public class MainActivity extends Activity{
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
	setContentView(R.layout.activity_main);

        String fileName = "test.txt";
	FileOutputStream outputStream;
	try {
			outputStream = openFileOutput(fileName, MODE_WORLD_READABLE);
			String content = "hello world";
			outputStream.write(content.getBytes());
			 outputStream.flush();
			outputStream.close();
	} catch (FileNotFoundException e) {
			e.printStackTrace();
	} catch (IOException e) {
			e.printStackTrace();
	}
    }
}

if I use API 17 android.jar for my project  to do this analyses, my project print:
 
       dclass = android.content.ContextWrapper
      
And if I use API 19 , it print : 

       dclass = android.app.Activity

Why they different?  what's wrong?
method.getDeclaringClass() is the class ,in which method  is implemented ?

**Comment by ericbodden** [comment]
> method.getDeclaringClass() is the class ,in which method is implemented ?
Yes

So I guess the API simply changed from 17 to 19? It's been known to happen...

**Comment by WangYeOtw** [comment]
Hi, ericbodden, I have checked Android API 17 and 19 source code again, and I'm sure, both of them , "openFileOutput" is implemented in "android.content.ContextWrapper".

So , I Insists  there is something wrong in SootMethod.getDeclaringClass().

**Comment by ericbodden** [comment]
Hi @WangYeOtw 
The method getDeclaringClass has not changed for over a decade. It's also very simple. There can be nothing wrong with it. Maybe it's a classpath problem?

**Comment by StevenArzt** [comment]
I agree with Eric. I have tested your code and only get

```
dclass = android.content.ContextWrapper
```

for both Android 17 and Android 19.

Where did you get your Android platform JAR files from? Maybe there are broken, I used the official ones from Google's Android SDK.

Furthermore, your code is a bit odd: Transformers are only applied to application classes, but you are looking for the API classes declaring method with a certain name. API classes will however never end up in your transformer with the default settings. I enabled Soot's application mode for these classes to be transformed at all. If I do that, I get the result described above. With that, you however don't even need an app that ever calls the openFileOutput method since all you're doing is a traditional Java analysis on the platform JAR file.

In short: This is not a bug.

My code:

```
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_process_dir(
				Collections.singletonList("D:\\Arbeit\\Android Analyse\\AndroidTestApp\\bin\\AndroidTestApp.apk"));
		Options.v().set_force_android_jar(
				"D:\\Tools\\adt-bundle-windows-x86_64-20140321\\sdk\\platforms\\android-19\\android.jar");
		Options.v().set_soot_classpath("D:\\Tools\\adt-bundle-windows-x86_64-20140321\\sdk\\platforms\\android-19\\android.jar");
		Options.v().set_allow_phantom_refs(true);
		Options.v().set_output_format(Options.output_format_none);
		Options.v().set_app(true);

		Scene.v().loadNecessaryClasses();

		PackManager.v().getPack("jtp").add(new Transform("jtp.foo", new BodyTransformer() {

			protected void internalTransform(Body body, String phaseName, Map options) {
				SootMethod method = body.getMethod();
				SootClass dClass = method.getDeclaringClass();
				if (method.getName().equals("openFileOutput")) {
					System.out.println("dclass = " + dClass.getName());
				}
			}

		}));
```

**Comment by WangYeOtw** [comment]
@StevenArzt , After updated my Android SDK,  the problem have solved, I'm so sorry, and big thanks.

About my odd code:
While I analyse invoke expressions in a method, I want to know where the invoked method implemented .
