### ISSUE TITLE
operation requires resolving level SIGNATURES but *.* is at resolving level HIERARCHY

### ISSUE THREAD

**Issue by Benjamin-T** [Sable/soot#357]
Hi~
I'm trying to run the VeryBusyAnalysis example given in [A Survivor's Guide to Java Program Analysis with Soot]( http://www.brics.dk/SootGuide/). But get the runtime exception as below.

> Exception in thread "main" java.lang.RuntimeException: This operation requires resolving level SIGNATURES but testers.VeryBusyClass is at resolving level HIERARCHY
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(testers.VeryBusyClass,SIGNATURES);
Otherwise, try whole-program mode (-w).

I think the code is quite straightforward, but I don't understand what is this resolving level about. And after I add this "Scene.v().addBasicClass(testers.VeryBusyClass,SIGNATURES);" as the exception suggests, it gives me another exception says to add "Scene.v().addBasicClass(java.lang.System,SIGNATURES);" I don't think this is how it works, please tell me what am I missing. I'm using the soot-trunk.jar, the example code is as follow and I've put some setup in it. Thanks in advance.
 
    public static void main(String[] args) {
		args = new String[] {"testers.VeryBusyClass"};
		
		if (args.length == 0) {
			System.out.println("Usage: java RunVeryBusyAnalysis class_to_analyse");
			System.exit(0);
		}
		// some setup added by myself
		Scene.v().setSootClassPath(Scene.v().getSootClassPath() + 
				":/Users/Benze/Dev/workspace_bak/TestSoot/bin");
		//Scene.v().addBasicClass("testers.VeryBusyClass",SootClass.SIGNATURES);
		Scene.v().loadNecessaryClasses();
		
		SootClass sClass = Scene.v().loadClassAndSupport(args[0]);		
		sClass.setApplicationClass();
		
		Iterator methodIt = sClass.getMethods().iterator();
		while (methodIt.hasNext()) {
			SootMethod m = (SootMethod)methodIt.next();
			Body b = m.retrieveActiveBody();
			
			System.out.println("=======================================");			
			System.out.println(m.toString());
			
			UnitGraph graph = new ExceptionalUnitGraph(b);
			VeryBusyExpressions vbe = new SimpleVeryBusyExpressions(graph);
			
			Iterator gIt = graph.iterator();
			while (gIt.hasNext()) {
				Unit u = (Unit)gIt.next();
				List before = vbe.getBusyExpressionsBefore(u);
				List after = vbe.getBusyExpressionsAfter(u);
				UnitPrinter up = new NormalUnitPrinter(b);
				up.setIndent("");
				
				System.out.println("---------------------------------------");			
				u.toString(up);			
				System.out.println(up.output());
				System.out.print("Busy in: {");
				String sep = "";
				Iterator befIt = before.iterator();
				while (befIt.hasNext()) {
					AbstractBinopExpr e = (AbstractBinopExpr)befIt.next();
					System.out.print(sep);
					System.out.print(e.toString());
					sep = ", ";
				}
				System.out.println("}");
				System.out.print("Busy out: {");
				sep = "";
				Iterator aftIt = after.iterator();
				while (aftIt.hasNext()) {
					AbstractBinopExpr e = (AbstractBinopExpr)aftIt.next();
					System.out.print(sep);
					System.out.print(e.toString());
					sep = ", ";
				}			
				System.out.println("}");			
				System.out.println("---------------------------------------");
			}
			
			System.out.println("=======================================");
		}
	}

**Comment by ericbodden** [comment]
Hi.

This section of the guide seems outdated. Calling loadClassAndSupport is not recommended.

Instead run your code in a transformer. Please check out the other tutorials on the webpage.

Cheers,
Eric

> On 09.02.2015, at 05:15, Benze Tang <notifications@github.com> wrote:
> 
> Hi~
> I'm trying to run the VeryBusyAnalysis example given in A Survivor's Guide to Java Program Analysis with Soot. But get the runtime exception as below.
> 
> Exception in thread "main" java.lang.RuntimeException: This operation requires resolving level SIGNATURES but testers.VeryBusyClass is at resolving level HIERARCHY
> If you are extending Soot, try to add the following call before calling soot.Main.main(..):
> Scene.v().addBasicClass(testers.VeryBusyClass,SIGNATURES);
> Otherwise, try whole-program mode (-w).
> 
> I think the code is quite straightforward, but I don't understand what is this resolving level about. And after I add this "Scene.v().addBasicClass(testers.VeryBusyClass,SIGNATURES);" as the exception suggests, it gives me another exception says to add "Scene.v().addBasicClass(java.lang.System,SIGNATURES);" I don't think this is how it works, please tell me what am I missing. I'm using the soot-trunk.jar, the example code is as follow and I've put some setup in it. Thanks in advance.
> 
> public static void main(String[] args) {
>     args = new String[] {"testers.VeryBusyClass"};
> 
>     if (args.length == 0) {
>         System.out.println("Usage: java RunVeryBusyAnalysis class_to_analyse");
>         System.exit(0);
>     }
>     // some setup added by myself
>     Scene.v().setSootClassPath(Scene.v().getSootClassPath() +
>             ":/Users/Benze/Dev/workspace_bak/TestSoot/bin");
>     //Scene.v().addBasicClass("testers.VeryBusyClass",SootClass.SIGNATURES);
>     Scene.v().loadNecessaryClasses();
> 
>     SootClass sClass = Scene.v().loadClassAndSupport(args[0]);
>     sClass.setApplicationClass();
> 
>     Iterator methodIt = sClass.getMethods().iterator();
>     while (methodIt.hasNext()) {
>         SootMethod m = (SootMethod)methodIt.next();
>         Body b = m.retrieveActiveBody();
> 
>         System.out.println("=======================================");
>         System.out.println(m.toString());
> 
>         UnitGraph graph = new ExceptionalUnitGraph(b);
>         VeryBusyExpressions vbe = new SimpleVeryBusyExpressions(graph);
> 
>         Iterator gIt = graph.iterator();
>         while (gIt.hasNext()) {
>             Unit u = (Unit)gIt.next();
>             List before = vbe.getBusyExpressionsBefore(u);
>             List after = vbe.getBusyExpressionsAfter(u);
>             UnitPrinter up = new NormalUnitPrinter(b);
>             up.setIndent("");
> 
>             System.out.println("---------------------------------------");
>             u.toString(up);
>             System.out.println(up.output());
>             System.out.print("Busy in: {");
>             String sep = "";
>             Iterator befIt = before.iterator();
>             while (befIt.hasNext()) {
>                 AbstractBinopExpr e = (AbstractBinopExpr)befIt.next();
>                 System.out.print(sep);
>                 System.out.print(e.toString());
>                 sep = ", ";
>             }
>             System.out.println("}");
>             System.out.print("Busy out: {");
>             sep = "";
>             Iterator aftIt = after.iterator();
>             while (aftIt.hasNext()) {
>                 AbstractBinopExpr e = (AbstractBinopExpr)aftIt.next();
>                 System.out.print(sep);
>                 System.out.print(e.toString());
>                 sep = ", ";
>             }
>             System.out.println("}");
>             System.out.println("---------------------------------------");
>         }
> 
>         System.out.println("=======================================");
>     }
> }
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Prof. Eric Bodden, Ph.D., http://sse.ec-spride.de/ http://bodden.de/
Head of Secure Software Engineering at Fraunhofer SIT, TU Darmstadt and EC SPRIDE
Tel: +49 6151 16-75422    Fax: +49 6151 869-127
Room B5.11, Fraunhofer SIT, Rheinstraße 75, 64295 Darmstadt

**Comment by Benjamin-T** [comment]
Ok, seems that extending Soot with transformer is the canonical way to do this. Thanks~

**Comment by 2048li** [comment]
Hi, I have the same problem.
But in my analysis the transformer is needless[is transformer pre-requisite?]; and  if i move my method to a transformer, it also throws this error. Any idea? 
Thanks.

**Comment by czchao** [comment]
Hi @t-benze  ,
I met the similar problem, can you show some detail about running code above in transformer.
How to process code below in transformer?
Thanks.
`SootClass sClass = Scene.v().loadClassAndSupport(args[0]);
sClass.setApplicationClass();
`

**Comment by edwardpassagi** [comment]
Crazy how the last question asked was literally right before I started doing CS in my college, and now here I am...  a Master's student having the exact problem someone all the way back from 2015 had.

In any case, how can I approach this? I'm having the same issue when trying to do a static analysis on `Mockito` repo

**Comment by ericbodden** [comment]
Hello. I am afraid that the class resolution in Soot is quite intricate. Hence it's impossible to answer your question without full access to the code. If you could share it, that could help.

BTW we are heavily working on a new major release that will greatly overhaul Soot's architecture including its class loading. That should finally get rid of these problems.

**Comment by cogbee** [comment]
-w solve my problem
