### ISSUE TITLE
How to invoke loadClassAndSupport when using soot on apk files?

### ISSUE THREAD

**Issue by ZicongLiu** [Sable/soot#364]
I'm using soot on Android applications using the wiki at "Instrumenting Android Apps with Soot" (https://github.com/Sable/soot/wiki/Instrumenting-Android-Apps-with-Soot). However, when I'm using Scene.v().loadClassAndSupport(XXX); to load a class written by myself, I cannot achieve my goal since an Exception is thrown saying "You are analyzing an Android application but did not define android.jar. Options -android-jars or -force-android-jar should be used."
  By reading the source code, namely soot/Scene.java, I found out that when invoking loadClassAndSupport you checked whether Options.v().android_jars() has been set when the wiki told us to input the information of android-jars in args.
  So how can I achieve this?

**Comment by StevenArzt** [comment]
Usually, you should not call loadClassAndSupport on your own. If your class is inside the APK, it will automatically be loaded as an application class and thus automatically be available in the Soot Scene. If your class is lying around as a Java class file on disk and is not in the process-dir, you need to put it on the Soot classpath and then call "addBasicClass" in your code to load it.

There is a much longer tutorial on instrumenting Android applications available here: http://sseblog.ec-spride.de/tutorials/ We gave this tutorial at RV'13 and CCS'13.

**Comment by ZicongLiu** [comment]
Thanks, it seems to solve my problem, despite the occurrence of other problems... I'll try to solve them with the help of addBasicClass.
