### ISSUE TITLE
APK output fails to display graphics

### ISSUE THREAD

**Issue by chpkim** [Sable/soot#366]
Reading in the original APK and outputting it without applying transformation causes blank screen for apps that use LibGDX graphics engine. Apps include:

https://github.com/siondream/freegemas-gdx
https://github.com/pierotofy/snappyfrog

**Comment by ericbodden** [comment]
Again, it would help tremendously to have an indication of where the app fails.

**Comment by Alexandre-Bartel** [comment]
Could you share the apks?

**Comment by Alexandre-Bartel** [comment]
Fixed with db8e4fe4061f14b86e7d68b10e0ac83176b65612.
