### ISSUE TITLE
An app output by Soot has its screen flipped

### ISSUE THREAD

**Issue by chpkim** [Sable/soot#368]
An OpenGL darts game output by Soot, without applying any transformation, has its screen flipped along the x-axis. Here is the app: https://github.com/Ertyguy/Darts. There seems to be considerable amount of difference between the original smali and the output smali of the main rendering loop file. 

Original smali: https://drive.google.com/file/d/0B9KLXcAovVUHXzdjOXpubE5Zc1U/view?usp=sharing

Output smali: https://drive.google.com/file/d/0B9KLXcAovVUHMTVsdUE3bDUzTWs/view?usp=sharing

Soot also seems to be having trouble transforming other OpenGL games. After I run them, they seem to crash.

**Comment by ericbodden** [comment]
Lol - this is an interesting effect. I am afraid we will have to know more about what exactly causes the flip to be able to help you. Can you pinpoint the actual problem in the generated code? Also make sure you tried the latest build of Soot please.

**Comment by Alexandre-Bartel** [comment]
Fixed with db8e4fe4061f14b86e7d68b10e0ac83176b65612.
