### ISSUE TITLE
Autoboxing of java Primitives doesn't work in DexPrinter

### ISSUE THREAD

**Issue by jolealdoneto** [Sable/soot#375]
Hello guys, first of all thanks for working on this lib, it's pretty awesome.

This happens when trying to transform a body in an android apk.

I would like to simply report that autoboxing in the DexPrinter class doesn't work. Basically, if you try to cast any RefType to any primitive you will not be able to. This happens exactly in line 24 from PrimitiveType.java, that assumes that the source class is always a primitive as well. Bellow you can find the stacktrace. I think it can be related to https://github.com/Sable/soot/issues/240

My command line: java -cp "../TestingSoot/lib/*:../../*:."  AndroidInstrument -pp -android-jars ~/adt-bundle-linux-x86_64-20140702/sdk/platforms/android-20 -process-dir ~/prj/android/ClientSide/bin/ClientMain-debug.apk -allow-phantom-refs -w

java.lang.RuntimeException: not found: java.lang.Object
	at soot.toDex.PrimitiveType.getByName(PrimitiveType.java:24)
	at soot.toDex.ExprVisitor.castPrimitive(ExprVisitor.java:589)
	at soot.toDex.ExprVisitor.caseCastExpr(ExprVisitor.java:550)
	at soot.jimple.internal.AbstractCastExpr.apply(AbstractCastExpr.java:134)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:373)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1152)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1035)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:932)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:489)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1281)
	at soot.PackManager.writeClass(PackManager.java:993)
	at soot.PackManager.writeOutput(PackManager.java:617)
	at soot.PackManager.writeOutput(PackManager.java:523)
	at soot.Main.run(Main.java:246)
	at soot.Main.main(Main.java:152)
	at AndroidInstrument.main(AndroidInstrument.java:73)

**Comment by StevenArzt** [comment]
Auto-boxing is compiler feature and does not exist in Java bytecode or Dalvik code. Therefore, casts between reference types and primitive types are always disallowed in Soot. If you want to do boxing, you need to do it manually.

The problem of a cast between a primitive type and a reference type that you seem to be seeing in an APK file you are reading in and then trying to write back out is thus presumably either related to a custom transformation you apply on the way (do you perform instrumentation?) or to a bug in Soot that produced invalid code when reading in the original file.

If you are not changing the Jimple bodies of any method in any way, then I assume we have a bug in the Dalvik front-end. If this is true and the issue happens if you just run Soot on the command-line, then please send me the APK file to Steven.Arzt@cased.de.

**Comment by jolealdoneto** [comment]
Hi Steven,

thanks for the answer. I am doing some instrumentation and also transforming the bytecode, so the problem might be on my side. The strange thing is, I first tried the code in "vanilla" soot: That is Java -> Jimple -> [transformation] -> Jimple -> Java. But as soon as I moved the process to android, that is: APK -> Java -> Jimple -> [transformation] -> Jimple -> Java -> APK, I got the problem.

A quick question, if a have an IntType (or any primitive), how can I transform it to a RefType.v("java.lang.Integer") if casting between primitive and object are not allowed?

Thank you!

**Comment by StevenArzt** [comment]
The individual steps Soot performs before writing out Dalvik bytecode differ from the steps that are taken to create Java bytecode. Invalid code that is detected by one output writer need not necessarily be detected by another output writer. Enabling the -validate option is generally a good idea to have Soot perform some basic checks. Still, these checks are not complete either - we're constantly working on enhancing them.

To box primitive integer, you need to create Jimple code that creates a new instance of java.lang.Integer and calls the constructor of that box class with the primitive value that you want to box.

**Comment by jolealdoneto** [comment]
Okay, thanks for the clarification. I suppose we can close the ticket then.
