### ISSUE TITLE
What is the difference of path setting between intra analysis and inter analysis?

### ISSUE THREAD

**Issue by nana1904** [Sable/soot#395]
Hi all, 

I hava a string exception. When I do intra analysis, it is ok, but when I open whole program command to do inter analysis, the exception comes up. 
Exception in thread "main" java.lang.RuntimeException: couldn't find class: java.lang.AutoCloseable (is your soot-class-path set properly?)

Could some people kindly point out the possible error ? 

Thanks,
Naling

**Comment by StevenArzt** [comment]
Can you post your complete Soot command line?

**Comment by nana1904** [comment]
Options.v().set_whole_program(true);
	PhaseOptions.v().setPhaseOption("cg.spark","enabled:true");//enable spark function	    
	PhaseOptions.v().setPhaseOption("cg.spark","on-fly-cg:true"); // enable on-fly-cg to calculate call graph
	PhaseOptions.v().setPhaseOption("wstp", "enabled:true");

**Comment by nana1904** [comment]
I use the command:
java -cp soot-2.5.0.jar:/usr/local/opt/tomcat/libexec/lib/servlet-api.jar:/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Classes/rt.jar:src:test  MyTransformer *.class

MyTransformer is wjtp, inside MyTransformer,  I set the following command:
Options.v().set_whole_program(true);
PhaseOptions.v().setPhaseOption("cg.spark","enabled:true");//enable spark function      
PhaseOptions.v().setPhaseOption("cg.spark","on-fly-cg:true"); // enable on-fly-cg to calculate call graph
PhaseOptions.v().setPhaseOption("wstp", "enabled:true"); 


It will have exception, but if I use cmd:
java -cp soot-2.5.0.jar:src/:test/:/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Classes/rt.jar:/usr/local/opt/tomcat/libexec/lib/servlet-api.jar  MyTransformer1  *.class

MyTransformer1 is jtp which doesn't set whole program mode, then it runs ok.

**Comment by StevenArzt** [comment]
You also need to set the Soot classpath so that it points to the classes that you want to analyze,

**Comment by nana1904** [comment]
I think I already set soot class path,
-cp soot-2.5.0.jar

**Comment by ericbodden** [comment]
Soot has its own classpath, which goes _after_ soot-2.5.0.jar
Please read the documentation.

**Comment by StevenArzt** [comment]
Furthermore, Soot 2.5 is quite outdated. You should update to the latest nightly build.
