### ISSUE TITLE
java.lang.RuntimeException when run the example AndroidInstrument.java

### ISSUE THREAD

**Issue by jxnu707** [Sable/soot#398]
hi,
i have an android.jar in the path:C:\Users\Administrator\Desktop,but it throws an exception like can't find android.jar.
and it's weird that it goes to a directory(..\Desktop\android-10\)whick is not exist.

I just learn about soot for two days,I really want to know how to fix it!
Thanks!
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-android-jars C:\Users\Administrator\Desktop -process-dir C:\Users\Administrator\Desktop\test.apk

Max Memory:
247MB

Stack trace:
java.lang.RuntimeException: error: target android.jar (C:\Users\Administrator\Desktop\android-10\android.jar) does not exist.
	at soot.Scene.getAndroidJarPath(Scene.java:308)
	at soot.Scene.defaultAndroidClassPath(Scene.java:472)
	at soot.Scene.defaultClassPath(Scene.java:436)
	at soot.Scene.getSootClassPath(Scene.java:233)
	at soot.SourceLocator.getClassSource(SourceLocator.java:67)
	at soot.Scene.tryLoadClass(Scene.java:665)
	at soot.Scene.loadBasicClasses(Scene.java:1267)
	at soot.Scene.loadNecessaryClasses(Scene.java:1346)
	at soot.Main.run(Main.java:213)
	at soot.Main.main(Main.java:152)
	at AndroidInstrument.main(AndroidInstrument.java:82)

**Comment by StevenArzt** [comment]
If you use the -android-jars parameter, Soot will extract the target SDK version from your APK file and use the corresponding Android platform JAR file for this particular version. Soot expects the platform JAR directory to be structured like the "platforms" directory in your Android SDK, i.e., there have to be subfolders for all the installed Android versions. If you want to force Soot to use a specific Android JAR file, use the -force-android-jar command-line parameter instead.

**Comment by jxnu707** [comment]
Thanks!
But I got another problem.My APK file used android-18,and I used -android-jar command-line with parameter like X:\adt-bundle-windows-x86-20130911\adt-bundle-windows-x86-20130911\sdk\platforms which cantains android-18.jar in it.But it threw an exception like 

Soot started on Mon Apr 27 23:35:11 CST 2015
Using 'X:\adt-bundle-windows-x86-20130911\adt-bundle-windows-x86-20130911\sdk\pl
atforms\android-18\android.jar' as android.jar
soot.SootResolver$SootClassNotFoundException: couldn't find class: android.graph
ics.pdf.PdfDocument$Page (is your soot-class-path set properly?)

I found that there is no  package "graphics.pdf" from android-18.
Dose soot only support Android-17 or below for now?

**Comment by StevenArzt** [comment]
Presumably, that class just isn't contained in your Android JAR file. This is not a Soot problem. We just take the Android JAR files as-is. You can use the -allow-phantoms-refs option to work around this issue.

**Comment by jxnu707** [comment]
@StevenArzt 
I have sovled the problem by your advice,Thanks!
But I failed to disassemble an APK that only  transforming application classes to Jimple as exceptation.Specifically,I got many Jimple files like android.surppot-v4.xxx.Jimple even with option -x Android.  in command line.
Is there any way to get the Jimple files which only in the application's package?

**Comment by StevenArzt** [comment]
These classes are contained in the APK file as well, so they are application classes from Soot's perspective. The only possibility to exclude them would be to have a transformer that explicitly marks them as library classes before the write-out happens.

**Comment by jxnu707** [comment]
@StevenArzt 
I will try it,Thank you!

**Comment by Dhani92** [comment]
Can you please suggest the syntax to use the force-android-jar command line parameter?
