### ISSUE TITLE
Publish Soot to Maven

### ISSUE THREAD

**Issue by malaverdiere** [Sable/soot#42]
Maven and Maven-related (SBT, Ivy, Buildr, etc.) users wishing to use Soot as a library in their programs have to resort to maven kung-fu to handle the dependency.

Soot should be published to a major Maven repository in order to facilitate usage by those users.

**Comment by edwardmp** [comment]
+1

**Comment by anddann** [comment]
Currently, we publish soot nightly builds to a nexus repository https://soot-build.cs.upb.de/nexus/.
To use our Nexus server reference soot as follows in your pom.xml or gradle.properties:
```<dependencies>
  <dependency>
    <groupId>ca.mcgill.sable</groupId>
    <artifactId>soot</artifactId>
    <version>3.0.0-SNAPSHOT</version>
  </dependency>
</dependencies>
<repositories>
  <repository>
    <id>soot-snapshot</id>
    <name>soot snapshots</name>
    <url>https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/</url>
  </repository>
</repositories>	```

**Comment by anddann** [comment]
we finally publish soot to maven central

```
<dependencies>
  <dependency>
    <groupId>ca.mcgill.sable</groupId>
    <artifactId>soot</artifactId>
    <version>4.0.0</version>
  </dependency>
</dependencies>
```
