### ISSUE TITLE
a try-catch error of current soot branch develop

### ISSUE THREAD

**Issue by xhzhang** [Sable/soot#421]
I am currently using soot to do some static analysis, and first thank you all for your contributions. 
When I run soot develop branch with a DroidBench test case, i.e. the Exceptions2 of category General-Java, the generated jimple file seems to miss some instruction mistakenly.
Here is the source code:
![image](https://cloud.githubusercontent.com/assets/5550773/7607149/b6809940-f991-11e4-821b-484d050fda65.png)

we can see that line 33 is not dead code, but in jimple this line is optimized to nothing. In fact, the local "imei" disappeared.
Here is the generated jimple:
![image](https://cloud.githubusercontent.com/assets/5550773/7607374/600b1c1e-f993-11e4-8d81-88c0b0bcca70.png)
So we can see that in label2 the instruction missed, and there is no "imei" local in this jimple file.

I run the same test case with the Soot Eclipse Plugin, and it worked fine. So I guess maybe its some little bug in current develop branch.
Thank you!

**Comment by StevenArzt** [comment]
Line 33 is dead code. The only use of the "imei" variable is in the exception handler. However, there is no possibility for an exception to be thrown *after* line 33 has been executed, so the value assigned to "imei" in line 33 is never used.
