### ISSUE TITLE
java.lang.RuntimeException when analyzing DaCapo with Soot+TamiFlex

### ISSUE THREAD

**Issue by manasthakur** [Sable/soot#422]
Steps to reproduce:
I followed the same steps mentioned at https://github.com/secure-software-engineering/tamiflex/tree/master/dacapo-scripts in order to analyze DaCapo.

Files used to reproduce: 
Same as mentioned in the above webpage.

Soot version: soot-2.5.0

Command line:
-w -app -p cg.spark enabled -p cg reflection-log:/Users/manas/benchmarks/out/avrora-small/run.log -cp /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar:/Users/manas/benchmarks/out/avrora-small -main-class Harness -include org.apache. -include org.w3c. -d /Users/manas/benchmarks/sootified Harness

Max Memory:
1820MB

Stack trace:
java.lang.RuntimeException: Line: '/usr/bin/java -cp /Users/manas/benchmarks/dacapo-9.12-bach.jar -javaagent:poa.jar=/Users/manas/benchmarks/out/avrora-small Harness --scratch-directory /Users/manas/benchmarks/scratch -n 3 avrora -s small'
	at soot.Scene.addReflectionTraceClasses(Scene.java:1267)
	at soot.Scene.loadBasicClasses(Scene.java:1219)
	at soot.Scene.loadNecessaryClasses(Scene.java:1302)
	at soot.Main.run(Main.java:214)
	at soot.Main.main(Main.java:152)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at soot.Scene.addReflectionTraceClasses(Scene.java:1252)
	... 4 more

**Comment by manasthakur** [comment]
I found that the log files themselves are not being generated while running the script "dump-all". The contents of each log file are following:

java -cp /Users/manas/benchmarks/dacapo-9.12-bach.jar -javaagent:poa-2.0.2.jar=/Users/manas/benchmarks/out/avrora-small Harness --scratch-directory /Users/manas/benchmarks/scratch -n 3 avrora -s small
objc[29729]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Error opening zip file or JAR manifest missing : poa-2.0.2.jar
Error occurred during initialization of VM
agent library failed to init: instrument

Please look into it from this post onwards.

**Comment by StevenArzt** [comment]
@ericbodden Can you have a look?

**Comment by manasthakur** [comment]
Works properly on Linux. Mostly some classpath permission issues on Mac OS X.
