### ISSUE TITLE
Options.v().set_keep_line_number doesn't work

### ISSUE THREAD

**Issue by Azure-Vani** [Sable/soot#426]
I import soot-truck.jar (nightly build version, MD5 274f66517ebb4933d26e2c75fe0062d9) into my project and want to analyze a java class file. (jdk 1.8 and language version is java 8)

But I can not get line number tag after setting Options.v().set_keep_line_number option. Here is the code snippets:

    import soot.*;
    import soot.tagkit.LineNumberTag;
    import soot.toolkits.scalar.*;
    import soot.options.Options;
    
    import java.util.Iterator;
    
    /**
     * Created by Vani on 4/17/15.
     */
    
    public class Main {
        public static void main(String argv[]) {
            String old = Scene.v().getSootClassPath();
            Scene.v().setSootClassPath(old + ":/Users/Vani/Patl4J/sample-test-projects/testAB/bin:/Users/Vani/Patl4J/sample-test-projects/testAB");
            SootClass s = Scene.v().loadClassAndSupport("testAB.ABCase");
            Scene.v().loadNecessaryClasses();
            Options.v().set_keep_line_number(true);
            for (Iterator it = s.getMethods().iterator(); it.hasNext(); ) {
                SootMethod fun = (SootMethod) it.next();
                System.out.println(fun.getDeclaration());
    
                Body body = fun.retrieveActiveBody();
    
                // print the Jimple units
                PatchingChain<Unit> u = body.getUnits();
                for (Iterator uIt = u.iterator(); uIt.hasNext(); ) {
                    Unit unit = (Unit) uIt.next();
                    int lineNum = ((LineNumberTag) unit.getTag("LineNumberTag")).getLineNumber();
                    System.out.println("\t" + lineNum + ": " + unit);
                }
            }
        }
    }

In fact, the tag list for an unit is empty. Am I mistaking something?

**Comment by StevenArzt** [comment]
You are setting the option after you have already loaded the classes. That can't work. You must set the option before so that the Soot class loader knows that it shall also load line numbers.

**Comment by Azure-Vani** [comment]
But it doesn't work although I have move the statement Options.v().set_keep_line_number(true); to the very beginning of the program. The taglist for unit is empty.


    import soot.*;
    import soot.tagkit.LineNumberTag;
    import soot.toolkits.scalar.*;
    import soot.options.Options;

    import java.util.Iterator;

    /**
     * Created by Vani on 4/17/15.
     */

    public class Main {
        public static void main(String argv[]) {
            Options.v().set_keep_line_number(true);

            String old = Scene.v().getSootClassPath();
            Scene.v().setSootClassPath(old + ":/Users/Vani/Patl4J/sample-test-projects/testAB/bin:/Users/Vani/Patl4J/sample-test-projects/testAB");
            SootClass s = Scene.v().loadClassAndSupport("testAB.ABCase");
            Scene.v().loadNecessaryClasses();
            for (Iterator it = s.getMethods().iterator(); it.hasNext(); ) {
                SootMethod fun = (SootMethod) it.next();
                System.out.println(fun.getDeclaration());

                Body body = fun.retrieveActiveBody();

                // print the Jimple units
                PatchingChain<Unit> u = body.getUnits();
                for (Iterator uIt = u.iterator(); uIt.hasNext(); ) {
                    Unit unit = (Unit) uIt.next();
                    int lineNum = ((LineNumberTag) unit.getTag("LineNumberTag")).getLineNumber();
                    System.out.println("\t" + lineNum + ": " + unit);
                }
            }
        }
    }

In fact, [here](https://mailman.cs.mcgill.ca/pipermail/soot-list/2014-September/007304.html) is another guy who seems met the same problem with me but  there is no workable solution in maillist.

**Comment by StevenArzt** [comment]
Querying the tag manually is not the preferred way to obtain the line number. Have you tried unit.getJavaSourceStartLineNumber() instead? It will automatically query two possible tags that may both store the line number information.

**Comment by Azure-Vani** [comment]
@StevenArzt It does work! Thanks a lot! :)
