### ISSUE TITLE
BPrimitiveCastInst problem

### ISSUE THREAD

**Issue by GithubChristianG** [Sable/soot#434]
Hello,

I have encountered what I think is a problem. Inside the setValue() method in the Java library class DateTimeParseContext,  the instruction i7 = (int) r1 results in a BPrimitiveCastInst (RefType ---> int) object, and then an exception is thrown inside the toString() method because there is no case for a RefType as a fromtype.

Best regards ChristianG.

**Comment by Alexandre-Bartel** [comment]
Could you give a minimum working example reproducing your problem as well as the full command line you use to launch Soot?

**Comment by StevenArzt** [comment]
DateTimeParseContext does not appear to be included inside the Oracle JDK. I downloaded the Threeten backport for Java 7 JAR file which does include the class, but there is no setValue() method. Please provide the exact target JAR files or classes on which you run Soot.

**Comment by GithubChristianG** [comment]
This is the program I used and run it in Eclipse with SOOT.

public class Test 
{
    public static void main(String[] args)
    {
        String newargs[] = {
        "-allow-phantom-refs",
        "-include-all",
        "-d", "c:\\Temp",
        "-process-dir","C:\\Program Files (x86)\\Java\\jre1.8.0_31\\lib\\rt.jar",
        "-cp","C:\\Program Files (x86)\\Java\\jre1.8.0_31\\lib\\jce.jar","C:\\Program Files (x86)\\Java\\jre1.8.0_31\\lib\\jsse.jar"};
        soot.Main.main(newargs);        
    }
}

Tell me if you need more information
/ChristianG

**Comment by GithubChristianG** [comment]
I think I gave you the wrong class. It should be: java.time.format.DateTimeFormatterBuilder$ReducedPrinterParser

/ChristianG

**Comment by StevenArzt** [comment]
I can reproduce the issue. This is indeed a bug.

**Comment by GithubChristianG** [comment]
Is this fix in the latest nightly build?

/Christian
