### ISSUE TITLE
Mavenize Build

### ISSUE THREAD

**Issue by malaverdiere** [Sable/soot#44]
Building Soot can be a bit difficult for newcomers. A simpler build process that handles all the dependencies  is desirable.

Further, the build process should take in consideration the projected modularization  (see #43)

Soot should be built using Maven or Ivy, and the whole software should be buildable from a single command, with no parametrization needed.

**Comment by timtadh** [comment]
I actually created a pretty good solution to building soot with apache buildr. It is in my jpdg repository. It could definitely be cleaned up to an included here. Although, to be honest if I had to do it again I would try and see if I could use gradle do to the broader support and easier install.

**Comment by StevenArzt** [comment]
The worst aspect of Soot dependency management is currently JastAddJ. For all other dependencies, we just need the respective JAR file, but for JastAddJ, we do actually need the source. Given that this front-end is really outdated anyway, we should first get this back into an acceptable state (https://github.com/Sable/soot/issues/300) and make it a normal clear-cut library dependency. As I said, we have no control over the project, but apparently their new version can be compiled into a single JAR file one can just use. Or we switch to something else entirely for parsing Java source files, doesn't matter from the point of dependency management.

**Comment by timtadh** [comment]
@StevenArzt I have had success hooking into the OpenJDK compiler and getting their AST. It has been about 3 years since I have done it. It wasn't TOO hairy. The big advantage is that since it is the compiler the source is parsed in the "correct" way.
