### ISSUE TITLE
Can not fount class after set_whole_program

### ISSUE THREAD

**Issue by Azure-Vani** [Sable/soot#443]
I have write such code snippets:

```
    Options.v().set_whole_program(true);
    Options.v().setPhaseOption("cg.spark","on");
    Options.v().setPhaseOption("jb", "use-original-names:true");
    Options.v().set_keep_line_number(true);

    SootClass s = Scene.v().loadClassAndSupport("EntryClass");
    Scene.v().loadNecessaryClasses();
    Options.v().set_main_class("EntryClass");
    Scene.v().addBasicClass("husacct.XMLReportWriter",SootClass.SIGNATURES);
    Scene.v().addBasicClass("javax.crypto.IllegalBlockSizeException",SootClass.SIGNATURES);

    PackManager.v().runPacks();
    Scene.v().getClass("husacct.XMLReportWriter");
    Scene.v().loadClassAndSupport("husacct.XMLReportWriter");
```

And `Scene.v().getClass("husacct.XMLReportWriter")` reported that can not found the class, while `Scene.v().loadClassAndSupport("husacct.XMLReportWriter")` complained 

```
    This operation requires resolving level SIGNATURES but husacct.XMLReportWriter is at resolving level HIERARCHY
```

Although I have written `Scene.v().addBasicClass("husacct.XMLReportWriter", SootClass.SIGNATURES);`

So what should I do to resolve the issue? And what's the difference between `loadNecessaryClasses`, `loadClass`, `loadClassAndSupport`, `getClass`, `addBasicClass`?

**Comment by ericbodden** [comment]
Hi.

Please don’t use loadClassAndSupport unless you know what you are doing. Instead call Soot’s main method and hook in your own Transformers where needed.

Eric
