### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [Sable/soot#447]
Can you perhaps consider using a different license for Soot and related projects so this can be reused. E.g. this can be used here if ASL 2.0 is used: https://cwiki.apache.org/confluence/display/FLINK/Project+Ideas

**Comment by ericbodden** [comment]
Hello.

I am afraid that this is close to impossible as Soot is a code base which many people have submitted to, and all those people would have to agree to the change, some of which have even already passed away.

Best wishes,
Eric
