### ISSUE TITLE
AnnotationTag not supported?

### ISSUE THREAD

**Issue by csw244** [Sable/soot#458]
Hello, 

I have an analysis to check each element inside the method's annotation tag. When I try to compile the analysis, I get an error

```
for (int i = 0; i < annotation.getNumElems(); i++) {
					                              ^
  symbol:   method getNumElems()
  location: variable annotation of type AnnotationTag
/home/local/ANT/stepchoi/soot-analysis/src/main/java/soot-analysis/Main.java:154: error: cannot find symbol

if (annotation.getElemAt(i).toString().contains(methodMapping)) {
              ^
  symbol:   method getElemAt(int)
  location: variable annotation of type AnnotationTag
/home/local/ANT/stepchoi/soot-analysis/src/main/java/soot-analysis/Main.java:180: error: cannot find symbol

```

Is getElemAt() and getNumElems() for AnnotationTag not supported fully?

Thank you in advance. 
Stephanie

**Comment by Alexandre-Bartel** [comment]
Hi Stephanie,

Are you using the latest version of Soot? Method getNumElems() has been deprecated for a while and then removed in commit 27740c57942b316e4668df967da419d07ed12ed8. You should use the getElems() method instead.
