### ISSUE TITLE
java.lang.NullPointerException when ...

### ISSUE THREAD

**Issue by mojtaba-esk** [Sable/soot#461]
Hi would you please check this out?
Thank you.

Files used to reproduce: 
com.chatous.pointblank.apk
https://play.google.com/store/apps/details?id=com.chatous.pointblank

Soot version: trunk

Command line:
-android-jars /home/lroot/didfail/platforms -process-dir /home/lroot/didfail/cert/APK/com.chatous.pointblank.apk -cp /home/lroot/didfail/cert/transformApk/bin::/home/lroot/workspaces/didfail/soot/classes:/home/lroot/workspaces/didfail/soot/li

**Comment by Alexandre-Bartel** [comment]
Are you using the nightly build version? If not, could you download it from there https://ssebuild.cased.de/nightly/soot/ and try it again on your apk?
If you still get an exception, please post the full stack trace and send me the apk via email at alexandre.bartel@ec-spride.de

**Comment by mojtaba-esk** [comment]
Ok Thanks a lot, I will try the nightly version and let you know.

**Comment by StevenArzt** [comment]
With the latest nightly build, I cannot reproduce the any issue. A conversion dex -> dex (via internal Jimple representation) works perfectly fine.
