### ISSUE TITLE
 java.lang.Runnable and GallGraph update issue

### ISSUE THREAD

**Issue by zemisolsol** [Sable/soot#463]
When I ran into the following call invocation, I found there is an implicit call invocation issue.

"interfaceinvoke $r4.< java.util.concurrent.ExecutorService: java.util.concurrent.Future submit(java.lang.Runnable) >($r3);"

In this case, the callee of above unit should be like "void run()" method. However, soot did not find any edge. So I've found "void run()" edge according to $r3 class, then add it by using "Scene.v().getCallGraph().addEdge(newEdge)" code.

My question is that, after connecting edge what should I do to update CFG?

**Comment by ericbodden** [comment]
Hi.


> On 26.08.2015, at 09:02, zemisolsol <notifications@github.com> wrote:
> 
> When I ran into the following call invocation, I found there is an implicit call invocation issue.
> 
> 	• interfaceinvoke $r4.($r3);
> In this case, the callee of above unit should be like "void run()" method. However, soot did not find and edge. So I've found "void run()" edge according to $r3 class, then add it by using "Scene.v().getCallGraph().addEdge(newEdge)" code.

It might be more advisable to investigate why in your case the call-graph analysis is incomplete.

> My question is that, after connecting edge how can I do to update CFG?

Why would you like to update any CFG? A CFG contains intra-procedural control flow only.

Cheer,
Eric

**Comment by zemisolsol** [comment]
Hi,
I've solved this issue by adding submit()-run() edge into the soot framework.
Thank you!

Best regards,
zemisolsol
