### ISSUE TITLE
Plugin not installing OS X Eclipse Mars

### ISSUE THREAD

**Issue by miguelvelezmj25** [Sable/soot#471]
I am trying to install the plugin from http://sable.github.io/soot/eclipse/. These are the files that Eclipse tells me that are being installed
  /Applications/Eclipse.app/Contents/Eclipse/plugins/ca.mcgill.sable.soot_2.5.2.jar
  /Applications/Eclipse.app/Contents/Eclipse/features/ca.mcgill.sable.soot.feature_2.5.2
  /Applications/Eclipse.app/Contents/Eclipse/plugins/ca.mcgill.sable.soot.help_2.5.2.jar
  /Applications/Eclipse.app/Contents/Eclipse/plugins/ca.mcgill.sable.soot.lib_2.5.2

I also tried the "Simple Installation" section of the wiki, but it did not work either. 

Any advice?

**Comment by miguelvelezmj25** [comment]
Are there any required plugins?

**Comment by StevenArzt** [comment]
The Soot Eclipse plugin is quite old and from what I know, nobody has worked on it for quite some years now. Which feature of the plugin are you interested in? I might point you to other options that are more up-to-date if I know that.

**Comment by miguelvelezmj25** [comment]
I am interested in the call graph construction algorithms. CHA, RTA, and CTA.

Thanks.

**Comment by StevenArzt** [comment]
You easily try them out by running Soot from the command-line. For the results, you can either implement your own code to analyze and/or compare them, our you can use Soot's built-in dot writer to create a dot file which you can then dump into GraphViz. The latter is feasible for small programs. For large real-world programs, the callgraph is usually so large that you will have to filter or post-process it according to your concrete goals (that is, remove everything you're not interested in to not get lost in all the edges).

**Comment by miguelvelezmj25** [comment]
Great! Thanks for the advice.
