### ISSUE TITLE
Possibly outdated information in soot_in_eclipse_howto.html

### ISSUE THREAD

**Issue by domainexpert** [Sable/soot#474]
Rather than following the more complex procedure as indicated in the instruction in soot_in_eclipse_howto.html, to load Soot into Eclipse, one can instead do File ->
Import -> Existing Projects into Workspace -> Next -> input the root directory of your
soot source tree -> tick the project -> Finish.

Regards,
Andrew

**Comment by anddann** [comment]
Thx, unfortunately the eclipse plugin is outdated.
