### ISSUE TITLE
src/soot/toolkits/graph/BlockGraphConverter.java Incompatible to Java 6

### ISSUE THREAD

**Issue by domainexpert** [Sable/soot#477]
`src/soot/toolkits/graph/BlockGraphConverter.java` of 082e0b1e26d27471bd2831596f6786f59b79a359 made Java 6's `javac` throws 'Illegal start of expression.' The problem is that `javac` cannot parse `Collections.<Unit>emptyList()`. Following is how I patched my own clone.

```
diff --git a/src/soot/toolkits/graph/BlockGraphConverter.java b/src/soot/toolkits/graph/BlockGraphConverter.java
index 5f8b362..8c3d2be 100644
--- a/src/soot/toolkits/graph/BlockGraphConverter.java
+++ b/src/soot/toolkits/graph/BlockGraphConverter.java
@@ -194,6 +194,7 @@ class DummyBlock extends Block
 
     public Iterator<Unit> iterator()
     {
-        return (Collections.<Unit>emptyList()).iterator();
+       List<Unit> s = Collections.emptyList();
+        return s.iterator();
     }
 }
```

**Comment by StevenArzt** [comment]
We have a pull request for this, thanks for the code contribution. Let's move the discussion there. I'll close this issue report to avoid duplicates.
