### ISSUE TITLE
smali Libraries Incompatible to Java 6

### ISSUE THREAD

**Issue by domainexpert** [Sable/soot#478]
In 082e0b1e26d27471bd2831596f6786f59b79a359 the included `smali` libraries `dexlib2-2.0.7-dev.jar` and `util-2.0.7-dev.jar` have class files with version 51.0. For Soot's compatibility with Java 6 (in case someone other than me cares), they need to be replaced with version 50.0 classes built using JDK 6. The source of `smali` can be cloned from https://github.com/JesusFreke/smali and for me the compilation of `smali` went smoothly with JDK 6 with simply `gradle jar` (although I had to install `gradle` beforehand).

**Comment by StevenArzt** [comment]
Thank you for submitting a pull request for this. Let's keep the discussion about Java 6 compatibility centralized in that pull request. Therefore, I close this report.
