### ISSUE TITLE
CallGraph running time

### ISSUE THREAD

**Issue by miguelvelezmj25** [Sable/soot#479]
I am running the call graph example from the Survivor's Guide, which is very small. It takes 10 to 15 seconds for Soot to run and return the list of outgoing edges from a method. Is this the normal running time?

**Comment by domainexpert** [comment]
I'm currently looking into the Survivor's Guide as well, and I suppose you are talking about the incomplete snippet on Page 32, which lists incoming (not outgoing) edges to a method. My first guess is that Soot may have constructed a larger call graph whose most edges are not needed for your purpose. With the right setting, it could even generate the graph of JDK library. However, I think to answer your question one would probably need to have a look at your complete code.

**Comment by miguelvelezmj25** [comment]
This is the code that came with the Survivor's guide. I have not changed anything since I wanted to first understand how it works:

```
package dk.brics.soot.callgraphs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import soot.MethodOrMethodContext;
import soot.PackManager;
import soot.Scene;
import soot.SceneTransformer;
import soot.SootClass;
import soot.SootMethod;
import soot.Transform;
import soot.jimple.toolkits.callgraph.CHATransformer;
import soot.jimple.toolkits.callgraph.CallGraph;
import soot.jimple.toolkits.callgraph.Targets;

public class CallGraphExample
{	
	public static void main(String[] args) {
	   List<String> argsList = new ArrayList<String>(Arrays.asList(args));
	   argsList.addAll(Arrays.asList(new String[]{
			   "-w",
			   "-main-class",
			   "testers.CallGraphs",//main-class
			   "testers.CallGraphs",//argument classes
			   "testers.A"			//
	   }));
	

	   PackManager.v().getPack("wjtp").add(new Transform("wjtp.myTrans", new SceneTransformer() {

		@Override
		protected void internalTransform(String phaseName, Map options) {
		       CHATransformer.v().transform();
                       SootClass a = Scene.v().getSootClass("testers.A");

		       SootMethod src = Scene.v().getMainClass().getMethodByName("doStuff");
		       CallGraph cg = Scene.v().getCallGraph();

		       Iterator<MethodOrMethodContext> targets = new Targets(cg.edgesOutOf(src));
		       while (targets.hasNext()) {
		           SootMethod tgt = (SootMethod)targets.next();
		           System.out.println(src + " may call " + tgt);
		       }
		}
		   
	   }));

           args = argsList.toArray(new String[0]);
           
           soot.Main.main(args);
	}
}
```

When trying to run this code in Eclipse, Soot was complaining about the class path, so I added the following to my program arguments in my run configuration:

```
-cp .:/Users/miguelvelez/Documents/Programming/Soot/Projects/soot/classes:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/jce.jar
```

**Comment by domainexpert** [comment]
Actually I did not know that the Survivor's Guide came with sources as the link http://www.brics.dk/SootNote to the source provided in the document itself is broken, but I found the source in the soot source tree. Thanks!

Although I had to add JDK jar files path as well, I did not add them to the JVM using -cp, but instead to Soot using -soot-class-path. First, it did not run with the default memory size provided to the JVM, but it worked after I increased the maximum JVM memory to 2GB, which is all of the RAM in my old MacBook. For me the run time was 45 seconds producing 173349 edges (as returned by cg.size()). If I understand correctly, the call graph is constructed from a number of entry point methods. The number of methods returned by cg.sourceMethods() was 9696, although I am not sure if this was the number of entry point methods. The methods of cg.sourceMethods() not only include testers.CallGraph.main(), but also JDK methods that are not reachable from it in an obvious way. I suppose it may be worth looking into Soot's -exclude option to try to exclude these extra methods.

**Comment by domainexpert** [comment]
Using the Soot option `-no-bodies-for-excluded`, the number edges decreased to just 219 with only 29 source methods. The example finished in only 7 seconds. As far as I know, this option avoids the loading of method bodies from excluded code (JDK library, for example, is by default excluded, and need to be explicitly included using `-include` option).

**Comment by miguelvelezmj25** [comment]
I am not sure why there is this call ```CHATransformer.v().transform();``` inside the ```internalTransform``` method. When I call the ```cg.size()``` before and after that call, there is an increase in the size of the edges. However, if I do not make that function call, I still get information about the call graph. I believe that the CHA algorithm is being executed twice, and that is why it is taking so long.

**Comment by domainexpert** [comment]
I tried commenting out that call as well and even with `-no-bodies-for-excluded` option `cg.size()` decreased from 216 to 144 for me. Further investigations by comparing method signatures in the edges revealed that the sets of edges are just the same! 

I also tried to detect edge duplications within the callgraphs themselves. As a result, there are 20 to 36 method signature-to-method signature edge duplications among the 216 (I have to put 20-36 range as the number varies from run to run--I don't know why, and I know the numbers don't tally). The same method signature to method signature duplication is about 4-5 among the 144.

If we look at the example, `main` mehod, it provides `-w` (whole program) option to `soot.Main.main()` which should probably have already triggered the call graph generation (the one with 144 edges) anyway even without the `CHATransformer.v().transform()` call. Without `-w` no call graph was generated, even if I put back `CHATransformer.v().transform()`. So to me `CHATransformer.v().transform()` seems unnecessary, but within the context of the Survivor's Guide, perhaps it has some instructional value.

**Comment by miguelvelezmj25** [comment]
To get a call graph, we have to run the program in ```Whole Program Mode```. From the guide:

```
When conducting an inter-procedural analysis in Soot we need to put Soot into
Whole-program mode and we do that by specifying the option -w to Soot. In this 
mode Soot includes three other packs in the execution cycle: cg (call-graph generation), 
wjtp (whole Jimple transformation pack, and wjap (whole Jimple annotation pack).
```

By playing with the tutorial, if you remove all of this code
```
PackManager.v().getPack("wjtp").add(new Transform("wjtp.myTrans", new SceneTransformer() {

        @Override
        protected void internalTransform(String phaseName, Map options) {
               CHATransformer.v().transform();
                       SootClass a = Scene.v().getSootClass("testers.A");

               SootMethod src = Scene.v().getMainClass().getMethodByName("doStuff");
               CallGraph cg = Scene.v().getCallGraph();

               Iterator<MethodOrMethodContext> targets = new Targets(cg.edgesOutOf(src));
               while (targets.hasNext()) {
                   SootMethod tgt = (SootMethod)targets.next();
                   System.out.println(src + " may call " + tgt);
               }
        }

       }));
```

The CHA algorithm executes. 

```
The simplest call graph is obtained through Class Hierarchy Analysis (CHA), 
for which no setup is necessary.
```

If you remove the ```-w``` option, CHA is not executed. 

Maybe they changed how the CHA algorithm is executed.

**Comment by StevenArzt** [comment]
You don't have to call the CHA transformer on your own in the current version of Soot. All you need to do is to enable whole-program mode and place your code that relies on the callgraph into one of the whole-program packs such as wjtp. In the code above, just remove the call to the transformer and the rest of the code should still execute all fine.

The no-bodies-for-excluded option prevents Soot from loading the method bodies of excluded classes, i.e., library classes. A library class is everything that is on the Soot classpath, but not inside the process directory (plus a few more complicated things, but let's keep it simple for now). Usually, that will be classes from the JDK or the Android SDK. Unless you really need a sound callgraph including callbacks from the JDK into your application code or want to analyze the JDK itself, it's usually unnecessary to load the JDK. Respectively, no-bodies-for-excluded is a good choice to start with for most people. Not loading the bodies of library classes will save you quite a bit of time and memory, even aside from the callgraph construction.

By default, Soot uses CHA for constructing callgraphs. This callgraph algorithm is fast, but rather imprecise. If your clalgraph gets too big with too many spurious edges, you may want to chose a more precise algorithm such as SPARK. SPARK will take longer to compute than CHA, but you will usually get way fewer edges. if you have an analysis that depends on the callgraph, spending more time on a more precise callgraph may very well pay off since you save lots of time later on as your analysis doesn't need to follow all the spurious callgraph edges.
