### ISSUE TITLE
Local PointsTo analysis

### ISSUE THREAD

**Issue by martinschaef** [Sable/soot#480]
Not sure if you do Questions on the Issue Tracker  (apologies if this is not the case).
Here is my question:
I'm doing a shimple to SMT translation. Given the programs that I analyze and the performance requirements, a whole program analysis is not feasible. However, I want a light points-to analysis. E.g., given the following program:

    public class TranslationTest01 {
      public void virtualCalls(int i) {
         Object o;
         if (i>0) o = new TranslationTest01();
         else o = new String();
         o.toString();
      }
     @Override
     public String toString() { return null;}
    }
 
I want to know that o.toString() either refers to String.toString() or TranslationTest01.toString() (which overloads toString).

Is there something out-of-the-box that I could apply to the (Shimple)Body to get this information?

Thanks.

**Comment by ericbodden** [comment]
Martin, there is LocalMayAliasAnalysis. This is designed for Jimple, but it might also work on Shimple if you do minor adjustments:
https://ssebuild.cased.de/nightly/soot/javadoc/soot/jimple/toolkits/pointer/LocalMayAliasAnalysis.html

**Comment by martinschaef** [comment]
Thanks!
