### ISSUE TITLE
java.util.ConcurrentModificationException when decompiling

### ISSUE THREAD

**Issue by ahtokca** [Sable/soot#483]
Steps to reproduce:
1.)  get an android dex with guardit obfuscated code
2.) run the tool

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:

<pre>-cp d:\ADT\sdk\platforms\android-22\android.jar;classes-dex2jar.jar -f dava xxxxxx.xxxxax</pre>

Max Memory:

<pre>1795MB</pre>

Stack trace:

<pre>java.util.ConcurrentModificationException
    at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:485)
    at soot.dava.toolkits.base.finders.ExceptionFinder.preprocess(ExceptionFinder.java:90)
    at soot.dava.DavaBody.&#60;init&#62;(DavaBody.java:321)
    at soot.dava.Dava.newBody(Dava.java:84)
    at soot.PackManager.runBodyPacks(PackManager.java:948)
    at soot.PackManager.runBodyPacks(PackManager.java:609)
    at soot.PackManager.runBodyPacks(PackManager.java:508)
    at soot.PackManager.runPacksNormally(PackManager.java:485)
    at soot.PackManager.runPacks(PackManager.java:392)
    at soot.Main.run(Main.java:271)
    at soot.Main.main(Main.java:147)
</pre>

**Comment by StevenArzt** [comment]
Can you please provide a JAR file with which we can reproduce the issue? That's much easier than having to apply the obfuscator on our own.

**Comment by elephantom** [comment]
I am having this issue as well (working with a "plain" apk, not obfuscated). Do you have any insight into how to solve this? Thanks!

**Comment by StevenArzt** [comment]
@elephantom Please send the APK file to Steven.Arzt@cased.de. Without the inputs on which the problem occurs, it's hard to say what goes wrong.

**Comment by elephantom** [comment]
Steven -- here's the APK on f-droid: https://f-droid.org/repository/browse/?fdfilter=mBrowser&fdid=am.zoom.mbrowser
The link to download it is further down the page, but I can email it to you if that's better -- just let me know.

To run soot, I run the following command after compiling the soot jar. 

java AndroidInstrument -android-jars /my/home/dir/etc/ -allow-phantom-refs -p db.transformations enabled:true -process-dir apks/am.zoom.mbrowser_12.apk

I have modified soot, but it's not anything that should affect this (I'm just outputting ASTs in the Dava stage a little differently)

Thanks for looking in to this!

**Comment by StevenArzt** [comment]
I can't reproduce the problem with plain Soot. Here are my Soot command line options (launching Soot from Eclipse in Debug mode):

```
-process-dir "D:\Arbeit\APKs\am.zoom.mbrowser_12.apk" -android-jars "D:\Tools\adt-bundle-windows-x86_64-20140321\sdk\platforms" -allow-phantom-refs -output-format dex -src-prec apk -force-overwrite -validate  -p db.transformations enabled:true
```

This completes just fine.
