### ISSUE TITLE
resolving level Java7 on Linux

### ISSUE THREAD

**Issue by martinschaef** [Sable/soot#492]
With the latest nightly build (Oct 27, 2015), I get the following exception on Linux for Java 7. I do not get this exception on Mac or on Linux with Java8. With this nightly build I also had a concurrent modification exception as mentioned in Issue #483 when running soot on Ant (using the class files).

soottocfg.test.callgraph_test.CallGraphTest > test_cha[0: check (SSLSocketExampleA.java)] FAILED
    java.lang.RuntimeException: This operation requires resolving level SIGNATURES but java.lang.ThreadGroup is at resolving level DANGLING
    If you are extending Soot, try to add the following call before calling soot.Main.main(..):
    Scene.v().addBasicClass(java.lang.ThreadGroup,SIGNATURES);
    Otherwise, try whole-program mode (-w).
        at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:152)
        at soot.SootClass.checkLevel(SootClass.java:138)
        at soot.SootClass.declaresMethod(SootClass.java:393)
        at soot.Scene.grabMethod(Scene.java:629)
        at soot.Scene.containsMethod(Scene.java:635)
        at soot.EntryPoints.addMethod(EntryPoints.java:58)
        at soot.EntryPoints.implicit(EntryPoints.java:78)
        at soot.EntryPoints.all(EntryPoints.java:99)

**Comment by martinschaef** [comment]
Actually, the concurrent modification exception happens when I iterate over all classes in Scene.v().getClasses(), but it didn't happen before I updated soot.

**Comment by Alexandre-Bartel** [comment]
Thanks for reporting this! Have you tried "whole program mode" and/or "addBasicClass SIGNATURES" as suggested by the error message? 

It seems that you have two different issues. If the stack trace you have for the concurrent modification exception is not related to issue #483, please open a new issue.

**Comment by martinschaef** [comment]
Yes, both fix the problem (I use addBasicClass for now). However, the exception was not there in earlier versions and it only occurs in one of my four CI configurations (linux + java 7), so I was wondering if it is a bug somewhere in soot.

**Comment by anddann** [comment]
The release 4.0 works on java 7 and 8
