### ISSUE TITLE
PSF file used to build Soot in Eclipse gives an error

### ISSUE THREAD

**Issue by elephantom** [Sable/soot#493]
I am trying to build Soot in Eclipse using the directions here: https://github.com/Sable/soot/wiki/Building-Soot-with-Eclipse. However, soot.psf gives an error when I try to load it. The error is: 

"The following errors occurred while importing projects. Some projects may not be loaded.
  Projects for repository type org.eclipse.egit.core.GitProvider could not be loaded as the type could not be found."

How can I fix this? Or, is there a better way to build soot?

**Comment by StevenArzt** [comment]
Have you installed the GIT plugin for Eclipse? This may be the reason for the missing class.

If you just want to build Soot, you can also use the ant build script that we ship with it.

**Comment by elephantom** [comment]
Hm, progress.... installing the git plugin for Eclipse fixed the .psf issue, thank you! However, it was unable to build because of a null pointer exception in heros.

However, I DID get soot to build with ant. I don't understand what is being produced with this command, though. Where are the output files? Is there a resulting jar file? If not, is there a way to make a resulting jar file..?

Thanks in advance for the help/clarification!

**Comment by StevenArzt** [comment]
Ant has a target "fulljar" which will produce a file called "soot-trunk.jar" in the "lib" directory. This is a full build of the whole Soot framework.

I'm not sure what you mean with the NullPointerException. An exception is a runtime failure and should not happen at compile time. When exactly does it happen? Do you have a stack trace?

**Comment by anddann** [comment]
Please use the maven pom.xml to build soot.
