### ISSUE TITLE
double/float constants handled incorrectly when going from dex to jimple

### ISSUE THREAD

**Issue by madberries** [Sable/soot#496]
Consider the following example (see dex file http://web.mit.edu/jordane/www/failing.dex for example)...

    public double fail_1(double[] a) {
        a[0] = Double.NaN;
        return a[0];
    }

Soot will incorrectly add a long2double cast on a wide const that was never a long in the first place.  This will result in semantically incorrect code.  Essentially any non-zero value would be incorrect.  The double constant will become the double equivalent of the long bits (represented in IEEE-754 form).

**Comment by madberries** [comment]
Note, that the problem seems to go away if the constant were store away in a local, such as...

public double fail_1(double[] a) {
    double d = Double.NaN;
    a[0] = d;
    return d;
}

**Comment by Alexandre-Bartel** [comment]
Thanks for reporting this! It has been fixed with 6c2b781cd43a10f91c155999eb7bb1b1deb8ab43.
