### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when ...

### ISSUE THREAD

**Issue by winsun** [Sable/soot#503]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-d ./apk/out/ -android-jars /Users/winsunxu/GitHub/android-platforms -allow-phantom-refs -src-prec apk -ire -f J -process-dir ./apk/alipay.apk</pre>

Max Memory:
<pre>1360MB</pre>

Stack trace:
<pre>java.lang.ArrayIndexOutOfBoundsException: 7
	at soot.dexpler.DexBody.getRegisterLocal(DexBody.java:308)
	at soot.dexpler.instructions.ArrayLengthInstruction.jimplify(ArrayLengthInstruction.java:56)
	at soot.dexpler.DexBody.jimplify(DexBody.java:434)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1160)
	at soot.PackManager.runPacksNormally(PackManager.java:459)
	at soot.PackManager.runPacks(PackManager.java:392)
	at soot.Main.run(Main.java:271)
	at soot.Main.main(Main.java:147)
</pre>

**Comment by Alexandre-Bartel** [comment]
Thank you for reporting this. Could you send the apk to alexandre.bartel@ec-spride.de?

**Comment by 2048li** [comment]
I have the same problem. Have you solved it? Thanks.

**Comment by MarcMil** [comment]
Did you send the APK to Alexandre?
It's hard to solve problems if we are not able to reproduce the issues…
The best thing is to upload them somewhere where they are stored for a long term, available to anyone. But if a developer is offering his e-mail address like here, you can also mail them directly. Until that is being done, there is not much we can do.

**Comment by StevenArzt** [comment]
@Alexandre-Bartel @winsun  What's the status of this issue?

**Comment by Alexandre-Bartel** [comment]
Still waiting for an apk.

**Comment by 2048li** [comment]
Sorry for the late to reply. I encountered that "out of bound" problem just one time, and then I could not recur it, but the "classnotfoundexception" problem.

**Comment by 2048li** [comment]
I found the running record,and I will send you later.Thanks!

**Comment by Alexandre-Bartel** [comment]
@2048li Thanks for the apk. Running Soot on it does not trigger an exception on my side. Have you tried with the latest Soot version? You can get it there: https://ssebuild.cased.de/nightly/soot/lib/soot-trunk.jar

**Comment by 2048li** [comment]
When I use the new version of soot-trunk.jar, It shows "soot.sootresolver$sootclassnotfoundexception".:(

**Comment by Alexandre-Bartel** [comment]
What is the command line you use to launch Soot? What is the full stack trace and exception message?

**Comment by 2048li** [comment]
The command I used is "  java -cp soot-trunk.jar:AXMLPrinter2.jar:baksmali-2.0.3.jar soot.Main -d outdot -ire -android-jars . -f J -process-dir 360security.apk "
and the exception message is:
"
Soot started on Sat Mar 05 20:21:50 EST 2016
soot.SootResolver$SootClassNotFoundException: couldn't find class: com.qihoo.security.nettraffic.NetTrafficAlertDialog$1 (is your soot-class-path set properly?)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:228)
    at soot.SootResolver.bringToSignatures(SootResolver.java:266)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
    at soot.SootResolver.resolveClass(SootResolver.java:131)
    at soot.Scene.loadClass(Scene.java:725)
    at soot.Scene.loadClassAndSupport(Scene.java:710)
    at soot.Scene.loadNecessaryClasses(Scene.java:1448)
    at soot.Main.run(Main.java:243)
    at soot.Main.main(Main.java:147)


Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://ssebuild.cased.de/nightly/soot/doc/soot_options.htm

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/Sable/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
    https://github.com/Sable/soot/issues/new?title=soot.SootResolver%24SootClassNotFoundException+when+...&body=Steps+to+reproduce%3A%0A1.%29+...%0A%0AFiles+used+to+reproduce%3A+%0A...%0A%0ASoot+version%3A+%3Cpre%3Etrunk%3C%2Fpre%3E%0A%0ACommand+line%3A%0A%3Cpre%3E-d+outdot+-ire+-android-jars+.+-f+J+-process-dir+360security.apk%3C%2Fpre%3E%0A%0AMax+Memory%3A%0A%3Cpre%3E1769MB%3C%2Fpre%3E%0A%0AStack+trace%3A%0A%3Cpre%3Esoot.SootResolver%24SootClassNotFoundException%3A+couldn%26%2339%3Bt+find+class%3A+com.qihoo.security.nettraffic.NetTrafficAlertDialog%241+%28is+your+soot-class-path+set+properly%3F%29%0A%09at+soot.SootResolver.bringToHierarchy%28SootResolver.java%3A228%29%0A%09at+soot.SootResolver.bringToSignatures%28SootResolver.java%3A266%29%0A%09at+soot.SootResolver.processResolveWorklist%28SootResolver.java%3A170%29%0A%09at+soot.SootResolver.resolveClass%28SootResolver.java%3A131%29%0A%09at+soot.Scene.loadClass%28Scene.java%3A725%29%0A%09at+soot.Scene.loadClassAndSupport%28Scene.java%3A710%29%0A%09at+soot.Scene.loadNecessaryClasses%28Scene.java%3A1448%29%0A%09at+soot.Main.run%28Main.java%3A243%29%0A%09at+soot.Main.main%28Main.java%3A147%29%0A%3C%2Fpre%3E
    Please be as precise as possible when giving us
    information on how to reproduce the problem. Thanks!
"

Thanks!
-shentanli

**Comment by Alexandre-Bartel** [comment]
Adding option -allow-phantom-refs should enable you to analyze the app with Soot.

**Comment by 2048li** [comment]
Yeah!I have tried it and got the output. The output is the jimple lanaguage.
