### ISSUE TITLE
JLeExpr makeBafInst throw RuntimeException

### ISSUE THREAD

**Issue by martinschaef** [Sable/soot#509]
Why does JLeExpr.makeBafInst throw a RuntimeException?

https://github.com/Sable/soot/blob/efacd2bbc470c15c68ccc5c0506dc0b25864d775/src/soot/jimple/internal/JLeExpr.java

What is the right way to use <= when modifying a class file?

**Comment by StevenArzt** [comment]
Do you have a Soot input that actually triggers this exception? It has never surfaced so far, at least from what I know. Probably that expression is not used during the Jimple -> baf translation.

**Comment by martinschaef** [comment]
Yes ... I'm adding stmts to guard array access using something like:

    Expr compare = Jimple.v().newLtExpr(e.getIndex(), len);

and then I'm writing stuff out using the snippet from your wiki:


		// write the class to a file
		try (OutputStream streamOut = new JasminOutputStream(new FileOutputStream(fileName));
				PrintWriter writerOut = new PrintWriter(new OutputStreamWriter(streamOut, "UTF-8"));) {
			AbstractJasminClass jasminClass = new soot.baf.JasminClass(sClass);
			jasminClass.print(writerOut);
			writerOut.flush();
		} catch (FileNotFoundException e) {

which triggers an exception

java.lang.RuntimeException: unsupported conversion: i0 < $helper0
	at soot.jimple.internal.JLtExpr.makeBafInst(JLtExpr.java:42)
	at soot.jimple.internal.AbstractJimpleIntBinopExpr.convertToBaf(AbstractJimpleIntBinopExpr.java:53)
	at soot.jimple.internal.JAssignStmt$1.caseLocal(JAssignStmt.java:317)
	at soot.jimple.internal.JimpleLocal.apply(JimpleLocal.java:104)
	at soot.jimple.internal.JAssignStmt.convertToBaf(JAssignStmt.java:290)
	at soot.baf.BafBody.<init>(BafBody.java:92)
	at soot.baf.Baf.newBody(Baf.java:560)

**Comment by martinschaef** [comment]
May bad ... 

    AbstractJasminClass jasminClass = new soot.baf.JasminClass(sClass);

should have been

    AbstractJasminClass jasminClass = new soot.jimple.JasminClass(sClass);

... then it works.
