### ISSUE TITLE
Can't find the jar file to run the command line 

### ISSUE THREAD

**Issue by michaelcourcy** [Sable/soot#518]
Hi 

I start to experiment soot and I tried to download the jar files to run soot in command line. 

In this wiki page : https://github.com/Sable/soot/wiki/Running-Soot the link http://www.sable.mcgill.ca/soot/soot_download.html seems to be broken it's redirected to http://sable.github.io/soot/.

in this wiki page : https://github.com/Sable/soot/wiki/Introduction:-Soot-as-a-command-line-tool I get to the release page  I download the 2.5.0 package where I could not find any soot-x.y.z.jar inside.

Did I missed something ? 

Thanks

**Comment by michaelcourcy** [comment]
I found the right link was 
https://github.com/Sable/soot/blob/develop/soot_download.html
This link point to all the useful download.

I correct the wiki thus I close the issue.

**Comment by StevenArzt** [comment]
In general, I recommend using the nightly builds as the 2.5 release version is pretty outdated by now. You can find them at https://ssebuild.cased.de/nightly/soot/.

**Comment by michaelcourcy** [comment]
Ok thanks now I can see this link is actually on the readme.md of the project. 
I'm going to update the wiki as well.
