### ISSUE TITLE
Return type of bootstrap method is not required by JVMS to be java.lang.invoke.CallSite

### ISSUE THREAD

**Issue by Maccimo** [Sable/soot#523]
At https://github.com/Sable/soot/blob/master/src/soot/jimple/internal/JDynamicInvokeExpr.java#L64 there is check that return type of bootstrap method is `java.lang.invoke.CallSite`.

According to the JVMS8  [&sect;invokedynamic](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html#jvms-6.5.invokedynamic) this is not correct:

> the bootstrap method is invoked as if by execution of an invokevirtual instruction (§invokevirtual) that contains a run-time constant pool index to a symbolic reference R where: 
> ...
> The symbolic reference R describes a method which is signature polymorphic (§2.9). Due to the operation of invokevirtual on a signature polymorphic method called invoke, the type descriptor of the receiving method handle (representing the bootstrap method) need not be semantically equal to the method descriptor specified by R. **For example, the first parameter type specified by R could be Object instead of java.lang.invoke.MethodHandles.Lookup, and the return type specified by R could be Object instead of java.lang.invoke.CallSite.**

**Comment by mbenz89** [comment]
Changed a long time ago.
