### ISSUE TITLE
Reset ClassPath for Android, A Bug?

### ISSUE THREAD

**Issue by fripSide** [Sable/soot#524]
After setting the classpath and load all classes, I use the Scene.v().setClassPath to change the sootclasspath to load other Android apk files. But it failed to load the new apk in the path. Is it a Bug?
After reading the source code, I found that setClassPath will call the SourceLoader.v().invalidateClassPath(). But the invalidateClassPath does not reset the dexClassIndex to null. So that DexClassProvider.find() will not call the buildDexIndex(https://github.com/Sable/soot/blob/a61d8114ad32f0022240fca97e850aec9f0aea3a/src/soot/DexClassProvider.java#L54) to load  the new apk files in the new classpath.

To fix this problem, please add SourceLocator.v().setDexClassIndex(null) in SourceLocator.v().invalidateClassPath.
(https://github.com/Sable/soot/blob/a61d8114ad32f0022240fca97e850aec9f0aea3a/src/soot/SourceLocator.java#L163)

**Comment by StevenArzt** [comment]
I'm not sure why you need to change the classpath. The classpath can take an arbitrary number of elements if you want to merge them into one single scene. Furthermore, your questions sound a bit like the APK file should be loaded unconditionally which would make it a better match for the process-dir rather than the classpath.

**Comment by fripSide** [comment]
I need to use flowdroid to load different apk files in many times to analysis the ICC between any app. I don't want to load all of them at once so I have to change the process-dir to contain another apk. But if the Scene.sootclasspath is not null. It will not add the process-dir to the classpath. And the new apk files will not be add to Scene.classes as the reason above.

**Comment by StevenArzt** [comment]
If you don't want to load all the APK files at once, would it be an option for you to completely reset Soot between the runs? In that scenario, you would first run Soot and FlowDroid on the first APK, save your results, then reset it and run it again on the second APK. You would then only have a single APK in your scene concurrently. If you want to load other APKs on demand, you're just shifting the effort of loading them till later, but the end result doesn't differ from loading them all at once in the beginning. The only reason I can think of to delay the loading is if you get additional information as to what to load while analyzing the first APKs. Is this the case?

I changed the code according to your request which makes sense in a way, bur I expect you to run into to other issues when switching the classpath at runtime.

**Comment by fripSide** [comment]
Thank you! I see. 
I don't use the loadNecessaryClass to load all the class at once but use the SourceLoader.v(). getClassesUnder() to load a part of classes of the apks. So I can divide the apk sources into SDK' classes and app's own classes and combine the sources of other apks. I need to append classes to Scene.v().classes instead of use G.v().reset to reload.
