### ISSUE TITLE
java.lang.CharSequence tries to load with double fileSuffix() in ZipFilePart

### ISSUE THREAD

**Issue by derdj** [Sable/soot#525]
I got an error that java.lang.CharSequence can't be loaded when analysing a java class.
After debugging to dig for reasons i found that soot tries to load it as  "java.lang.CharSequence.class.class" from the jar file rt.jar.

The reason for this issue seemingly are the lines 76 & 83 in class
soot/generated/jastadd/soot/JastAddJ/ZipFilePart.java

name = name + fileSuffix();
relativeName = name + fileSuffix();   --> java.lang.CharSequence.class.class

**Comment by anddann** [comment]
JastAdd is outdated, please use the ASM bytecode frontend
