### ISSUE TITLE
A visual debugger for static analyses

### ISSUE THREAD

**Issue by malaverdiere** [Sable/soot#53]
(copy-pasted from GSOC application)
Explanations:
In the past year, we have developed Heros, a plugin into Soot which allows for inter-procedural data-flow analyses. While the framework eases the definition of such analyses, implementing the analyses correctly is still a tricky task. Hence, we are looking for a visualization that would aid analysis designers in depicting the analysis results by overlaying them over the analyzed program. Thus, the visualization plays the role of a debugger for static analyses. A visual debugger should be integrated into Eclipse. We have already implemented basic support to run Soot and Heros through Eclipse run configuration. Therefore  a student could focus on the visualization part and on extracting necessary analysis information from Heros.
Note: previously we also proposed this topic as a thesis topic; you can find the writeup here

Expected Results:
A debugger that visualizes data flows facts overlayed over the analyzed program’s code, as the data are computed by the Heros solver within Soot.

Knowledge prerequisite:
Good Java programming skills; knowledge about Debuggers and/or Eclipse are helpful

**Comment by ericbodden** [comment]
We actually have this by now:
https://blogs.uni-paderborn.de/sse/tools/visuflow-debugging-static-analysis/
Beta testers welcome :-)
