### ISSUE TITLE
DeadAssignmentEliminator removes NopStmts

### ISSUE THREAD

**Issue by ChristianWulf** [Sable/soot#530]
Currently, the DeadAssignmentEliminator also removes NopStmts although we have a NopEliminator for this task. I use the NopStmts to encode higher-level structures, such as for-loop constructs. Thus, I do not want them to be removed.

See [DeadAssignmentEliminator.java](/Sable/soot/blob/develop/src/soot/jimple/toolkits/scalar/DeadAssignmentEliminator.java#L122) and [NopEliminator.java](/Sable/soot/blob/develop/src/soot/jimple/toolkits/scalar/NopEliminator.java#L69).

**Comment by StevenArzt** [comment]
The easiest way to go about this would be to add an option to the DeadAssignmentEliminator that defines whether nop statements shall be eliminated or not. To ensure backwards compatibility, this option should be enabled (do remove nop statements) by default. You can then simply disable it.

Can you implement this and open a pull request?

**Comment by ChristianWulf** [comment]
Sure. Give me some days since I am currently busy.

**Comment by anddann** [comment]
Outdated
