### ISSUE TITLE
Problem in Instrumenting apk with soot

### ISSUE THREAD

**Issue by jyotigajrani** [Sable/soot#538]
It is related to issue: https://github.com/Sable/soot/issues/230

I am using following commands to run the same:

1. javac -cp "soot-trunk.jar" AndroidInstrument.java

2. java -cp soot-trunk.jar soot.Main -android-jars /home/jyoti/Android/adt-bundle-linux-x86_64-20140702/sdk/platforms -cp . -pp AndroidInstrument -process-dir Onlytelephony.apk

But I get following exception:

soot.SootResolver$SootClassNotFoundException: couldn't find class: soot.Local (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:228)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:173)
	at soot.SootResolver.resolveClass(SootResolver.java:131)
	at soot.Scene.loadClass(Scene.java:725)
	at soot.Scene.loadClassAndSupport(Scene.java:710)
	at soot.Scene.loadNecessaryClass(Scene.java:1425)
	at soot.Scene.loadNecessaryClasses(Scene.java:1436)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)

my CLASSPATH is set in .bashrc as:

export CLASSPATH=$CLASPATH:/usr/lib/jvm/java-7-oracle:/usr/lib/jvm/java-7-openjdk-amd64/:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javawas.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/home/jyoti/Android/adt-bundle-linux-x86_64-20140702/sdk/platforms:/home/jyoti/PHD/IccTA/soot-infoflow-android-iccta-master/libs/

So as far as I think, I have added all jars in classpath and using -pp option in second command. I think my commands are missing something or have some mistake.
May you please help by telling what should be exact commands.

I will be very helpful to you. I am struggling for this from 2-3 days.

**Comment by Alexandre-Bartel** [comment]
Could you describe how you solved your problem? It may be useful to others.
