### ISSUE TITLE
Can I use RTA algorithm for a CallGraph construction without SPARK?

### ISSUE THREAD

**Issue by vitaliiavdiienko** [Sable/soot#541]
Hi all,

i know that there is a possibility to use RTA and VTA for a CallGaph construction but only inside of SPARK. 

But for those who don't want to use SPARK (due to time constraints and missing edges to AndroidSDK) does to possible to change the default CHA for the CallGraph to RTA or VTA?

Thank you in advance.

Best Regards,
Vitalii

**Comment by patricklam** [comment]
Although there is no conceptual reason you wouldn't be able to use RTA and
VTA without SPARK, I do not believe that these are currently implemented
independent of SPARK. So you're stuck with using SPARK if you want anything
more than CHA. Sorry!

(A lot of the time, by the way, is spent constructing the IR for all of the
bytecode, not in SPARK itself. It would be great to have faster bytecode
construction.)
