### ISSUE TITLE
SootMethod.getSubSignature: Created method signatures are ambiguous

### ISSUE THREAD

**Issue by jpstotz** [Sable/soot#551]
The current implementation of the "subSignature" of a SootMethod creates ambiguous signature strings. This is a big problem as the subsignature is used for checking if a class contains multiple methods with the same signature.

The main problem is that there is no way to distinguish between a primitive type like "int" and a class in the default package named "int". Soot mixes up the type int and the class int and totally gets confused.
This scenario is not a theoretical construct - an app with a class named "int" has already been observed in reality.

**Comment by StevenArzt** [comment]
Theoretically, there should be a difference between the IntType class modeling a primitive int and the RefType class modeling some class with whatever name. Why this doesn't work out with this one example is something I need to look into.

**Comment by MarcMil** [comment]
With the newest commits (8275282dec8c3dbc72307f25469e75ff4ddfa9f6) this problem should be fixed by now.
