### ISSUE TITLE
Data race at DefaultShimpleFactory

### ISSUE THREAD

**Issue by scg03** [Sable/soot#552]
For example, when invoking

ShimpleTransformer.v().transform();
PackManager.v().runBodyPacks();

then DefaultShimpleFactory.setBody(Body) at the following context will cause data race.

	DefaultShimpleFactory.setBody(Body) line: 73	
	ShimpleBodyBuilder.<init>(ShimpleBody) line: 82	
	ShimpleBody.<init>(Body, Map) line: 97	
	Shimple.newBody(Body) line: 104	
	ShimpleMethodSource.getBody(SootMethod, String) line: 36	
	SootMethod.getBodyFromMethodSource(String) line: 91	
	SootMethod.retrieveActiveBody() line: 322	
	PackManager.runBodyPacks(SootClass) line: 950	
	PackManager.access$0(PackManager, SootClass) line: 875	
	PackManager$1.run() line: 625	
	CountingThreadPoolExecutor(ThreadPoolExecutor).runWorker(ThreadPoolExecutor$Worker) line: 1145	
	ThreadPoolExecutor$Worker.run() line: 615 [local variables unavailable]	
	Thread.run() line: 744

**Comment by StevenArzt** [comment]
Is this issue resolved now with the merged pull request?

**Comment by scg03** [comment]
Yes. Thanks.
