### ISSUE TITLE
commit d27ca5ba78cbd48e4933278dfe9290343ac2181f caused uninitialized local var

### ISSUE THREAD

**Issue by scg03** [Sable/soot#553]
The commit d27ca5ba78cbd48e4933278dfe9290343ac2181f "also perform copy propagation by default" generate code with uninitialized local var.

**Comment by StevenArzt** [comment]
Can you please provide an example on which the problem can be reproduced?
On Mar 11, 2016 1:49 AM, Chenguang <notifications@github.com> wrote:The commit d27ca5b "also perform copy propagation by default" generate code with uninitialized local var.

**Comment by StevenArzt** [comment]
Since there has not been any activity in this thread for more than a month, I close it. If the problem still persists, please feel free to re-open it.
