### ISSUE TITLE
Question: Disable bytecode optimizations

### ISSUE THREAD

**Issue by martinschaef** [Sable/soot#558]
Hi,
I have a toy example: 

```java
	@SuppressWarnings("null")
	public void main(String[] args) {
		String s = null;
		s.length();
	}
```

However, Jimple replaces this implicit (but inevitable) NullpointException by the explicit throw below:

```
    public void main(java.lang.String[])
    {
        Main r0;
        java.lang.String[] r1;
        java.lang.NullPointerException r2;
        r0 := @this: Main;
        r1 := @parameter0: java.lang.String[];
        r2 = new java.lang.NullPointerException;
        specialinvoke r2.<java.lang.NullPointerException: void <init>(java.lang.String)>("This statement would have triggered an Exception: $stack3 = virtualinvoke s.<java.lang.String: int length()>()");
        throw r2;
    }
```

Is there a way to prevent Soot from doing this transformation? It breaks some of my toy examples in a demo of a static analysis tool.

**Comment by StevenArzt** [comment]
The root problem why we introduced these transformations is that Soot's type assigner requires all variables to have proper uses. If there is a null variable on which a method is called, this will lead to null_type being assigned to that local as there is no real type information the algorithm could use. If other algorithms such as callgraph construction encounter such a type, this can lead to follow-up errors. We can introduce an option to not generate the explicit exception, but there's a high chance that you will run into a number of issues without it.

**Comment by ericbodden** [comment]
Still there might be a possibility to disable this for Martins purposes. I don’t know which pack is responsible for the transformation, though.

Cheers,
Eric

**Comment by StevenArzt** [comment]
There is now an option ignore_nullpointer_dereferences in the type assigner (jb.tr). If this option is enabled, it leaves the nullpointer accesses as they are maps the respective base objects' types to null_type. As I said, use at your own risk.

**Comment by martinschaef** [comment]
This one works for me:
```java
    soot.options.Options sootOpt = soot.options.Options.v();
    sootOpt.setPhaseOption("jop.cpf", "enabled:false");
```
