### ISSUE TITLE
uri in "building soot with intellj" doc did not work

### ISSUE THREAD

**Issue by 2048li** [Sable/soot#564]
hi,
The heros.jar and jasminclasses.jar, which said avaliable from that site, cannot be got.
Any other sites?or Should I just import those two projects from github?
Thanks

**Comment by ericbodden** [comment]
Indeed the documentation seems outdated. Our nightly builds now are available here:
https://ssebuild.cased.de/nightly/soot/lib/

I have asked @StevenArzt to see if we can again produce heros.jar and jasminclasses.jar files there. For now, soot-trunk.jar should contain the union of all those class files.

**Comment by 2048li** [comment]
ok. Thanks!

**Comment by StevenArzt** [comment]
We actually do have nightly builds for Heros (https://ssebuild.cased.de/nightly/heros/) and Jasmin (https://ssebuild.cased.de/nightly/jasmin/lib/). This also includes jasminclasses.jar.

**Comment by 2048li** [comment]
Ok, Thanks!

**Comment by malindadoo** [comment]
The link https://ssebuild.cased.de/nightly/soot/lib/ is still not working. Any updated links?

**Comment by mbenz89** [comment]
We moved the server: https://soot-build.cs.uni-paderborn.de/nightly/
Where did you find the hyperlink to the old build server?
