### ISSUE TITLE
No Support for multiple dex files in APK

### ISSUE THREAD

**Issue by vitaliiavdiienko** [Sable/soot#565]
Hi all,

a few issues:
1) Soot doesn't load classes from all .dex files
2) Soot tries (after instrumentation) to write all classes to one .dex file and doesn't even try to split them across different .dex files (and reaches limits of .dex files quickly...).

This makes Soot a useless framework for analyzing real-world Android apps.

Do you plan any activities in this direction?

Thank you in advance.

Best Rergards,
Vitalii

**Comment by ericbodden** [comment]
Hi Vitalii.

> a few issues:
> 1) Soot doesn't load classes from all .dex files
> 2) Soot tries (after instrumentation) to write all classes to one .dex file and doesn't even try to split them across different .dex files (and reaches limits of .dex files quickly…).

Yes those are known issues.

> This makes Soot a useless framework for analyzing real-world Android apps.

That’s a harsh statement. I would not say that one follows from the other.

> Do you plan any activities in this direction?

Yes we are. @StevenArzt would know more about the current state of things. But contributions are also always welcome!

Cheers,
Eric

**Comment by vitaliiavdiienko** [comment]
Hi Eric,
> 
That’s a harsh statement. I would not say that one follows from the other.

Agree. I was under the impression of an app with 9 classes.dex inside :smile: 

> But contributions are also always welcome!

I have a code that supports loading of all *.dex files from the APK and I actually use it (I can share it also), but writing .jimple classes to *.dex files back seems to be more complicated and experts can do it faster and better.

**Comment by ericbodden** [comment]
> I have a code that supports loading of all *.dex files from the APK and I actually use it (I can share it also), but writing .jimple classes to *.dex files back seems to be more complicated and experts can do it faster and better.

Sure, thanks. Let’s see whether Steven can enlighten us about the current status on this. I am not quite sure about what has already been implemented.

Cheers,
Eric

**Comment by StevenArzt** [comment]
If you need to load multiple dex files into your Soot scene, you have to do this on your own at the moment. You extract the additional dex files from the APK file and then specify the APK (for its main classes.dex) as well as the additional dex files in the process-dir option. This will merge all files together.

Automating this merging is something we can implement as an optional feature. If you have code for it, feel free to share it. There are, however, good reasons for not making this the default:

1) What happens if there is a class Foo in two of the additional dex files? If the main code loads either dex file depending on some condition, that's no problem. In our Soot scene, we would, however, have them both at the same time which is impossible.

2) Dex files are often split because the dex format has a restriction on the maximum number of classes and methods. If we merge it all and write it back out, the output file will be invalid and will fail to load on the device. We don't have a dex splitter yet.

3) What happens with class loader calls in the merged APK file? They would have to be removed to avoid duplicate loads.

**Comment by vitaliiavdiienko** [comment]
@StevenArzt 

Yes, you are totally right in what you wrote. Let's keep this thread as a possible future improvement.

But for FlowDroid I would make this option of loading multiple DEX files as a default. The reason is in the fact that nobody investigated in how many cases your Option 1 happens if we take let's say top 1000  apps from Google Play Store. Maybe it will not happen at all or will happen once. In this case we miss more potential leaks by being scared that something bad can happen.

**Comment by 2048li** [comment]
Now, I have a question that if I use this 
"Options.v().set_process_dir(Collections.singletonList(appAPK));" in eclipse to set scene, and then i want to change the scene in the  same program[means that I have a for loop to pass appAPK to set_process_dir to change scene], if I just change the appAPK, the scene seems not change. So how can I do to change scene with appAPK?
Thanks!

**Comment by StevenArzt** [comment]
@2048li First of all, if you have a different issue than what is discussed in this thread, then open up a new thread and don't clutter existing discussions.

Just changing the options doesn't make Soot re-load any classes. You need to restart Soot all the way, i.e., call the main method again or run the class resolver again, depending on what your original way of interacting with Soot was. Essentially, place your whole analysis in one big loop that iterates over all your APK files and does the full processing (configure Soot and run it) per APK.

**Comment by roylin1994** [comment]
@StevenArzt  

> 2) Dex files are often split because the dex format has a restriction on the maximum number of classes and methods. If we merge it all and write it back out, the output file will be invalid and will fail to load on the device. We don't have a dex splitter yet.

Can Soot split an apk's multiple dex files now?
If I convert an apk's (which has multiple dex files) jimple files to dex. It can only convert to one dex file(classes.dex). So I can't repack apk to run on phone. 
Have some solutions to solve this problem?

**Comment by denis-bogdanas** [comment]
The implementation of multiple dex support contained a bug which I just fixed. In some places in SourceLocator apk was read the old-fashioned way, even if process_multiple_dex was set. Submitting a pull request.

**Comment by denis-bogdanas** [comment]
Ok, I already had one pull request open. Just added the new changes to it: https://github.com/Sable/soot/pull/591

**Comment by StevenArzt** [comment]
Please do not append changes to unrelated pull requests. Open up now ones so that we can keep issues and changes separate. Having one humungous pull request makes it very hard to review and merge things. I merged that one commit manually: 601a4e44d47360bcab383b14f8734463ba90896f

**Comment by denis-bogdanas** [comment]
Hi Steven,
Thanks for merging. Having all pull requests clean would mean messing with 2 new branches at my end - one for dex fix and one working branch that has both changes. But I see your point, will do it as you suggest next time.
