### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by sloanyang** [Sable/soot#567]
soot/src/soot/jimple/parser/JimpleAST.java:53: error: cannot find symbol
Parser p =

It seems that github mirror is missing files inside folder.
https://svn.sable.mcgill.ca/soot/soot/trunk/src/soot/jimple/parser/

Please merge these files from svn.

**Comment by StevenArzt** [comment]
The Parser.java file should normally be placed under generated/sablecc/soot/jimple/parser/parser. I have added it and things should now compile again.
