### ISSUE TITLE
soot.scene.forceResolve(String className,int level)

### ISSUE THREAD

**Issue by ZhengqiaoLi** [Sable/soot#570]
1. soot.scene.forceResolve(String className,int level)
2. JNopStmt

I don't know what is function of the upper API.
can you tell me?
pls.

**Comment by ericbodden** [comment]
Hi.

This function forces a class to be loaded into the Scene, at a certain resolving level. It will be loaded into the scene even if otherwise it would not be loaded, e.g. because it’s name is on the excludes-list.

Cheers,
Eric
