### ISSUE TITLE
Can I use Soot to deal with Android 6.0 application？ 

### ISSUE THREAD

**Issue by njupt-moon** [Sable/soot#574]
@ericbodden 
Hi 
I get the android.jar from official SDK manager, but some problem occurs while i am dealing with Android 6.0 applications. I am sure that the application is targeted over Android 6.0.
Using 'E:\Android\android-sdk\platforms\android-23\android.jar' as android.jar
Exception in thread "main" soot.SootResolver$SootClassNotFoundException: couldn't find class: android.net.http.AndroidHttpClient (is your soot-class-path set properly?)

**Comment by StevenArzt** [comment]
The android.jar file for API version 23 (Android 6.0) doesn't contain the class mentioned in the exception, I have just checked. This is a good reason for Soot not being able to find it. The stub JAR files are not necessarily complete, i.e., they do not contain internal classes or classes the app developer is not supposed to see/use. Nevertheless, it is perfectly possible for apps to reference them. At runtime, on the actual device, these classes will be there.

Most simple solution: Use -allow-phantom-refs in Soot to skip over such issues.

**Comment by njupt-moon** [comment]
@StevenArzt 
Hi Steven,
oh yes, thanks for your answer!
