### ISSUE TITLE
Create a class into Android apk by instrumenting.

### ISSUE THREAD

**Issue by roylin1994** [Sable/soot#582]
I want to create a class into Android apk with instrument.But I don't konw well about Soot.
https://github.com/Sable/soot/wiki/Instrumenting-Android-Apps-with-Soot
https://github.com/Sable/soot/wiki/Creating-a-class-from-scratch
The two links above is the only thing I can learn from,but I don't know how to combine them to do my work.
Can someone help me ?

**Comment by roylin1994** [comment]
@StevenArzt  Can you help me?

**Comment by StevenArzt** [comment]
What exactly is your goal? Do you want to inject a class written in Java into an APK? In this case, just put it on Soot's process-dir together with the APK and then run Soot to transform the APK.

**Comment by roylin1994** [comment]
@StevenArzt  I want to instrument APK to create a class into APK.
For example,before `public class MainActivity extends Activity` I want to instrument code to create a class.So that when APK is decompiled,I can see the class I created before the `MainActivity`.
If I explain my goal clearly?

**Comment by StevenArzt** [comment]
You can create a new instance of SootClass and add it to your Soot scene. When Soot then writes out its transformed classes, your new SootClass will also be written into the APK.

For more information on app instrumentation with Soot, you can read section 5 and 6 in this paper: https://www.informatik.tu-darmstadt.de/fileadmin/user_upload/Group_EC-Spride/Publikationen/Instrumenting_Android_and_Java_Applications_as_Easy_as_abc.pdf

**Comment by roylin1994** [comment]
@StevenArzt Thank you for your reply.
I'll have a try by studying this paper.

**Comment by roylin1994** [comment]
@StevenArzt 
How to run "create a class from scratch"?
I use "run as Java application"。But it doesn't react.
Reminder that：<terminated>

**Comment by roylin1994** [comment]
@StevenArzt 
How to recognize the class that I want to instrument?
![qq 20160519112348](https://cloud.githubusercontent.com/assets/15721702/15381669/2873d322-1db4-11e6-9353-3c68e3d88770.png)
like the picture , I want to recognize the `public class MainActivity extends Activity ` to instrument code.
But I can only recognize the onCreate method `protected void onCreate(Bundle savedInstanceState) `
My code:
`@Override
	protected void internalTransform(Body body, String arg0, Map arg1) {
		String bodyGetClass = body.toString();
		System.out.println("bodygetClass: " + bodyGetClass);`
And the report only can recognize 
![oncreate](https://cloud.githubusercontent.com/assets/15721702/15381726/c5bf3d2e-1db4-11e6-91f7-965f052ed755.png)
So,how to recognize the class which I want to instrument code? Can Soot achieve this goal?Instrument code before Class.

**Comment by roylin1994** [comment]
@StevenArzt 
After I create class,how can I instantiate the class I created and invoke the method in the class in other java file.I can't new a class.
![qq 20160525184633](https://cloud.githubusercontent.com/assets/15721702/15537500/591f8698-22a9-11e6-939a-2d90aebe610b.png)

**Comment by roylin1994** [comment]
With the help of this tutorial: [https://github.com/Sable/soot/wiki/Creating-a-class-from-scratch](url)
I can create a class.
After that,you need to set the class you created to be Application Class.
Using `SootClass.setApplicationClass`,So that Soot can convert your class into a jimple file and write out.And the class will contain in Soot's Scene which can be used.
