### ISSUE TITLE
SootClass.methodIterator().remove disfunctional

### ISSUE THREAD

**Issue by MarcMil** [Sable/soot#587]
Obtaining an iterator via SootClass.methodIterator(), calling next() and remove() on it will remove the method from the methodList list in SootClass, but not from subSigToMethods, resulting in an inconsistent state.

Also, why does getMethods() return a new Arraylist, wouldn't be Collections.unmodifiableList be enough (and more memory efficient)?
Oops, I get it, because it would be fragile due to the fact that other methods may add or remove methods at the same time.

**Comment by patricklam** [comment]
The answer to all your questions is "yes". We should merge a pull request
that fixes them.

I think that get methods() may predate unmodifiableList.

pat

**Comment by MarcMil** [comment]
Regarding getMethods(): In the meantime I figured out why this might be a bad idea. It would be fragile due to the fact that other methods may add or remove methods at the same time, while another thread might hold a reference to the unmodifiable list and expects nothing to be changed. Creating a new array list prevents this and existing code might depend on this behaviour.

**Comment by patricklam** [comment]
I have a feeling that Raja's MSc thesis discusses this issue. Good to give
it a look.

We're not so concerned about threads and certainly weren't at original
design time. But even in the absence of threads, you can have some callee
that modifies the list unexpectedly. Iterators handle this transparently,
but there might be other dependencies that expect no changes.

I also tend to expect, though, that changes are much more common in the
list of units of a method body than in the set of methods. Indeed, you can
probably query the code to see whether the list of methods ever changes.

**Comment by StevenArzt** [comment]
Cleaning up subSigToMethods definitely shouldn't break anything, so let's go with that for now.

@MarcMil Can you open a pull request for that one?

Concerning the copy-lists and unmodifiable wrappers: That's the old trade-off between forgiveness of the API (you are prevented from breaking Soot's internal structures in user code) and performance. I tend to favor performance, so you won't see a lot of copying or unmodifiable wrappers in my code. Historically, Soot leans more on the safety side, even if this costs quite some memory for all the wrappers.
