### ISSUE TITLE
Iterate all classes

### ISSUE THREAD

**Issue by hylhp** [Sable/soot#588]
Hi all,

I'm a soot beginner. One question is how to iterate all classes in Soot?

I know inter-procedural analysis (-w, cg, wjtp) can achieve it. 
But these phases are time-consuming and over-engineering for my question.

Any suggestions? Thank you.

**Comment by MarcMil** [comment]
`for (SootClass clazz : Scene.v().getApplicationClasses() { ... }`
or

`for (SootClass clazz : Scene.v().getClasses() { ... }`

Depending on whether you want to see only the classes specified in process_dir or also the soot_classpath.
To learn more about soot, you can also read http://www.brics.dk/SootGuide/sootsurvivorsguide.pdf
