### ISSUE TITLE
Cannot Identity the Callbacks in Fragment

### ISSUE THREAD

**Issue by majestyhao** [Sable/soot#598]
The FlowDroid's dummyMain fails to show any callbacks inside the fragments of FragmentLifecycle2 in DroidBench. The issue remains when I added callback specifications such as android.app.ListFragment$onListItemClick in AndroidCallbacks.txt.

Thanks.

**Comment by StevenArzt** [comment]
Fragments are not yet supported by FlowDroid. We hope that we will be able to add this feature soon.
