### ISSUE TITLE
Bug: Got 0 methods in SootClass when analyzing apk files

### ISSUE THREAD

**Issue by Acmine** [Sable/soot#601]
Hello.

I am trying to use soot to analyze apk files. I add a customized wjpp phase. In my wjpp phase, I use
`Scene.v().getApplicationClasses()`
to get all the application classes.
However, when I iterate all the classes and use
`sootClass.getMethods()`
to iterate the methods of the classes, I got no method to iterate.
And method `getMethodCount` returns 0.

I tried to use dex2jar to transform the apk file to a jar file and then soot works well and recognized all the methods.

Is it a bug of soot when analyzing .apk file or did I use it in a wrong way?

Thank you very much for your attention.

**Comment by StevenArzt** [comment]
Please give a more complete code snippet that shows how you configure Soot and how you exactly iterate over the classes.

**Comment by Acmine** [comment]
In a MainDriver I wrote:
`
Pack wjpp = PackManager.v().getPack("wjpp");
        wjpp.add(new Transform("wjpp.myTrans", new MyTrans()));
String[] sootArgs = {
          "-w",
          "-f",
          "n",
          "-android-jars",
          "/Path/To/Android/sdk/platforms/",
          "-allow-phantom-refs",
          "-process-dir",
          "/Path/To/Some.apk"
};

soot.Main.main(sootArgs);
`


In the SceneTransformer.internalTransform I added the codes below:
`
Chain<SootClass> chain = Scene.v().getApplicationClasses();
Iterator<SootClass> iterator = chain.snapshotIterator();

while (iterator.hasNext()) {
      SootClass sootClassTemp = iterator.next();

      System.out.println(sootClass.getName() + ": " + sootClass.getMethodCount()); //This number gets 0.
      List<SootMethod> methods = sootClass.getMethods();
      for (SootMethod sm : methods) {
          System.out.println(sm); //Nothing is print here because List methods is empty
      }
}
`

Thanks a lot for your help.

**Comment by StevenArzt** [comment]
The problem arises because you do not specify the -src-prec option on your command line. The default option does not load dex or apk files, but only Java source code and binary code. Add "-src-prec apk" and your code works. I will also add a warning to Soot that reports such misconfigurations.

**Comment by Acmine** [comment]
Thanks a lot! I added that option and it works well.

Thank you so much.
