### ISSUE TITLE
Error while building soot.please help

### ISSUE THREAD

**Issue by kkrgithub** [Sable/soot#607]
[.....]
List
    [javac]         LinkedList worklist = new LinkedList();
    [javac]                                   ^
    [javac]   missing type arguments for generic class LinkedList<E>
    [javac]   where E is a type-variable:
    [javac]     E extends Object declared in class LinkedList
    [javac] Note: Some input files additionally use or override a deprecated API.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 100 errors
    [javac] 100 warnings

**Comment by anddann** [comment]
For building soot please refer to the wiki https://github.com/Sable/soot/wiki/Building-Soot-from-the-Command-Line-(Recommended).
Alternatively, download the full jar `sootclasses-trunk-with-dependencies.jar` from https://soot-build.cs.upb.de/nightly/soot/
