### ISSUE TITLE
Error on Soot download page? Broken link to nightly builds

### ISSUE THREAD

**Issue by phlummox** [Sable/soot#608]
Hi,

The Soot Download page (https://www.sable.mcgill.ca/soot/soot_download.html) seems to have a broken link.

It says nightly builds can be found at http://vandyk.st.informatik.tu-darmstadt.de/abc/, but I get a "no such host" error. I assume the correct link should be https://ssebuild.cased.de/nightly/soot/.

Cheers

**Comment by ericbodden** [comment]
Hi Laurie.

I wonder if it would be ok to remove the old Soot homepage or redirect it to the one on Github. The problem is that the old page is no longer being maintained.

Best wishes from Paderborn,
Eric

**Comment by RishMeh19** [comment]
please provide the current link for downloading .jar files of nightly build version of soot

**Comment by mbenz89** [comment]
@RishMeh19  https://github.com/Sable/soot#how-do-i-obtain-soot-without-maven

@ericbodden I think your answer was addressed to Laurie Hendren and not quite meant to be published here...

**Comment by ericbodden** [comment]
That's OK, no harm done.
