### ISSUE TITLE
Instrumenting If/else

### ISSUE THREAD

**Issue by sofysalty** [Sable/soot#611]
Hi
I'm new at working with soot library and I want to instrument my java program such that can insert statement before If and else block of my program. I want to have something as the code bellow as soot output:

`if x<y
 {statement1;
  x=x+y;}
else
   {statement2;
   y=x+z;}
`
statement1 and statement2 are two different statement I should add before first statement if If block and else block. Can you help me and say how I can do this modification to code with soot?

**Comment by anddann** [comment]
see https://github.com/Sable/soot/wiki/Creating-a-class-from-scratch
