### ISSUE TITLE
Where can  I download soot-2.6.0 ?

### ISSUE THREAD

**Issue by Dracula-36** [Sable/soot#616]
Hi, 
    When I use sbt to compile a project based on saprk, sbt hints me "org.sable#soot;2.6.0: not found". However, I've found in https://github.com/Sable/soot/releases without no results. I 'm confused and expecting your help.

**Comment by StevenArzt** [comment]
Soot 2.6 was never released. The last official release was 2.5, which is, however, also quite old by now. Your best option at the moment is to use our nightly builds available from https://ssebuild.cased.de/nightly/soot/.
