### ISSUE TITLE
Traps dropped when loading class via library

### ISSUE THREAD

**Issue by martinschaef** [Sable/soot#620]
I'm using Soot as a library as described in [your post](https://github.com/Sable/soot/wiki/Creating-a-class-from-scratch) using `Scene.v().loadClassAndSupport(foo);` on the following file:

```bash
wget https://raw.githubusercontent.com/jayhorn/jayhorn/devel/jayhorn/src/test/resources/horn-encoding/backlog/UnsatThrows.java
```

However, in the active body of main, there is no trap for the catch block. If I change the caught type from Throwable to Exception, the trap shows up. 

If I run the file through soot from command line using :
```bash
wget https://ssebuild.cased.de/nightly/soot/lib/soot-trunk.jar
mkdir out
javac -g UnsatThrows.java -d out/
java -cp soot-trunk.jar soot.Main -cp ./out:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar -pp -process-dir out/ -output-format J
```
The trap shows up for both versions.

Is there some flag that I (did not) set that prevents the trap from being created?

**Comment by ericbodden** [comment]
Hi Martin.

This looks like a bug to me. I expect a problem with a boundary condition.

Best wishes
Eric

**Comment by martinschaef** [comment]
Narrowed it down a bit. Here is the file/line that causes the problem:
https://github.com/jayhorn/jayhorn/blob/devel/soottocfg/src/main/java/soottocfg/soot/SootRunner.java#L210

If `createAssertionClass()` is called before `Scene.v().loadBasicClasses();` and `Scene.v(). loadNecessaryClasses();` (line 218/219) the trap in the above example is not loaded. In fact, the whole class hierarchy is a bit messed up. Throwable is not a subtype of Object, etc. 
If `createAssertionClass()` is called after the basic and necessary class loading, everything is fine.

**Comment by ericbodden** [comment]
Hi Martin.

Thanks for drilling this down. This seems to be a problem caused by your Soot extension then. It’s little surprising that stuff does not work when basic classes are not yet loaded. Usually that’s the first thing that Soot does. So can you fix the problem by just shifting the order of the calls?

Cheers
Eric

**Comment by martinschaef** [comment]
Already fixed it on my side. Just found it a bit scary that the scene generation still succeeds when I mess up the class loading and just drops a few traps. Thanks.
