### ISSUE TITLE
A simple problem: Unable to access jarfile soot.jar

### ISSUE THREAD

**Issue by OxfordNJ** [Sable/soot#631]
I have  downloaded the Soot .jar file, but when i command "java -jar soot.jar" on terminal,
it returned me an error: Unable to access jarfile soot.jar
What happend with it?

**Comment by StevenArzt** [comment]
Are you sure that the file is called "soot.jar"? The Soot JAR file from our nightly build server is usually called "soot-trunk.jar".

**Comment by anddann** [comment]
For downloading a ready-to use jar see https://repo1.maven.org/maven2/ca/mcgill/sable/soot/
