### ISSUE TITLE
Can I retrieve inherited methods?

### ISSUE THREAD

**Issue by njupt-moon** [Sable/soot#633]
@StevenArzt 
Hi!
If I have following code snippet:
class B {
    void BMethod() {}
}
class A extends B {
    void AMethod() {}
}.
It seems that I can use A.getMethods() to get method "A.AMethod()". But inherited method "A.BMethod()" is missing. Are there any APIs can be used to retrieve inherited methods?
Thx!

**Comment by MarcMil** [comment]
You can use the Hierarchy class and retrievethe respective superclasses and interfaces. You can query these for methods with the same subsignature.
