### ISSUE TITLE
Installed Soot plug-in, but no Soot option when right click .java file

### ISSUE THREAD

**Issue by april1989** [Sable/soot#639]
Hi,

I've installed the soot plug-in according to the tutorial. After the installation, there is the soot plug-in in plug-in folder and feature folder of Eclipse default plug-in installation folder. But there is no soot perspective or view. And when I right clicked any .java file, there is no soot option shown like in the tutorial. Mine is Eclipse 4.4 for Mac OS X.

Thanks.

**Comment by SamSunani** [comment]
Facing the same issue. I think the support for the plug-in has been discontinued.

**Comment by mjblackhorse** [comment]
Facing the same issue

**Comment by anddann** [comment]
Unfortunately, the eclipse plugin is outdated
