### ISSUE TITLE
Small Typo in the maven dependency snippet in README file

### ISSUE THREAD

**Issue by joelbandi** [Sable/soot#642]
The original XML snippet says 

``` xml
<version>RELEASE/version>
```

but It should be 

``` xml
<version>RELEASE</version>
```

 I want to commit the change in :smiley:

**Comment by anddann** [comment]
Thanks for pointing it out @joelbandi.
The current README snippets states `<version>3.0.0-SNAPSHOT</version>`.
Thus, I will close this issue.
