### ISSUE TITLE
Java to Jimple Compiler jrag files

### ISSUE THREAD

**Issue by efferifick** [Sable/soot#648]
Hello,

I am working on a Java 8 to Jimple compiler. I notice that you are using JastAddJ to generate a compiler for Java, but I cannot find the jrag used for generation.

Do you think it would be possible for you to share these?

Thanks!

**Comment by ericbodden** [comment]
Hello.

this is a good question. We used to use the version from here but it seems to no longer resider at this location:

http://svn.cs.lth.se/svn/jastadd-oxford/projects/trunk/JastAddExtensions/SootJastAddJ

Jesper did you happen to know whether a copy of the Jimple frontend still exists on your side?

Best wishes
Eric

**Comment by ericbodden** [comment]
Hi,

The IT staff at our department moved the SVN servers around a couple times and the old jastadd-projects SVN ended up with the new URL http://svn16.cs.lth.se/svn/jastadd-oxford/projects/

This URL seems to point to the SootJastAddJ repository: http://svn16.cs.lth.se/svn/jastadd-oxford/projects/trunk/JastAddExtensions/SootJastAddJ/

/Jesper

________________________________________

**Comment by ericbodden** [comment]
Thanks a lot Jesper, much appreciated! 

Markus does that help you out? By the way: it�s great that you are supporting the developmend of a Java 8 frontend for Soot. Thanks in advance!

Cheers
Eric

**Comment by efferifick** [comment]
I think this is enough to get me started. Please note that you SVN repository might be copied in your [abc](https://github.com/Sable/abc/tree/master/JastAddExtensions) repository, and also the abc repo contains the Jimple back-end which is another thing I was looking for. Thanks, will mark this issue as resolved.
