### ISSUE TITLE
Could not load classfile: java.io.ObjectInputStream (with OpenJDK 1.8.0_101)

### ISSUE THREAD

**Issue by he-sk** [Sable/soot#649]
Hi,

I'm trying the tutorial (Introduction: Soot as a command line tool) and get the following error after I add rt.jar to the class path:

```
$ export JAVA_HOME=$(/usr/libexec/java_home)
$ java -cp soot-2.5.0.jar soot.Main -cp .:$JAVA_HOME/jre/lib/rt.jar HelloWorld
Soot started on Tue Oct 04 14:58:45 PDT 2016
Unknown tag in constant pool: 16 at entry 764
Exception in thread "main" java.lang.RuntimeException: Could not load classfile: java.io.ObjectInputStream
	at soot.coffi.Util.resolveFromClassFile(Util.java:75)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:39)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:215)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:155)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.tryLoadClass(Scene.java:417)
	at soot.Scene.loadBasicClasses(Scene.java:990)
	at soot.Scene.loadNecessaryClasses(Scene.java:1061)
	at soot.Main.run(Main.java:167)
	at soot.Main.main(Main.java:141)
```

This is on OS X 10.11.6 with JDK 1.8.0_101.

I get the same error on Linux if I use OpenJDK 1.8.0_102. If I use 1.7.0_111, then it works. Is Java 8 byte code not supported?

Any help would be appreciated!

**Comment by he-sk** [comment]
Ok, it works with the nightly build.

**Comment by nicolas-mosch** [comment]
I have this problem running the eclipse plugin. Is there a way to use the nightly build with the plugin?

**Comment by Ghedeon** [comment]
Can confirm, the same issue with eclipse plugin.

**Comment by hoangdangninh** [comment]
For now I use `-allow-phantom-refs` switch but it seems not to be the author's intention

**Comment by preesee** [comment]
This tool used like stupid

**Comment by ericbodden** [comment]
@preesee what is it you wanted to say?

**Comment by ericbodden** [comment]
Also I am afraid that we do not maintain the Eclipse plugin any more. Instead I recommend using VisuFlow: https://blogs.uni-paderborn.de/sse/tools/visuflow-debugging-static-analysis/

**Comment by preesee** [comment]
https://stackoverflow.com/questions/47185478/unknown-tag-in-constant-pool-soot-using-springframework-spring-web-libraries
https://stackoverflow.com/questions/15179629/run-functions-using-soot
https://stackoverflow.com/questions/28230434/could-not-load-classfile
https://stackoverflow.com/questions/17082280/soot-how-to-prevent-loadclassandsupport-to-create-an-empty-sootclass
https://stackoverflow.com/questions/45513141/soot-plugin-and-command-line-windows-jdk1-7
