### ISSUE TITLE
Keep Line Number setting not saved

### ISSUE THREAD

**Issue by alshain** [Sable/soot#68]
When creating a new configuration in the Soot Eclipse plugin, the `--keep-line-number` setting is not saved.

Creating a new configuration on the fly using the `Run...` menu shows `"Keep line numbers"` enabled in `Input Attribute Options`, but the flag is not being passed to soot.

_Workaround_: Manually amend `args` in the custom Main class' `main(String[] args)` function.

Eclipse:

```
Version: Juno Service Release 2
Build id: 20130225-0426
```

**Comment by anddann** [comment]
The eclipse plugin is outdated.
