### ISSUE TITLE
Wrong classpath generation in plugin on Windows

### ISSUE THREAD

**Issue by alshain** [Sable/soot#70]
The Eclipse plugin assembles the soot class-path incorrectly.

The build path is configured as follows:

```
/C:/<projectname>/<pathWithinProject>
```

Expected

```
/C:/<pathToProject>/<projectname>/<pathWithinProject>
```

Some build path entries are present twice, once in the wrong format, once in the correct format. One path is only present in the wrong format.

**Comment by anddann** [comment]
Unfortunately, the eclipse plugin is outdate
