### ISSUE TITLE
Unit source start column number at -1

### ISSUE THREAD

**Issue by orichalque** [Sable/soot#705]
Hello, I've an issue while instrumenting a method with Soot.
I need to get the javaSourceStartColumnNumber of a statement, but the method :
`stmt.getJavaSourceStartColumnNumber()`
always return -1.

Those are my current options:

```
        Options.v().set_prepend_classpath(true);
        Options.v().set_soot_classpath("./target/classes");
        Options.v().set_keep_line_number(true);
        Options.v().set_keep_offset(true);
```

I can get the line number, using `stmt.getJavaSourceStartLineNumber()`, but not the columns.
Do I need an other option ?

Tell me if you need more informations about my code.

Best regards

**Comment by mbenz89** [comment]
Hi. Columns are not persisted in the Java bytecode, unfortunately. You can only get the line number if debug information is added to the bytecode.
The method exists because in Android bytecode, column numbers are a thing and Soot can thus extract them when analyzing Android.
