### ISSUE TITLE
Code silently exiting

### ISSUE THREAD

**Issue by chrisjbaik** [Sable/soot#708]
I'm doing some analysis on some poorly-constructed Bytecode, and I need to be able to catch Exceptions when this is the case. However, looking at the `BytecodeParser` file:

https://github.com/Sable/soot/blob/8ef2307f45b957894577582738499a2e79fa9e70/generated/jastadd/soot/JastAddJ/BytecodeParser.java#L169

and many similar subsequent lines, there is a silent `System.exit(1);` call without any logging or error propagation, making it difficult to track down the error.

**Comment by anddann** [comment]
Please use the ASM bytecode frontend, which is the default frontend now, as the JastAdd frontend is outdated.
