### ISSUE TITLE
Accessing positions (columns) of defs and uses on Java code >1.4

### ISSUE THREAD

**Issue by andrewhead** [Sable/soot#710]
Thanks for making and maintaining Soot!  It has been a big help in my project.

I'm building out a new text editor tool, and am trying to get positions of defs and uses with Soot.  I haven't yet been able to get these positions on modern Java code (>Java 1.4) and would love some advice!  There's *got* to be a way to do this with Soot.

The only configuration of Soot I have found to reliably produce position tags for def boxes on units is soot-2.5.0 (from [here](https://www.sable.mcgill.ca/soot/soot_download.html)) with the `-polyglot` and `-keep-line-number` flags.

The problem is Polyglot seems to only work on Java 1.4 (see bottom of this post for an minimal example of a program that Polyglot crashes on).

Any thoughts on a configuration that would let me get def and use positions on Java code >1.4?

**Other things I've tried**: In due diligence, I tried updating to the latest Soot nightly build.  It looks like recent changes to the parser have made it so the most I can get is line numbers for units.  Other issues I read suggested that maybe the Coffi front-end might provide more information from the parse, though the `-coffi` options causes the command line to fail with Java 1.8, and I see a missing method error for `Map.putIfAbsent` if I run it with Java 1.7.  I've traversed a good amount of the available solution space, so any pointers would be helpful!

# Replicating

To replicate:

```bash
# Get my current version of Soot software and dependencies
wget -nc http://www.sable.mcgill.ca/software/sootclasses-2.5.0.jar
wget -nc http://www.sable.mcgill.ca/software/jasminclasses-2.5.0.jar
wget -nc http://www.sable.mcgill.ca/software/polyglotclasses-1.3.5.jar
```

You can replicate the error if by running:
```bash
java -cp sootclasses-2.5.0.jar:jasminclasses-2.5.0.jar:polyglotclasses-1.3.5.jar soot.Main \
  -cp .:$JAVA_HOME/jre/lib/rt.jar Example -print-tags -keep-line-number -f J \
  -src-prec java -polyglot
```

It succeeds on this `Example.java`:

```java
import java.util.ArrayList;

public class Example {

    public static void main(String[] args) {
        System.out.println(new ArrayList());
    }

}
```

Ideally, this next version of `Example.java` would work.  It just adds an `Object` generic to List.  But it gives a `Example.java:6: Syntax error: unexpected operator <.`

```java
import java.util.ArrayList;

public class Example {

    public static void main(String[] args) {
        System.out.println(new ArrayList<Object>());
    }

}
```

# Context

If it's useful, here's [my current code](https://github.com/andrewhead/examplify/blob/master/java/DataflowAnalysis.java#L315) that currently works with Soot 2.5.0 and Polyglot for getting positions of defs and uses for arbitrary Java code without generics.

**Comment by anddann** [comment]
#705 fixed
