### ISSUE TITLE
How to use soot to analyze a dex file?

### ISSUE THREAD

**Issue by gehuangyi20** [Sable/soot#715]
I want to analyze the compiled result of AOSP 7. I will get a list of .dex file. Prior to aosp 7, I can use dex2jar to convert the dex file to a jar file. Then, I can use soot to analyze it. Right now, dex2jar does not work for aosp 7 due to new dex file format. It seems soot can directly read and process a dex file. However, I do not know how to do it. I cannot find any example of doing this. I am thinking of two ways doing it.

1. Read each class in the dex file, and output a .class file.
2. Read each class in the dex file, and convert it to a SootClass.

Can someone tell me how to do this?

Thank you very much!

**Comment by XingweiLin** [comment]
I don't know exactly what you want to do.
If you want to load dex file and transform it to jimple file.You can use command below and replace it for your `platforms` path and apk name.
`java -Xmx2g -jar soot-trunk.jar soot.Main -w -allow-phantom-refs -android-jars /home/jyoti/Android/adt-bundle-linux-x86_64-20140702/sdk/platforms/ -src-prec apk -f jimple -process-dir Onlytelephony.apk`

If you want to write transformer to do some analysis based on Soot.
You can go to this link to load dex file.
[https://github.com/secure-software-engineering/android-instrumentation-tutorial/tree/master/instrumentation/manual-instrumentation/RV2013_Soot_instrumentation/RV2013](url)
