### ISSUE TITLE
/classes/bin does not exist

### ISSUE THREAD

**Issue by AnshumanRohella** [Sable/soot#732]
I am trying to create WTG for an Android app using Gator which runs on top of Soot. I downloaded the app JustSit from F-droid repository and tried running it but got the following error: 

`java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/Users/anshumanrohella/Desktop/Main_Project/gator-3.2/AndroidBench/justsit/justsit/bin/classes'`

Am I supposed to build/pre process the app through some IDE or what?

**Comment by mbenz89** [comment]
Can you provide more details on what exactly you are trying to accomplish, please? The provided stack trace is incomplete!
If your question is Gator related you should probably ask for help there.

**Comment by anddann** [comment]
No response for 2 years, thus closed.
