### ISSUE TITLE
Can not find Android classes by Scene.v().getClasses()

### ISSUE THREAD

**Issue by ddecadall** [Sable/soot#735]
I'm using soot and flowdroid to analyse apk. However I found that when the target apk has more than one dex file, I can't find the class in the other dex(classes2.dex for example) by Scene.v().getClasses().
    My options set as follow:
                Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_process_dir(Collections.singletonList(apkPath));
		Options.v().set_force_android_jar(jarPath);
		Options.v().set_output_format(Options.output_format_none);
		Options.v().set_whole_program(true);
		Options.v().set_allow_phantom_refs(true);
		Scene.v().loadNecessaryClasses();
   then I use Scene.v().getClasses() to get all the class, but it only contains the classes in classes.dex.  
    Did I miss any options? or I use wrong api?

**Comment by mbenz89** [comment]
Soot doesn't process more than one dex file by default. 
Have you tried "Options.v().set_process_multiple_dex(true);"?

Src: http://soot-build.cs.uni-paderborn.de/doc/sootoptions/
Some hints: #565

**Comment by ddecadall** [comment]
Thanks, I forget that options.
