### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by Mohannadcse** [Sable/soot#747]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-force-android-jar /Users/li.li/Project/github/android-platforms/android-18/android.jar -process-dir jit -ire -pp -keep-line-number -allow-phantom-refs -src-prec apk -w -d testspace/jit.apk/retargeted/retargeted/jit

Max Memory:
1979MB

**Comment by pavanupb** [comment]
Can you please share the apk?
