### ISSUE TITLE
Encrypted entry exception

### ISSUE THREAD

**Issue by loyacin** [Sable/soot#753]
Hi,
I was running my program (using Soot) as usual when, suddently, a wild exception appeared:
![exception](https://user-images.githubusercontent.com/25507892/28034500-51e7392e-657f-11e7-814a-3643d77f5c42.png)
![exceptionmp](https://user-images.githubusercontent.com/25507892/28034499-51d82f1a-657f-11e7-9d25-8ffe684a3d6c.png)

This occurs when I try to load classes:
![code](https://user-images.githubusercontent.com/25507892/28034696-f36d0792-657f-11e7-94eb-bb0055656e5b.png)

I wonder if you have any clues, because it happens on some apks.

I have done my researches on Internet and nobody seem to have this problem.
Can you help me please?

Loïc.

PS: I get the error on this apk .
[apk.zip](https://github.com/Sable/soot/files/1136742/apk.zip)

**Comment by loyacin** [comment]
Hi everyone,

Thanks to one of my colleague and Linghui Luo, I have my answer.

Since I can't explain more clearly, I will copy Linghui Luo's answer:
> I think the reason for this exception is that the apk is encrypted, if you try to unpack the apk you need to input a password.
Soot can only scan apks which are not encrypted.

It is exactly the case. 
Here is an example for better understanding:
![pw](https://user-images.githubusercontent.com/25507892/28673783-797e55e6-72b1-11e7-8f0b-5bac993896b9.png)
You can try this to assure yourself that we have the same problem.

Thanks for help and have a good day,

Loïc.

**Comment by mbenz89** [comment]
FYI: The password is "infected".
