### ISSUE TITLE
Failed to load java.lang.CharSequence

### ISSUE THREAD

**Issue by kbelkhir** [Sable/soot#775]
Hi,
i'm trying to decompile some java classes using the command line and i'm getting this error : 
**Exception in thread "main" java.lang.Error: Error: Failed to load java.lang.CharSequence.**, i suppose it has something to do with the JDK version, i tried with JDK 8 and 7.
here is my command : 

`java -cp lib/soot-trunk.jar soot.Main -cp .:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar -process-dir testdir -f J Hello`

can anyone please tell me how to make it work ?

**Comment by gnom7** [comment]
I have the same problem.
`Exception in thread "main" java.lang.Error: Error: Failed to load java.lang.CharSequence.`
With following args
`-t:9:wjtp.jbco_cr HelloWorld -soot-classpath /rt.jar:/jce.jar -process-path /test -v -f class -d /test/out`
Why closing issue?
