### ISSUE TITLE
Creating `Jimple.v().newStaticInvokeExpr` with method arguments as class objects

### ISSUE THREAD

**Issue by maldil** [Sable/soot#800]
Hi 
I am in the process of instrumenting android application. I need to invoke a method inside a class in the application. I could find the way of invoking method which has int,String and double as method arguments in soot references. But, my requirement is to pass a class object as an argument for invoking method. 

For an example - 
If I need to invoke`ContextCompat::getColor(Context context, int id)` , first I need to create  `IntConstant.v(id)` and then the 'context' objects. This is the problem. How can I create and give 'context' object ? 
Specially the context would be the class itself which invoke the method. How can I handle such a scenario in soot ?
@mbenz89 @StevenArzt  your help would be much needed. Thank you in advance.

**Comment by ericbodden** [comment]
Hello.

If I understood you correctly then the context would be a class constant. In this case you should use something such as:

ClassConstant.v(“my.package.MyContextClass”)

This will return the Jimple-equivalent to the following Java code:
my.package.MyContextClass.class


Best wishes
Eric

**Comment by doo1234** [comment]
Hello @ericbodden 
Thank you very much for your response. I followed the suggestion above and I think that would be a solution for my question. When I implemented it, I got following exception In my code. Could you please suggest me a way to solve this ?

`Warning: Bad use of array type in argument 1 of call at staticinvoke <android.support.v4.app.ContextCompat: int getColor(android.content.Context, int)>(class "yogi/corporationapps/telescope/bigzoomhd/MainActivity$5", 12) 
	at soot.validation.CheckTypesValidator.checkCopy(CheckTypesValidator.java:119)
	at soot.validation.CheckTypesValidator.validate(CheckTypesValidator.java:73)
	at soot.Body.validate(Body.java:258)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:109)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:97)
	at soot.PackManager.runBodyPacks(PackManager.java:971)
	at soot.PackManager.access$000(PackManager.java:112)
	at soot.PackManager$1.run(PackManager.java:620)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Is this due to the class `MainActivity` is not a type of `context`? If then what should I do ? Thank you very much for your time.

**Comment by ericbodden** [comment]
Hmm this is hard to tell like this.

Can you maybe print out the Jimple code that gets generated?

Cheers
Eric

**Comment by doo1234** [comment]
@ericbodden I am not sure what you are asking here. 
I have given below the part of the code that I am using. Hope that helps. 
```
@Override
    protected void internalTransform(String s, Map<String, String> map){
		.
		.
		.
		SootMethod sm= Scene.v().getMethod(method);
		Body bd = sm.retrieveActiveBody();
		SootClass clz = Scene.v().getSootClass(sm.getDeclaringClass().getName());
		Local reqPerm = generateNewLocal(bd, Int);
		Unit u = createGetColor(reqPerm, clz);
		.
		.
		.
		
		
	}
	
private Unit createGetColor(Local lo, SootClass clz)
    {
        Unit u =null;
        LinkedList args = new LinkedList();
        String decClass = clz.getName();
        decClass= decClass.replace('.','/');
        
        Value deClass = ClassConstant.v(decClass);
        Value intcons = IntConstant.v(1);
        args.add(deClass);
        args.add(intcons);
      
        SootMethod sm = Scene.v().getMethod
                ("<android.support.v4.app.ContextCompat: int getColor(android.content.Context, int)");
        StaticInvokeExpr invokeExpr = Jimple.v().newStaticInvokeExpr(sm.makeRef(),args);
        u =Jimple.v().newAssignStmt(lo,invokeExpr);
        return u;
    }
```

Your help hi highly valuable.

**Comment by ericbodden** [comment]
Hmm I cannot see any obvious flaws in that code.

However, I was thinking that it would help to see a printout of the Jimple Body that you obtain _after_ your transformation has been applied.

That would help me see where the mismatch might be.

Cheers
Eric

**Comment by doo1234** [comment]
Hi @ericbodden 
Thank you for the information. I took a day to analyze the jimple body to have an indication about the exception. Sadly, I couldn't solve the issue.  I have given below the Jimple body. Could you please look at the jimple body and give me feed back or instructions to follow. 
 
 ```
public void onPictureTaken(byte[], android.hardware.Camera)
    {
        yogi.corporationapps.telescope.bigzoomhd.MainActivity$5 $r0;
        byte[] $r1;
        android.hardware.Camera $r2;
        android.graphics.Matrix $r3, r23;
        android.content.Intent $r4, r31;
        java.util.Date $r5, r26;
        java.lang.Exception $r6;
        java.io.FileOutputStream $r7, r29;
        java.io.ByteArrayOutputStream $r8, r28;
        android.content.ContentValues $r9, r30;
        int $i0, $i1, $i2;
        android.graphics.Bitmap $r10;
        yogi.corporationapps.telescope.bigzoomhd.MainActivity $r11;
        float $f0;
        java.lang.String $r12;
        boolean $z0, $z1;
        java.io.File $r13, $r15, r25;
        java.lang.StringBuilder $r14, r24;
        java.sql.Timestamp $r16, r27;
        long $l2;
        android.graphics.Bitmap$CompressFormat $r17;
        java.lang.Long $r18;
        android.content.ContentResolver $r19;
        android.net.Uri $r20;
        android.content.Context $r21;
        android.widget.Toast $r22;
        java.lang.CharSequence r33;

        $r0 := @this: yogi.corporationapps.telescope.bigzoomhd.MainActivity$5;

        $r1 := @parameter0: byte[];

        $r2 := @parameter1: android.hardware.Camera;

        $i0 = lengthof $r1;

     label01:
        $i2 = staticinvoke <android.support.v4.app.ContextCompat: int getColor(android.content.Context, int)>(class "yogi/corporationapps/telescope/bigzoomhd/MainActivity$5", "android.permission.CAMERA");

        if $i2 == 0 goto label02;

        staticinvoke <android.support.v4.app.ContextCompat: ColorStateList getColorStateList(android.content.Context, int) >(class "yogi/corporationapps/telescope/bigzoomhd/MainActivity$5", 123);

     label02:
        nop;

        $r10 = staticinvoke <android.graphics.BitmapFactory: android.graphics.Bitmap decodeByteArray(byte[],int,int)>($r1, 0, $i0);

     label03:
        r23 = new android.graphics.Matrix;

        $r3 = r23;

     label04:
  

```
	
Following code is the reonsible Soot code for the excetion.
#########Caller of the exception method (this.checkCopy)###################
```
if(var11.parameterTypes().size() != var12.getArgCount()) {
                    exception.add(new ValidationException(var10, "Argument count does not match the signature of the called function", "Warning: Argument count doesn\'t match up with signature in call" + errorSuffix + " in " + body.getMethod()));
                } else {
                    for(int var13 = 0; var13 < var12.getArgCount(); ++var13) {
                        this.checkCopy(var10, body, exception, Type.toMachineType(var11.parameterType(var13)), Type.toMachineType(var12.getArg(var13).getType()), " in argument " + var13 + " of call" + errorSuffix);
                    }
                }
```
				
######Body of the this.checkCopy which fire the exception (Warning: Bad use of array type in argument 1 of call at staticinvoke <android.support.v4.app.ActivityCompat: void requestPermissions )#######################

```
if(!(rightType instanceof NullType)) {
            if(!(leftType instanceof RefType) || !((RefType)leftType).getClassName().equals("java.lang.Object")) {
                if(leftType instanceof ArrayType || rightType instanceof ArrayType) {
                    if(leftType instanceof ArrayType && rightType instanceof ArrayType) {
                        return;
                    }

                    if(rightType instanceof ArrayType && (leftType.equals(RefType.v("java.io.Serializable")) || leftType.equals(RefType.v("java.lang.Cloneable")) || leftType.equals(RefType.v("java.lang.Object")))) {
                        return;
                    }

                    exception.add(new ValidationException(stmt, "Warning: Bad use of array type" + errorSuffix + " in " + body.getMethod()));
                }
```

					
According to my understanding, the error is happening due to the argument mismatch. The first argument should be type of android.content.Context . If it is the reason, how can I add extra implementation class to the object class ?. 
Your opinion regarding this is highly valuable.

**Comment by doo1234** [comment]
Hello @mbenz89 
I followed your instruction on `this `reference and the jimple body is looked like below. According to your first point, the problem is still exist due to implementation mismatch. The problem is, how can I add extra implementation class or parent class to the class `ogi.corporationapps.telescope.bigzoomhd.MainActivity`. Could you please instruct me on this ? Will `SootClass.addInterface()` and `SootClass.setSuperclass()` help for this. 

```
      public void onPictureTaken(byte[], android.hardware.Camera)
    {
        yogi.corporationapps.telescope.bigzoomhd.MainActivity$5 $r0;
        byte[] $r1;
        android.hardware.Camera $r2;
        android.graphics.Matrix $r3, r23;
        android.content.Intent $r4, r31;
        java.util.Date $r5, r26;
        java.lang.Exception $r6;
        java.io.FileOutputStream $r7, r29;
        java.io.ByteArrayOutputStream $r8, r28;
        android.content.ContentValues $r9, r30;
        int $i0, $i1, $i2;
        android.graphics.Bitmap $r10;
        yogi.corporationapps.telescope.bigzoomhd.MainActivity $r11;
        float $f0;
        java.lang.String $r12;
        boolean $z0, $z1;
        java.io.File $r13, $r15, r25;
        java.lang.StringBuilder $r14, r24;
        java.sql.Timestamp $r16, r27;
        long $l2;
        android.graphics.Bitmap$CompressFormat $r17;
        java.lang.Long $r18;
        android.content.ContentResolver $r19;
        android.net.Uri $r20;
        android.content.Context $r21;
        android.widget.Toast $r22;
        java.lang.CharSequence r33;

        $r0 := @this: yogi.corporationapps.telescope.bigzoomhd.MainActivity$5;

        $r1 := @parameter0: byte[];

        $r2 := @parameter1: android.hardware.Camera;

        $i0 = lengthof $r1;

     label01:
        $i2 = staticinvoke <android.support.v4.app.ContextCompat: int getColor(android.content.Context, int)($r0, 1);

        if $i2 == 0 goto label02;

        staticinvoke <android.support.v4.app.ContextCompat: ColorStateList getColorStateList(android.content.Context, int) >($r0, 123);
```

**Comment by mbenz89** [comment]
You are right, you need an instance of `MainActivity` and not of `MainActivity$5` (which seems to be an anonymous inner class of MainActivity) here. I confused this.
To get the context, you can try using some of the methods stated [here](https://stackoverflow.com/questions/3572463/what-is-context-on-android). Also, you can access the `MainActivity` instance which your `MainActivity$5` instance belongs to via the `this$0` field of `MainActivity$5`.

Manuel

**Comment by maldil** [comment]
Hi @mbenz89 
Thank you for the feedback on this. I am continuing with the suggestion and will give an update soon.

**Comment by maldil** [comment]
The problem is solved and thanks for @mbenz89 and @ericbodden for helping me to finalize this. 

I have a suggestion to made to soot development team. The exception fired in the method `this.checkCopy`   was `Bad use of array type in argument 1 of call at staticinvoke` . This is a little bit misleading because when some one read this, he would interpret the argument 1 as the first argument in the method signature. Since for loop in the caller of `checkCopy` iterate starting from zero, argument 1 in the exception message refers to the second argument in the method signature. Due to this it took a considerable amount of time to analyze the exception.

For loop in Soot
```
 for(int var13 = 0; var13 < var12.getArgCount(); ++var13) {
                        this.checkCopy(var10, body, exception, Type.toMachineType(var11.parameterType(var13)), Type.toMachineType(var12.getArg(var13).getType()), " in argument " + var13 + " of call" + errorSuffix);
 }
```
Since the reader might not know about the for loop when he see the message at the first time, my suggestion is to update the message accordingly.

Thank you very much again.

**Comment by ericbodden** [comment]
Great! @mbenz89 can you maybe update the message to add a note that parameters are zero-indexed?

Cheers
Eric

**Comment by mbenz89** [comment]
Done! (71e52672b3002b0d5161081d35d2cc50685f8159)
