### ISSUE TITLE
vs

### ISSUE THREAD

**Issue by SowmyaaVS** [Sable/soot#803]
Hi
How to open jimple files on mac?

Thanks in advance

**Comment by ericbodden** [comment]
With a text editor.

Cheers
Eric

--
Sent via my mobile

On Oct 25, 2017 02:22, SowmyaaVS <notifications@github.com> wrote:

Hi
How to open jimple files on mac?

Thanks in advance

**Comment by SowmyaaVS** [comment]
Thanks :)

**Comment by SowmyaaVS** [comment]
If I set the output format as java, I get the output as a class file. How to get output as a  file?

**Comment by mbenz89** [comment]
Unfortunately, Soot is not able to transform bytecode back to Java code. If for some reason you are not able to work with jimple, you might want to try to use Java decompiler to get back to Java from class files.

-Manuel

**Comment by SowmyaaVS** [comment]
Okay Thanks. But how to open the class file?

**Comment by mbenz89** [comment]
I doubt you want to work on class files directly. Either try to work with the jimple representation that is pretty close to Java or use something like [this](http://jd.benow.ca/) to open and decompile the class files.

**Comment by SowmyaaVS** [comment]
Thank you so much
