### ISSUE TITLE
How to insert an android library method  which has not been used in the android application?

### ISSUE THREAD

**Issue by maldil** [Sable/soot#808]
Hi all,
I am trying to insert an android system method to application but that method has not been used in android application. The insertion steps is as folows.

1. Prepare arguments
2. Get SootMethod
3. Insert the method

In the second step, I use `Scene.v().getMethod` to get the Soot method and create the 'InvokeStmt' as follows.
```
SootMethod sm = Scene.v().getMethod
                ("<android.support.v4.app.ActivityCompat: void startPostponedEnterTransition(android.app.Activity)>");

InvokeStmt stm = Jimple.v().newInvokeStmt(Jimple.v().newStaticInvokeExpr(sm.makeRef(),args));
units.insertBefore(stm,st);
```
The problem is, the method `Scene.v().getMethod` return an exception saying `java.lang.RuntimeException: tried to get nonexistent method`. I think the problem here is, the method `<android.support.v4.app.ActivityCompat: void startPostponedEnterTransition(android.app.Activity)`) has not been used in the application (not in the callgraph of the application). Because of that, the method `Scene.v().getMethod` fires the exception. Is there a way of adding android system method to application which has not been used in the application ? @mbenz89 @ericbodden  will you be able to help me ?

**Comment by maldil** [comment]
@mbenz89 @ericbodden  could you please advice me on this. I am rally stuck here. Thank you very much in advance.

**Comment by mbenz89** [comment]
Have you set the correct android jar?

**Comment by maldil** [comment]
@mbenz89 
Thank you for the attention on this. I cloned the android plat from jars from https://github.com/Sable/android-platforms and give the folder path as an argument when creating `new SetupApplication("Folder path","android.apk");`  I checked with target SDK version as well as mini version and both gave same exception. 

Meanwhile, Is my assumption is correct ? `Scene.v().getMethod` returns the `SootMethod ` object if and only if that method has been used in the application. If it is, how can we insert non used android support library method to applications using soot ?

**Comment by mbenz89** [comment]
So first of all, the android-platforms you state there are only up to version 11. I would try to use the platform dir delivered with your android sdk and get the platforms you need through the SDK manager.

Soot should actually be able to find the class if it is in the class path. If not, you need to add it otherwise it will have no chance to resolve it.

**Comment by maldil** [comment]
The ambiguity is, I could insert the method successfully for a android application which was running on android version - 9. But, another application which was running on version 10 gave the above exception. 

Just to be clear, if I run the second application on version -9 will I be able to avoid the exception ?

I would be really grateful to you if you could give me a link or reference where I can find more android jar versions , Is it enough to have stub jars to this analysis?

**Comment by mbenz89** [comment]
Most of the time having stubs will be enough. If you want to analyze the framework itself, you will need the implementations of course.
Sorry, I cannot help you here. @anddann any suggestions from your side?

**Comment by anddann** [comment]
@maldil 
Is the declaring clas contained in the scene?

**Comment by sasidv** [comment]
@anddann 
Thank you for your attention on this. Of course, I could get the declaring class ( `android.support.v4.app.ActivityCompat` )and it's methods as below. But the method `startPostponedEnterTransition(android.app.Activity)` was not in the printed method list.
```
SootClass clz1 = Scene.v().getSootClass("android.support.v4.app.ActivityCompat");
for (SootMethod sootMethod : clz1.getMethods()) {
          log.info("SootMethod name = "+sootMethod.getName());
 }
```
I checked this with every version of android-jars (by coping every android.jar versions to the folder android-10 ,10 is the target SDK version of the application), but it gives the mentioned exception all time. Since I checked with all the jar versions, I am pretty sure the method should be exist in those jars (at last in few).

My idea is, Scene.v().getMethod gives the methods that has been **used in the application**. Could you please confirm this ? Can I get `SootMethod` object if the method has not been used in the application **(but in the android.jar)** from `Scene.v().getMethod` ? If not, what approach should I use ?

**Comment by maldil** [comment]
@anddann 
Thank you for your attention on this. Of course, I could print the methods of the class using below approach.
```
SootClass clz1 = Scene.v().getSootClass("android.support.v4.app.ActivityCompat");
for (SootMethod sootMethod : clz1.getMethods()) {
                log.info("SootMethod name = "+sootMethod.getName());
}
```
But the method `startPostponedEnterTransition` was not among the printed method list. 
I checked this every android.jar versions (by copying every android.jar versions to the folder android-10 , where 10 was the target SDK version of the application). I could see the same exception for every android.jar versions. I am pretty sure the method is contained in the android.jar files (at last few among all).
My idea is, `Scene.v().getMethod` return `SootMethod`, if the method as been used in the application. Could you please confirm this ? If it is, what approach should I use instead of using `Scene.v().getMethod` ?

**Comment by anddann** [comment]
IMHO: there exist three options
1. the package is excluded, the class is a phantom class, and the method is not used in the app's code.
2. the class is not on the classpath, and allow phantom refs is enabled.
3. the class does not declare the method in the used android.jar.
The documentation https://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#startPostponedEnterTransition(android.app.Activity) states added in android 22.1.0

**Comment by maldil** [comment]
1. If a class is a phantom, a warning will be populated. right? If it is, I can say that, the class is not a phantom class. But I can assure the method is not used in app's code. This is a new method for the application.
2. How can I check this ?
3. I can say, I checked the with android.jar - 23, and still it gives the above exception.  
`Scene.v().getMethod` return `SootMethod `if the method is used in the app's code. Is it ? If then, according to the first suggestion, what approach should I use in order to insert not used method ?
Thank you for your time.

**Comment by anddann** [comment]
You can check if a class is a phantom using the method `SootClass.isPhantom()`
Usually, when a class is resolved from bytecode then all methods (at least) their signatures are registered in Soot.

**Comment by maldil** [comment]
Thanks for the update.
I ran the below code 
```
SootClass clz1 = Scene.v().getSootClass("android.support.v4.app.ActivityCompat");
 if(clz1.isPhantom())
                log.info("Class is a Phantom class");
```
According to the ouput, it'seems the class is not a Phantom class. But I can say, the method is not used in the app's code as well.

**2, the class is not on the classpath, and allow phantom refs is enabled.**
Then my attention goes to this option. How can I check whether the class in classpath ? what happens if I enable the phantom refs ?

**Comment by anddann** [comment]
If the class is not on the classpath then it is marked as a phantom class!
Where did you download the android.jar file?

**Comment by maldil** [comment]
I downloaded .jar files from [android-platforms](https://github.com/Sable/android-platforms) up to 17. 
From 17 onward, I got downloaded them through SDK manager (Android Studio). Those are stub jars, will that be a problem ?

**Comment by anddann** [comment]
The android.jar 17 does not contain the method in the class `android.support.v4.app.ActivityCompat`

**Comment by maldil** [comment]
Of course, But, I just used android.jar - version 23. But it gives the exception.

**Comment by anddann** [comment]
Okay, I checked the class is not contained in the android.jar from the sdk.
IMHO: the class should be contained in the the app's dex file.
Maybe @mbenz89 can give you more information.

**Comment by maldil** [comment]
The problem is narrowed down. The reason for printing couple of methods as given in previous comment is that those methods have been used in the android application. The support libraries are compiled into apps. Therefore support lib classes such as `ActivityCompat` are not contained in android.jar file. Now the problem is, what is the approach I can use to insert such method using soot ? I am really grateful if you can support me regarding this.

**Comment by anddann** [comment]
What jar's did you put into soot's classpath when running soot?
Have you tried putting an app into the classpath that contains the bytecode of the class `ActivityCompat`?

**Comment by mbenz89** [comment]
I guess you will have to find the jar file that contains the compiled ActivityCompat class and add it to the classpath.

**Comment by maldil** [comment]
Thank you for the comments. 
@mbenz89  your point is clear. I believe, the support libraries are compiled into apps, and so they are distributed to be consumed by apps, via the Google Maven repository. Then, I am wondering how can I make such android.jar (If possible please instruct).

@anddann I used the jar file downloaded from SDK manager,
your second point is not clear to me. currently andoid.jar does not contain bytecode of `ActivityCompat`. Could you please give more information, if I have missed something here ?

**Comment by mbenz89** [comment]
The support jars should be in your android sdk installation folder under <adk>/extras/android/support/v4/android-support-v4.jar. You have to additionally pass it to Soot by `-cp android.jar:<path>/android-support-v4.jar`

Manuel

**Comment by sasidv** [comment]
@mbenz89 The above path in my computer is not exactly same as you described above. But the location contains couple of file including .aar file. I have given a image of file below. 
![image](https://user-images.githubusercontent.com/33288810/32604809-05c8b95e-c575-11e7-9a40-f85d4b424ef6.png)

I am not sure whether the location is correct. I couldn't find jar file there (but md5,sha1 are there). Do you have idea on this ? Or else, does soot support process .aar files ?

**Comment by maldil** [comment]
@mbenz89 The above path in my computer is not exactly same as you described above. But the location contains couple of file including .aar file. I have given a image of file below. 
![image](https://user-images.githubusercontent.com/20140049/32607058-a303c328-c57d-11e7-8b6d-fdc4797a7b31.png)


I am not sure whether the location is correct. I couldn't find jar file there (but md5,sha1 are there). Do you have idea on this ? Or else, does soot support process .aar files ?

**Comment by mbenz89** [comment]
https://stackoverflow.com/questions/12382555/android-support-library-manual-download

**Comment by maldil** [comment]
@mbenz89 thank you very much for the help. Downloading android support lib .jars through SDK is manager no longer exist. But we can extract them from the .aar files in the above folder path. 

Now I am trying to give the .jar files to process for soot. Since I am using soot as maven dependency, I use Option.v() to update required configuration.   My next question is how can I update external jar to soot `in addition to android platform jar`s. I tried using following functions, but it seems it's not working. 

```
Options.v().set_force_android_jar("<path>/android-support-v4.jar");
Options.v().set_android_jars("<path>/android-support-v4.jar");
```
However, I am wondering, Is soot support to load multiple jars ? (`android.jar` and `android-support-v4.jar`)

**Comment by mbenz89** [comment]
You need to add it to the class path instead using it as android.jar. `set_android_jars` can be used to set the framework jar so that when analyzing an apk, soot knows where to find the framework classes.
You should be able to call `Options.v().set_soot_classpath("<path>:android.jar:<path>/android-support-v4.jar")` when analyzing the framework itself.

**Comment by maldil** [comment]
@mbenz89  Thanks for helping me to understand Soot and it's concepts. 
As you mentioned, I added Options.v().set_soot_classpath to Soot option as below. 

```
Options.v().set_soot_classpath("D:\\android-platforms-master\\android-19\\android.jar");
Options.v().set_soot_classpath("D:\\android-platforms-master" +
                "\\android-Support-libs\\android-support.jar");
```
But, sadly, it still gives the the following exception as before  
`java.lang.RuntimeException: tried to get nonexistent method <android.support.v4.app.ActivityCompat: void startPostponedEnterTransition(android.app.Activity)>`

But I can assure the `android-support.jar` contains the method as expected. 
![image](https://user-images.githubusercontent.com/20140049/32688212-c54dd7ae-c6f2-11e7-8309-a51b22e54299.png)

Have I something missed here ? 

I printed method of the class ActivityCompat as below, it doesn't give all the class methods except the methods that has been used in the application. (I believe, It indicates the class ActivityCompat  has not been loaded from android-support.jar )

```
SootClass clz1 = Scene.v().getSootClass("android.support.v4.app.ActivityCompat");
for (SootMethod sootMethod : clz1.getMethods()) {
         log.info("SootMethod name = "+sootMethod.getName());
 } 

```
Output was

```
[main] INFO CFG.APKDSceneTransformer - SootMethod name = <init>
[main] INFO CFG.APKDSceneTransformer - SootMethod name = finishAffinity
[main] INFO CFG.APKDSceneTransformer - SootMethod name = invalidateOptionsMenu
[main] INFO CFG.APKDSceneTransformer - SootMethod name = startActivity
[main] INFO CFG.APKDSceneTransformer - SootMethod name = startActivityForResult
```
Do I need to change another configuration of Soot ? Or have I something missed ?
Thank you again!!!

**Comment by mbenz89** [comment]
Could you please post your current configuration of Soot?
Btw. the classpath is one string separated by the directory separator (; in windows):
`Options.v().set_soot_classpath("D:\\android-platforms-master\\android-19\\android.jar;D:\\android-platforms-master" + "\\android-Support-libs\\android-support.jar");`

**Comment by maldil** [comment]
@mbenz89 
Thank you for the response.The soot initialization method of the program is as below. I updated the class path as you suggested. The exception saying about nonexistent of the method still fires and the output of the for loop (in my previous comment) is also the same.
```
    public static void init(ManifestFile manifestFile) {
        G.reset();
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_whole_program(true);
        Options.v().set_prepend_classpath(true);
        Options.v().set_validate(true);
        Options.v().set_output_format(Options.output_format_dex);
        Options.v().set_force_android_jar("D:\\android-platforms-master\\android-19\\android.jar");
        Options.v().set_soot_classpath("D:\\android-platforms-master\\android-19\\android.jar" +
                ";D:\\WSU_Project2\\android-platforms-master\\android-Support-libs\\android-19\\android-support.jar");
        Options.v().set_src_prec(Options.src_prec_apk);
        Options.v().set_process_dir(Collections.singletonList(Details.APK_PATH));
        analyzer = new SetupApplication("D:\\android-platforms-master",Details.APK_PATH);
        analyzer.getConfig().setTaintAnalysisEnabled(false);
        analyzer.setCallbackFile(Soot.class.getClassLoader().getResource("AndroidCallbacks.txt").getFile());
        Scene.v().loadNecessaryClasses();
    }
```
Should I modify the soot configurations ? Is there a debugging method to confirm the loading of andoid-support.jar  ? 
Thank you again for your help.

**Comment by mbenz89** [comment]
FlowDroid resets Soot's options internally.
Can you try adding your options like this:
```  
        SootConfigForAndroid sootConf = new SootConfigForAndroid() {
            @Override
            public void setSootOptions(Options options) {
                super.setSootOptions(options);
                // your optins here
            }
        };
        setupApplication.setSootConfig(sootConf);
```

And then instead of `Scene.v().loadNecessaryClasses` you execute `setupApplication.constructCallGraph`. I am not sure this will help, but let's try how far we get.

**Comment by maldil** [comment]
Hi @mbenz89 
Thank you very much for your time and suggestions. 
I changed the init() method as you suggested.
```
   public static void init(ManifestFile manifestFile) {
        G.reset();
      //  Options.v().allow_phantom_refs();
        SootConfigForAndroid sootConf = new SootConfigForAndroid() {
            @Override
            public void setSootOptions(Options options) {
                super.setSootOptions(options);
                options.v().set_allow_phantom_refs(true);
                options.v().set_whole_program(true);
                options.v().set_prepend_classpath(true);
                options.v().set_validate(true);
                options.v().set_output_format(Options.output_format_dex);
                //  Options.v().set_soot_classpath(manifestFile.getAndroidFilePath());
                log.info("Path "+manifestFile.getAndroidFilePath());
                options.v().set_force_android_jar(manifestFile.getAndroidFilePath());

                 options.v().set_soot_classpath("D:\\android-platforms-master\\android-19\\android.jar" +
                ";D:\\android-platforms-master\\android-Support-libs\\android-19\\android-support.jar");

                options.v().set_src_prec(Options.src_prec_apk);
                // Options.v().set_oaat(true);
                options.v().set_process_dir(Collections.singletonList(Details.APK_PATH));
  
            }
        };
        analyzer = new SetupApplication(Details.ANDROID_PLATFORMS,Details.APK_PATH);
        analyzer.setSootConfig(sootConf);
        analyzer.getConfig().setTaintAnalysisEnabled(false);
        analyzer.setCallbackFile(Soot.class.getClassLoader().getResource("AndroidCallbacks.txt").getFile());
        analyzer.constructCallgraph();
//        Scene.v().loadNecessaryClasses();
    }
```
Although I changed the code as above, sadly, it still fires the exception. Is there a way to check whether the Soot has loaded support lib correctly ?

To give more details, I follow the below approach to instrument the application
```
        PackManager.v().getPack("wjtp").add(new Transform("wjtp.myAnalysis", new APKDSceneTransformer(finalChangingMethods)));
        PackManager.v().runPacks();
        PackManager.v().writeOutput();
```

**Comment by maldil** [comment]
@mbenz89 I am spending time with analyzing this. Do you have any idea on this behavior ? Thank you  very much for your time.

**Comment by maldil** [comment]
@mbenz89 Since the above approach is not working as expected I am thinking about a different approach.
As I observed, If the method `<android.support.v4.app.ActivityCompat: void startPostponedEnterTransition(android.app.Activity)>` has been used in the application soot managed to load the method and insert it to anywhere else and It does not depend on whether the android.jar contains that method or not. I am wondering, whether I can use that behavior to insert the method for the applications which the method has not been used. I noticed Soot has recently built capability to load multiple dex files. My concern is, will I be able to load two .apk file such that, one application has used the method and the other application has not been used the method. I am thinking about a possibility of inserting the method obtained from one application and insert it to another application. @mbenz89  I want your help to determine the feasibility of the approach. Or else, would you recommend me to continue earlier approach and try to make it happen ?

**Comment by mbenz89** [comment]
If a method is used in the target code and there is no source available for it, Soot will create a phantom reference for the Method/Class. This means, that it will derive the signature of the class/method from its usage. 
So, if you really do not want to analyze the method itself, you can also just add the signature to the class. 
```
SootMethod m = new SootMethod("startPostponedEnterTransition",
                    Collections.singletonList(RefType.v("android.app.Activity")), VoidType.v(), Modifier.PUBLIC);
m.setPhantom(true);
SootClass clz = Scene.v().getSootClass("android.support.v4.app.ActivityCompat");
clz.addMethod(m);
```

However, if you want to analyze its body, you really need the sources. Actually, I think after adding the support library jar to the classpath, you should be able to acquire it. I would double check if the AcctivityCompat class is not phantom and the package is not excluded (at least FlowDroid excludes it by default in soot.jimple.infoflow.android.config.SootConfigForAndroid)

**Comment by maldil** [comment]
@mbenz89 Thank you for the information. 
I am eager to know about adding method from another .jar  to application with soot instrumentation. I checked `soot.jimple.infoflow.android.config.SootConfigForAndroid` and it was as below.
It seems  infoflow put `android.*`  to a exclude list. I believe, the class `android.support.v4.app.ActivityCompat' is automatically belongs to the exclude list.  Would that be a problem ?
```
    public void setSootOptions(Options options) {
        LinkedList excludeList = new LinkedList();
        excludeList.add("java.*");
        excludeList.add("sun.*");
        excludeList.add("android.*");
        excludeList.add("org.apache.*");
        excludeList.add("org.eclipse.*");
        excludeList.add("soot.*");
        excludeList.add("javax.*");
        options.set_exclude(excludeList);
        Options.v().set_no_bodies_for_excluded(true);
        options.set_output_format(12);
    }
```

**Comment by maldil** [comment]
I would like to give summary for anyone who is interested android apk instrumentation with soot.
I followed following steps when inserting a method from another jar file.

1. Put the jar file to Soot class path and try to insert the method. 
2. There is an alternative approach, you can create the method and insert it to soot as phantom method. This was the successful approach for me. 

Thank you @mbenz89 @anddann for sharing the information.
