### ISSUE TITLE
Soot fails to read Manifest of Android App

### ISSUE THREAD

**Issue by jpstotz** [Sable/soot#814]
The code in `Scene.getTargetSDKVersion()` fails for [app-JniTests-release.apk.zip](https://github.com/Sable/soot/files/1437843/app-JniTests-release.apk.zip)

> java.lang.ArrayIndexOutOfBoundsException: 96
> 	at android.content.res.StringBlock.getShort(StringBlock.java:231)
> 	at android.content.res.StringBlock.getString(StringBlock.java:91)
> 	at android.content.res.AXmlResourceParser.getName(AXmlResourceParser.java:140)
> 	at soot.Scene.getTargetSDKVersion(Scene.java:460)
> 	at soot.Scene.getAndroidAPIVersion(Scene.java:405)
> 	at soot.Scene.getAndroidJarPath(Scene.java:364)
> 	at soot.Scene.defaultAndroidClassPath(Scene.java:608)
> 	at soot.Scene.defaultClassPath(Scene.java:547)
> 	at soot.Scene.getSootClassPath(Scene.java:297)
> 	at soot.SourceLocator.getClassSource(SourceLocator.java:73)
> 	at soot.Scene.tryLoadClass(Scene.java:830)
> 	at soot.Scene.loadBasicClasses(Scene.java:1504)
> 	at soot.Scene.loadNecessaryClasses(Scene.java:1583)

I tried to track the error down, however the problem seems to be located in `axmlprinter-2016-07-27.jar` respectively the dependency.

> 		<dependency>
> 			<groupId>ca.mcgill.sable</groupId>
> 			<artifactId>axmlprinter</artifactId>
> 			<version>2016-07-27</version>
> 		</dependency>

I searched for the code of this dependency however I could not found it. 
Your nexus repository at https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/ca/mcgill/sable/axmlprinter/2016-07-27/ only contains the binaries as well.
Where does this code come from and where are the sources (could be also a problem for the license examination mentioned by Eric)? 

The interesting part is that Soot is the only tool having problems with this app. apktool, jad-x and so on they all work without problems. Even the AndroidManifest.xml parser from soot-infoflow-android works without problems (at least the outdated fork of the code I use).

BTW: The mentioned dependency `axmlprinter-2016-07-27.jar`  contains the package `org.xmlpull.v1` with several classes. The same package is also included in the dependency 

> 		<dependency>
> 			<groupId>xmlpull</groupId>
> 			<artifactId>xmlpull</artifactId>
> 			<version>1.1.3.4d_b4_min</version>
> 		</dependency>

Therefore we have classes that are available twice within Soot. AFAIK the result can be random which classes are preferred... I don't think that this is related to the error

**Comment by mbenz89** [comment]
I think the source can be found [here](https://code.google.com/archive/p/android4me/source/default/source).
Also, there is an updated/refactored version which seems to be more recent [here](https://github.com/rednaga/axmlprinter).
Maybe you can evaluate them against each other and see if it makes sense to use the latter instead.

**Comment by jpstotz** [comment]
I tried to create a test project using the "updated/refactored version" you mentioned. But the code does not math the classes used by soot. Also it only allows to print the xml file, not parse. Therefore I don't think that it will help.

In the old Google code project I found it. Looks like this is a well-known issue for some years now: https://code.google.com/archive/p/android4me/issues/11

@StevenArzt just mentioned that all apps compiled with Android Studio 3.0 seem to cause this problem.

**Comment by mbenz89** [comment]
Any suggestions for a fix?

**Comment by jpstotz** [comment]
My suggestion would be to remove `axmlprinter` from Soot and use instead `pxb.android.axml.AxmlReader` (by Panxiaobo, published under Apache 2 license).
I already made some tests using this parser and it looks promising. 

Unfortunately the project of axml (again a Google code project) has been deleted. Luckily I saved the original sources in 2014 and can provide them.

**Comment by mbenz89** [comment]
Are we actually allowed to use Apache 2 licensed libraries? AFAIK Apache 2 is incompatible to LGPLv2.
On the other hand, FlowDroid seems to use the same library. Any chance we can reuse code from it?

**Comment by jpstotz** [comment]
I have created a fix for this issue - see the referenced pull request.

**Comment by mbenz89** [comment]
Fixed in 3e8dced9e5f669a7a247a6ef4ecc6bc7b459da97
