### ISSUE TITLE
JAVA VerifyError after instrumenting jimple 

### ISSUE THREAD

**Issue by Nebula010** [Sable/soot#823]
I want to instrument some jimple codes in the "wjtp" pack and output them to a class file.
After add the  // Instrument something to the output HelloWorld.class PART, there will be a 
"Exception in thread "main" java.lang.VerifyError: (class: HelloWorld, method: xgcd signature: (II)I) Expecting to find integer on stack" error.

Here is the code:

import java.io.*;
import java.util.*;

import soot.*;
import soot.jimple.JasminClass;
import soot.jimple.Jimple;
import soot.jimple.JimpleBody;
import soot.jimple.StringConstant;
import soot.options.Options;
import soot.shimple.Shimple;
import soot.shimple.ShimpleMethodSource;
import soot.shimple.internal.ShimpleBodyBuilder;
import soot.util.Chain;
import soot.util.JasminOutputStream;

public class Main {

    public static void main(String[] args) {

        G.reset();
        Options.v().set_whole_program(true);
        Options.v().set_via_shimple(true);

        Options.v().set_keep_line_number(true);
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_keep_offset(true);
        Options.v().set_verbose(false);

        Options.v().setPhaseOption("jb", "use-original-names:true");
        Options.v().setPhaseOption("shimple", "node-elim-opt:false");

        PhaseOptions.v().setPhaseOption("jb", "use-original-names:true");
        PhaseOptions.v().setPhaseOption("shimple", "node-elim-opt:false");

        List<String> argsList = new ArrayList<String>(Arrays.asList(args));
        argsList.addAll(Arrays.asList(new String[]{
                "-w",
                "-f",
                "jimple",
                "-via-shimple",
                "-src-prec",
                "java",
                "-main-class",
                "HelloWorld", //main-class
                "HelloWorld" //argument classes

        }));

        PackManager.v().getPack("wjtp").add(new Transform("wjtp.myTrans", new SceneTransformer() {

            @Override
            protected void internalTransform(String phaseName, Map options) {

                // Get the main class
                SootClass sc = Scene.v().loadClassAndSupport("HelloWorld");
                Scene.v().setMainClass(sc);

                // Get all the methods of main class
                List<SootMethod> sm = sc.getMethods();
                for(SootMethod temp : sm){
                    System.out.println("the methods are : + " + temp);
                }

                // retrieveActiveBody() will let init() have active body
                SootMethod init = sm.get(0);
                init.retrieveActiveBody();

                // Get the main method and xgcd method
                SootMethod mainMethod = Scene.v().getMainClass().getMethodByName("main");
                SootMethod xgcdMethod = Scene.v().getMainClass().getMethodByName("xgcd");
                System.out.println("the signature is " + xgcdMethod.getSignature());

                // Get the body of xgcd
                Body b = xgcdMethod.retrieveActiveBody();

                // Get the unit chain
                Chain<Unit> units = b.getUnits();

                // Instrument something to the output HelloWorld.class
                // THIS PART IS THE CAUSE OF THE ERROR
                Local tmpRef;
                tmpRef = Jimple.v().newLocal("tmpRef", RefType.v("java.io.PrintStream"));
                b.getLocals().add(tmpRef);

                Unit tmpRefAssignUnit = Jimple.v().newAssignStmt(tmpRef, Jimple.v().newStaticFieldRef(Scene.v().getField("<java.lang.System: java.io.PrintStream out>").makeRef()));
                units.insertBefore(tmpRefAssignUnit, units.getLast());

                SootMethod toCall = Scene.v().getMethod("<java.io.PrintStream: void println(int)>");
                units.insertAfter(Jimple.v().newInvokeStmt(Jimple.v().newVirtualInvokeExpr(tmpRef, toCall.makeRef(), StringConstant.v("Test!"))), tmpRefAssignUnit);

                // Jasmin output
                File fileName = new File("HelloWorld.class");
                try {
                    OutputStream streamOut = new JasminOutputStream(new FileOutputStream(fileName));
                    PrintWriter writerOut = new PrintWriter(new OutputStreamWriter(streamOut));
                    JasminClass jasminClass = new soot.jimple.JasminClass(sc);
                    jasminClass.print(writerOut);
                    writerOut.flush();
                    streamOut.close();
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }));

        args = argsList.toArray(new String[0]);
        soot.Main.main(args);

    }
}

So how to avoid this situation after adding some instruments? Thank you.

**Comment by ericbodden** [comment]
Hi.

Did you try to call validate() on the bodies you generate?

Cheers
Eric

**Comment by mbenz89** [comment]
First of all, like @ericbodden said, it is a good idea to call `body.validate()` after instrumenting jimple code.  

I think the problem in your code is located here:
```
SootMethod toCall = Scene.v().getMethod("<java.io.PrintStream: void println(int)>");
units.insertAfter(Jimple.v().newInvokeStmt(Jimple.v().newVirtualInvokeExpr(tmpRef, toCall.makeRef(), StringConstant.v("Test!"))), tmpRefAssignUnit);
```
You try to call a method `void println(int)` with an argument of type String (`StringConstant.v("Test!")`). Calling the method `"<java.io.PrintStream: void println(java.lang.String)>"` instead should solve the problem.

Manuel

**Comment by Nebula010** [comment]
I have tried what @mbenz89 said and solved the problem! 
@ericbodden @mbenz89 Thank you all!

**Comment by Nebula010** [comment]
BTW, @ericbodden there is a 404 error of 
**https://soot-build.cs.uni-paderborn.de/doc/sootoptions/**  
and
**https://soot-build.cs.uni-paderborn.de/doc/soot/** 
recently.

**Comment by mbenz89** [comment]
Where have you found above stated links? 
We moved the options and doc: https://github.com/Sable/soot/wiki/Options-and-JavaDoc
If you are using the latest build from the development branch, you find the corresponding links under "Development".

**Comment by Nebula010** [comment]
I found them on this page:
https://github.com/Sable/soot/wiki/Tutorials
The first two links: **Command line options and Phase options** and **Javadoc**
