### ISSUE TITLE
Find value of assigned $r3

### ISSUE THREAD

**Issue by arvind4141** [Sable/soot#825]
Hello, I'm doing static analysis with Soot for Android and I've faced a small issue.

Soot : virtualinvoke $r0.<io.cordova.hellocordova.MainActivity: void loadUrl(java.lang.String)>($r3)
Actual class: loadUrl(this.launchUrl)
Correct me if I'm wrong but I'm assuming that the value of the $r3 is equilavent to this.launchUrl?

How do I go about attempting to retrieve the value of this.launchUrl from $r3?

Thank you very much for the help!

**Comment by ericbodden** [comment]
Hello.

You would have to walk backwards to find assignments to that variable. You can use Soot's def-use analysis to access such information easily or you can implement a backwards analysis yourself.

An alternative is to propagate the value of that variable forward from its assignment to the loadUrl call. But this requires that you know upfront that this value will be relevant and thus must be propagated.

Hope that helps.

Cheers
Eric

--
Sent from my mobile
________________________________
