### ISSUE TITLE
delete jasmin and heros in .classpath

### ISSUE THREAD

**Issue by linghui2016** [Sable/soot#826]
soot is now maven project. jasmin and heros are still referenced in .classpath.  If the developer doesn't  have jasmin and heros in the workspace, eclipse shows a build error. In my opinion, the .classpath file can be deleted and ignored as it is automatically generated when importing soot as a maven project.
@StevenArzt What do you think?
@mbenz89

**Comment by linghui2016** [comment]
same with soot-infoflow-android (soot and soot-infoflow are referenced)

**Comment by mbenz89** [comment]
Deleted Jasmin and Heros from Soot's .classpath: 2e6b7802a1931df2cb07beefc420deae620aedbb
