### ISSUE TITLE
How to add If statement with a return statement

### ISSUE THREAD

**Issue by sasidv** [Sable/soot#828]
Hi 
I am in the process of instrumentation of android applications. I refer the [Example](https://github.com/secure-software-engineering/android-instrumentation-tutorial/blob/master/instrumentation/manual-instrumentation/RV2013_Soot_instrumentation/RV2013/src/instrumentation/MyBodyTransformer.java) as a guidance. 
Following approach has been taken to insert if statement in the above example.
```
EqExpr equalExpr = Jimple.v().newEqExpr(localBoolean, zero);
NopStmt nop = insertNopStmt(body, u);
IfStmt ifStmt = Jimple.v().newIfStmt(equalExpr, nop);
```
My question is, How can I add extra return statement into the above if expression ?
The code should look like below after the insertion.

```
if (no.startsWith("0900"))
{
   Log.i("Aspect ", "Premium SMS message blocked ");
   return null;
}
```
How can I add `return null`, I searched for this in mailing list,  but couldn't find a solid answer for this question.

**Comment by sasidv** [comment]
I used below approach. 
```
IfStmt ifStmt = Jimple.v().newIfStmt(UnequalExpr,unit);
ifStmt.setTarget(Jimple.v().newRetStmt(NullConstant.v()));
```
It gives below exception 
`java.lang.RuntimeException: Box JimpleLocalBox(null) cannot contain value: null(class soot.jimple.NullConstant)`
Or, can I use the abstract class UnitBox for this ? 
Could you please help me to add this. Or else, could you please give a reference guide. 
@mbenz89 @elavoie

**Comment by ericbodden** [comment]
Hi.

Please read up on Jimple. In Jimple, if-statements can only contain expressions, not statements. You will have to generate code such as:

if(x) goto l;
return whatever();
l: … // other code

Cheers
Eric

**Comment by mbenz89** [comment]
Hi, there are several ways to accomplish that.
I would do it like this (pseudo code):
```
units=method.getBody.getUnits();
Value zero = IntConstant.v(0);
EqExpr equalExpr = Jimple.v().newEqExpr(localBoolean, zero);
NopStmt nop = Jimple.v().newNop(); // create nop so that we have a temporary label to jump to
IfStmt ifStmt = Jimple.v().newIfStmt(equalExpr, nop);
units.add(ifStmt);
// do what ever you want to do here
units.add(nop); // add nop statement to jump to
Stmt someOtherThing = jimple.v().new...();
units.swapWith(someOtherThing); // replace the nop with a real instruction
```

There, your code would only be executed if "localBoolean" is not zero.

Manuel

**Comment by sasidv** [comment]
@mbenz89 @ericbodden  Thanks a lot. 
I am still trying to understand the concept here. I am little bit unclear about the functionality of the `nop` statement.   I am wondering whether I can map `nop` statement as `else` for the if statement.

Meanwhile, I am trying insert to a code piece to  an android application as below. I need to insert this into a method just after every locals are defined. 

```
int a = android.ClassA.methodA();
if(a != 0)
{
android.ClassA.methodB();
return null;
}
```

I followed the below manner. 

First inserted the methodB.
```
Iterator<Unit> it = bd.getUnits().snapshotIterator();
 while (it.hasNext()) {
       Unit unit = (Unit) it.next();
       soot.jimple.Stmt st = (soot.jimple.Stmt)unit;
        if(st.containsInvokeExpr()){
           units.insertBefore(Jimple.v().newInvokeStmt(Jimple.v().newStaticInvokeExpr(sm.makeRef(),args)),st);
            break;
          }
}
```
Then,I iterated the body again to find the method B. and then inserted method A. I built this by looking at the [example](https://github.com/secure-software-engineering/android-instrumentation-tutorial/blob/master/instrumentation/manual-instrumentation/RV2013_Soot_instrumentation/RV2013/src/instrumentation/MyBodyTransformer.java) 
```
it = bd.getUnits().snapshotIterator();
            while (it.hasNext()) {
                Unit unit = (Unit) it.next();
                soot.jimple.Stmt st = (soot.jimple.Stmt)unit;

                if(unit instanceof InvokeStmt) {
                    InvokeStmt invoke = (InvokeStmt)unit;
                    if(invoke.getInvokeExpr().getMethod().getSignature().equals
                            ("<android.ClassA.MethodB>")) //get the unit of inserted method B
                    {
                        log.info("method found");
                        Type Int = IntType.v();
                        LocalGenerator lg = new LocalGenerator(body);
                        Local para = lg.generateLocal(Int);
                        AssignStmt astmt = Jimple.v().newAssignStmt(para,
                                <android.ClassA.MethodA>);
                        bd.getUnits().insertBefore(astmt,unit); //unit is the methodB
                        IntConstant zero = IntConstant.v(0);
                        EqExpr equalExpr = Jimple.v().newEqExpr(para, zero);
                        NopStmt nop = Jimple.v().newNopStmt();
                        body.getUnits().insertAfter(nop, unit);
                        IfStmt ifStmt = Jimple.v().newIfStmt(equalExpr,nop);
                        bd.getUnits().insertBefore(ifStmt,unit);

                        bd.getUnits().swapWith(nop,Jimple.v().newReturnStmt(NullConstant.v()));
                        break;
                    }
                }

            }
```
Unfortunately this returns an error as below `no defs for value: $r1! `. But I checked the Jimple body after the transformation, it has defined the  `$r1`. The jimple body after the transformation is as below

  ```
 public void onPictureTaken(byte[], android.hardware.Camera)
    {
        nil.apps.droid.bigzoomhd.MainActivity$5 $r0;
        byte[] $r1;
        android.hardware.Camera $r2;
        android.graphics.Matrix $r3, r23;
        android.content.Intent $r4, r31;
        java.util.Date $r5, r26;
        java.lang.Exception $r6;
        java.io.FileOutputStream $r7, r29;
        java.io.ByteArrayOutputStream $r8, r28;
        android.content.ContentValues $r9, r30;
        int $i0, $i1, $i2;
        android.graphics.Bitmap $r10;
        nil.apps.droid.bigzoomhd.MainActivity $r11;
        float $f0;
        java.lang.String $r12;
        boolean $z0, $z1;
        java.io.File $r13, $r15, r25;
        java.lang.StringBuilder $r14, r24;
        java.sql.Timestamp $r16, r27;
        long $l2;
        android.graphics.Bitmap$CompressFormat $r17;
        java.lang.Long $r18;
        android.content.ContentResolver $r19;
        android.net.Uri $r20;
        android.content.Context $r21;
        android.widget.Toast $r22;
        java.lang.CharSequence r33;
        java.lang.String[] $r23;

        $r0 := @this: nil.apps.droid.bigzoomhd.MainActivity$5;

        $r1 := @parameter0: byte[];

        $r2 := @parameter1: android.hardware.Camera;

        $i0 = lengthof $r1;

     label01:
        $r23 = newarray (java.lang.String)[1];

        $r23[0] = "test";

        $i2 = staticinvoke <android.ClassA.methodA()>; //my insertion

        if $i2 == 0 goto label02; //my insertion

        staticinvoke <android.ClassA.MethodB()>; //my insertion

     label02:
        return null; //my insertion

        $r10 = staticinvoke <android.graphics.BitmapFactory: android.graphics.Bitmap decodeByteArray(byte[],int,int)>($r1, 0, $i0);

     label03:
        r23 = new android.graphics.Matrix;
```

@mbenz89 Could you please check the jimple body and help me to identify the error ? Any suggestion to improve the way of code insertion ?

**Comment by sasidv** [comment]
@mbenz89  I am looking forward to have your view on my approach. Could you please help me to avoid the exception when I run body.validation. The exception message was `no defs for value: $r1!.`. Really thank you for your time.

**Comment by sasidv** [comment]
@mbenz89 I am still struggling to add the return statement. I changed the approach as below by looking at the pseudo code.

```
    Iterator<Unit> it = bd.getUnits().snapshotIterator();
    Unit unitThis = null;
	while (it.hasNext()) {
        unitThis = (Unit) it.next();
        soot.jimple.Stmt st = (soot.jimple.Stmt)unitThis;
        if(st.containsInvokeExpr()){
                    break;
        }
    }
    
    InvokeStmt methodB = UtilInstrument.createMethodB(bd, unitThis);
    units.insertBefore(methodB, unitThis); //Inserted methodB before unitThis
	
    Type Int = IntType.v();
    Local condition = generateNewLocal(bd, Int);
    StaticInvokeExpr methodA = UtilInstrument.generateMethodA(bd,firstAPermission,clz);
    AssignStmt astmt = Jimple.v().newAssignStmt(condition,methodA);
    units.insertBefore(astmt,methodB); //inserted assignment before method B
	
	//Creating if condition
    IntConstant zero = IntConstant.v(0);
    EqExpr equalExpr = Jimple.v().newEqExpr(condition, zero);
    NopStmt nop = Jimple.v().newNopStmt();
    IfStmt ifStmt = Jimple.v().newIfStmt(equalExpr,nop);
	
    bd.getUnits().insertBefore(ifStmt,methodB); // inserted before method B

    bd.getUnits().insertAfter(nop,methodB); //inserted after method B
    
    units.swapWith(nop,Jimple.v().newReturnStmt(NullConstant.v())); // this the reason for the error

    log.info("Transformed body");
    System.err.println(bd);
    bd.validate();
```

**The problem is, when I  swap nop statement with return statement through `(units.swapWith(nop,Jimple.v().newReturnStmt(NullConstant.v()));)`  following exception fires `no defs for value: $r1!` . But when I remove that, code was transformed without exception.** 


The code what I need to insert is as below. I am trying to insert this as the first invoking methods to a existing method in the android application. 

```
androidapplicationMethod ()
{
int i = methodA();
   if(i !=0)
   {
      methodB()
      return;
    }

// other statement of androidapplicationMethod
}
```

The jimple body of the transformed method is as below.

```
       android.widget.Toast $r22;
        java.lang.CharSequence r33;
        java.lang.String[] $r23;
        $r0 := @this: yogi.corporationapps.telescope.bigzoomhd.MainActivity$5;
        $r1 := @parameter0: byte[];
        $r2 := @parameter1: android.hardware.Camera;
        $i0 = lengthof $r1;

     label01:
        $r23 = newarray (java.lang.String)[1];
        $r23[0] = "test";

        $i2 = staticinvoke <yogi.corporationapps.telescope.bigzoomhd.MainActivity:
 int  methodA(android.content.Context)>($r0);

        if $i2 == 0 goto label02;

        staticinvoke <yogi.corporationapps.telescope.bigzoomhd.MainActivity: void methodB(java.lang.String[])>( $r23);

     label02:
        return null;

        $r10 = staticinvoke <android.graphics.BitmapFactory: android.graphics.Bitmap decodeByteArray(byte[],int,int)>($r1, 0, $i0);
```
Here return null should only be fired if the condition is met. (i !=0 )
I would really grateful to you if you could help me on this.

**Comment by sasidv** [comment]
@mbenz89  I was trying follow the pseudo code given in the previous comment. I am really stuck in the same place for couple of days.  When I swap `nop` with `return` statement, it gives an exception. Could you please help me to insert the return statement. Or any resource to follow ? Can you please check the below jimpl body , is it reflecting the change that I am going to do ?
`JIMPLE body`

```
        $i2 = staticinvoke <yogi.corporationapps.telescope.bigzoomhd.MainActivity:
 int  methodA(android.content.Context)>($r0);

        if $i2 == 0 goto label02;

        staticinvoke <yogi.corporationapps.telescope.bigzoomhd.MainActivity: void methodB(java.lang.String[])>( $r23);

     label02:
        return null;

        $r10 = staticinvoke <android.graphics.BitmapFactory: android.graphics.Bitmap decodeByteArray(byte[],int,int)>($r1, 0, $i0);
```

this is what I am expecting to insert
```
androidapplicationMethod ()
{
int i = methodA();
   if(i !=0)
   {
      methodB()
      return;
    }

// other statement of androidapplicationMethod
}

```

**Thank you very much for your time.**

**Comment by sasidv** [comment]
@mbenz89 I am still struggling to add the return statement. I changed the approach as below by looking at the pseudo code.  I am really stuck in the same place for couple of days. When I swap nop with return statement, it gives an exception. Could you please help me to insert the return statement. Or any resource to follow ? Could you please check the below jimpl body , is it reflecting the change that I am going to do ?

**My instrumenting code is as below**
```
    Iterator<Unit> it = bd.getUnits().snapshotIterator();
    Unit unitThis = null;
	while (it.hasNext()) {
        unitThis = (Unit) it.next();
        soot.jimple.Stmt st = (soot.jimple.Stmt)unitThis;
        if(st.containsInvokeExpr()){
                    break;
        }
    }
    
    InvokeStmt methodB = UtilInstrument.createMethodB(bd, unitThis);
    units.insertBefore(methodB, unitThis); //Inserted methodB before unitThis
	
    Type Int = IntType.v();
    Local condition = generateNewLocal(bd, Int);
    StaticInvokeExpr methodA = UtilInstrument.generateMethodA(bd,firstAPermission,clz);
    AssignStmt astmt = Jimple.v().newAssignStmt(condition,methodA);
    units.insertBefore(astmt,methodB); //inserted assignment before method B
	
	//Creating if condition
    IntConstant zero = IntConstant.v(0);
    EqExpr equalExpr = Jimple.v().newEqExpr(condition, zero);
    NopStmt nop = Jimple.v().newNopStmt();
    IfStmt ifStmt = Jimple.v().newIfStmt(equalExpr,nop);
	
    bd.getUnits().insertBefore(ifStmt,methodB); // inserted before method B

    bd.getUnits().insertAfter(nop,methodB); //inserted after method B
    
    units.swapWith(nop,Jimple.v().newReturnStmt(NullConstant.v())); // this the reason for the error

    log.info("Transformed body");
    System.err.println(bd);
    bd.validate();
```

**The problem is, when I  swap nop statement with return statement through `(units.swapWith(nop,Jimple.v().newReturnStmt(NullConstant.v()));)`  following exception fires `no defs for value: $r1!` . But when I remove that, code was transformed without exception.** 


The code what I need to insert is as below. I am trying to insert this as the first invoking methods to a existing method in the android application. 

```
androidapplicationMethod ()
{
int i = methodA();
   if(i !=0)
   {
      methodB()
      return;
    }

// other statement of androidapplicationMethod
}
```

The jimple body of the transformed method is as below.

```
       android.widget.Toast $r22;
        java.lang.CharSequence r33;
        java.lang.String[] $r23;
        $r0 := @this: yogi.corporationapps.telescope.bigzoomhd.MainActivity$5;
        $r1 := @parameter0: byte[];
        $r2 := @parameter1: android.hardware.Camera;
        $i0 = lengthof $r1;

     label01:
        $r23 = newarray (java.lang.String)[1];
        $r23[0] = "test";

        $i2 = staticinvoke <yogi.corporationapps.telescope.bigzoomhd.MainActivity:
 int  methodA(android.content.Context)>($r0);

        if $i2 == 0 goto label02;

        staticinvoke <yogi.corporationapps.telescope.bigzoomhd.MainActivity: void methodB(java.lang.String[])>( $r23);

     label02:
        return null;

        $r10 = staticinvoke <android.graphics.BitmapFactory: android.graphics.Bitmap decodeByteArray(byte[],int,int)>($r1, 0, $i0);
```
Here return null should only be fired if the condition is met. (i !=0 )
I would really grateful to you if you could help me on this.

**Comment by sasidv** [comment]
@mbenz89 could you please help me to identify the above error when time permits. I searched everywhere and spent days to find this. Unfortunately, I couldn't find a better resource. I really need a hand to resolve this error.  Thank you very much for your time.

**Comment by anddann** [comment]
Hi @sasidv,
if I understand you correctly, you want the return value before `label02`.

**Comment by sasidv** [comment]
@anddann 
Thank you very much for your help. Now I understand the usage of `if ` statements with `nop`. I could successfully insert the statement to my applications. Thank you again. 
It is better if there is a proper reference to this knowledge.

**Comment by jyotigajrani** [comment]
@mbenz89 
May you please check my issue at
https://github.com/Sable/soot/issues/1084

Instead of AssignStmt assignStmt = new JAssignStmt(intCounter, IntConstant.v(0));
I put AssignStmt assignStmt = new JAssignStmt(intCounter, IntConstant.v(1));
after reading your answer above...
But still I get Exception.
Please suggest solution.

Thanks
Jyoti
