### ISSUE TITLE
graph constructed improperly for "catch(Exception)"

### ISSUE THREAD

**Issue by Waldo1637** [Sable/soot#829]
Consider the following input source:
```java
public class TestFile {
    public static void main(String[] args) {
        try {
            throw new UnsupportedOperationException();
        } catch (Exception ex) {
            System.out.println("Exception");
        }
    }
}
```
Run with the following command: `java -jar soot-trunk.jar -pp -cp . -w -allow-phantom-refs -no-bodies-for-excluded -dump-cfg ALL TestFile`
It produces the following graph (`NOPHASE-ExceptionalUnitGraph-3.dot`):
![image](https://user-images.githubusercontent.com/4001421/32795451-533006a6-c931-11e7-91fa-6779e46f8e22.png)
Notice how the "throw" statement itself does not even reach the "catch". Similarly, the exceptional edges that do exist don't list any caught exceptions.

Below is the expected graph where exceptions from the "throw" statement and the "init" statement are directed to the "catch" block. 
![image](https://user-images.githubusercontent.com/4001421/32795843-9712c8f8-c932-11e7-82ef-f8a65ab812a2.png)

The second graph is generated by adding `addBasicClass("java.lang.Exception");` to `Scene#addSootBasicClasses()`.
Is that addition safe/correct? I wonder if not including "java.lang.Exception" as a basic class was intentional or an oversight.

However, I'm also not sure if that addition is sufficient. Could it be possible for a similar condition to happen with a user-defined class (which obviously could not be added as a "basic class")?
I believe an alternative (more general) fix might be to adjust the logic in `ThrowableSet#whichCatchableAs(RefType)` specifically near the comments "If the current type is a phantom type, we catch it if and only if it is in the inclusion list and ignore any hierarchy." It's unclear to me why the hierarchy (i.e. AnySubType) should be ignored for a phantom class. Couldn't AnySubType still be used as long as the class has been resolved to the "HIERARCHY" level?

**Comment by ericbodden** [comment]
Hi Timothy.

Does this also happen when you do not use -no-bodies-for-excluded ?

My hypothesis is that this option causes Soot to not load the entire type hierarchy required to resolve the exceptional flows correctly. This also seems to be backed by your observation regarding addSootBasicClasses.

Yet, it seems odd that Exception is not by default a basic class. I think it should be and we should fix this.

Cheers
Eric

**Comment by ericbodden** [comment]
I just had a look:

The class Scene contains:

		addBasicClass("java.lang.Exception", SootClass.SIGNATURES);

Is that not executed in your case?

Cheers
Eric

**Comment by Waldo1637** [comment]
Oh, you're right. It looks like it was added just a month ago and I was using an older version. Sorry for the trouble.
