### ISSUE TITLE
System's class not loaded?

### ISSUE THREAD

**Issue by koradir** [Sable/soot#833]
`
        Scene.v().loadClassAndSupport(System.class.getName());`
        `SootClass system = Scene.v().getSootClass(System.class.getName());`
        `System.out.println(system.getFields());System.out.flush();
`

prints `[]`

Why? And how do I get it loaded?

**Comment by anddann** [comment]
Hi @koradir,
I've tried the code you posted above with JDK 1.8_151 and it works on my machine.
Do you use any additional classpath entries?

**Comment by anddann** [comment]
No response after 2 years. I guess the issue is solved.
