### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by wuwenjia** [Sable/soot#839]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-force-android-jar /Users/li.li/Project/github/android-platforms/android-18/android.jar -process-dir /home/xiaowu/iccta/DroidRA-master/benchmark-apps/eclipse-projects/Reflection_Reflection5 -ire -pp -keep-line-number -allow-phantom-refs -src-prec apk -w -d testspace/Reflection_Reflection5.apk/retargeted/retargeted/Reflection_Reflection5

Max Memory:
7282MB

Stack trace:
java.lang.RuntimeException: file '/Users/li.li/Project/github/android-platforms/android-18/android.jar' does not exist!
	at soot.Scene.defaultClassPath(Scene.java:505)
	at soot.Scene.getSootClassPath(Scene.java:230)
	at soot.SootResolver.<init>(SootResolver.java:82)
	at soot.Singletons.soot_SootResolver(Singletons.java:802)
	at soot.SootResolver.v(SootResolver.java:92)
	at soot.Scene.tryLoadClass(Scene.java:661)
	at soot.Scene.loadBasicClasses(Scene.java:1258)
	at soot.Scene.loadNecessaryClasses(Scene.java:1337)
	at soot.Main.run(Main.java:214)
	at soot.Main.main(Main.java:152)
	at RetargetedApp.main(RetargetedApp.java:24)
in a word,i don't know where is the command '/Users/li.li/Project/github/android-platforms/android-18/android.jar' .

**Comment by maldil** [comment]
You need to give android platform jar to the location` /Users/li.li/Project/github/android-platforms/android-18/` You can find those from [this locatoin](https://github.com/Sable/android-platforms) only up to 17. For others you can use stub jars downloaded from  SDK manager.

**Comment by wuwenjia** [comment]
@maldil ，there is a new issue when i use IccTA.
![qx7b _8x7qo 4y zig6 a](https://user-images.githubusercontent.com/28593292/33609503-5350ed2a-da03-11e7-919b-2eb6181655f3.png)

**Comment by mbenz89** [comment]
IccTA is part of FlowDroid. Please refer to [soot-infoflow-android](https://github.com/secure-software-engineering/soot-infoflow-android) to clarify this issue.
