### ISSUE TITLE
DroidRA

### ISSUE THREAD

**Issue by wuwenjia** [Sable/soot#840]
I want to know how to implement DroidRA ,[there is](https://github.com/serval-snt-uni-lu/DroidRA) no detail introduction

**Comment by mbenz89** [comment]
DroidRA is not developed/supported by us. Please contact the authors for further information on how to use it. 
FlowDroid also has an option to resolve reflective calls where it is statically possible by doing interprocedural constant propagation. Be aware of the fact that this of course just works for targets that can be evaluated by constant propagation, i.e., which are stated in code as strings and are not generated by complex operations.
