### ISSUE TITLE
Soot Method Contents.

### ISSUE THREAD

**Issue by arvind4141** [Sable/soot#841]
Hello,
Based on a given method, how do I proceed to find possible fields or methods that within a single soot Method. Technically, I would like to know would it be possible to retrieve the 'contents' of a Soot Method. 

Thank you for your reply.

**Comment by maldil** [comment]
If I understood your problem correctly, you need to iterate the body of the method.
```
SootMethod sm = Scene.v().getMethod("method");

Body bd = sm.retrieveActiveBody();
Iterator<Unit> it = bd.getUnits().snapshotIterator();
while (it.hasNext()) { 

            }
```
bd.getLocals() // use this to have locals 

You can have an idea on fundamental soot objects from https://github.com/Sable/soot/wiki/Fundamental-Soot-objects

**Comment by arvind4141** [comment]
Thank you @maldil for your reply. I understand the concept behind your reply, but it seems that I've run into another issue which is no method source being set for that specific I would like to retrieve its 'contents'. How do I go about solving this? Thank you so much!

Exception in thread "main" java.lang.RuntimeException: No method source set for method <com.cordova.plugins.sms.Sms: void send(org.apache.cordova.CallbackContext,java.lang.String,java.lang.String)>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at project.Taint_Manager.plugins_discover(Taint_Manager.java:24)
	at _project.Main.main(Main.java:67)

**Comment by maldil** [comment]
Their could be several reasons. Please check whether the method is a phantom method `sm.sm.isPhantom() `?
Likewise, there could be more. Please share the soot configurations.

**Comment by arvind4141** [comment]
It seems that the method was a phantom method. Issue is solved. Thank you.
