### ISSUE TITLE
Using Soot / Info-flow to generate callgraph successful, but...

### ISSUE THREAD

**Issue by arvind4141** [Sable/soot#843]
Hello,
I've managed to generate a callgraph successfully based on the below code.

       SetupApplication app = new SetupApplication
                ("C:\\Tools\\AndroidSDK\\platforms",
                        "./app_stuff/HybridCalculator.apk");
        app.calculateSourcesSinksEntrypoints("./app_stuff/SourcesAndSinks.txt");
        soot.G.reset();

        Options.v().set_src_prec(Options.src_prec_apk);
        Options.v().set_process_dir(Collections.singletonList("./app_stuff/HybridCalculator.apk"));
        Options.v().set_android_jars("C:\\Tools\\AndroidSDK\\platforms");
        Options.v().set_whole_program(true);
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_output_format(Options.output_format_class);
        Options.v().setPhaseOption("cg.cha", "on");
        Options.v().setPhaseOption("cg.cha", "apponly:true");

        Scene.v().loadNecessaryClasses();

        SootMethod entryPoint = app.getEntryPointCreator().createDummyMain();
        Options.v().set_main_class(entryPoint.getSignature());
        Scene.v().setEntryPoints(Collections.singletonList(entryPoint));
        System.out.println(entryPoint.getActiveBody());

        PackManager.v().runPacks();
        System.out.println(Scene.v().getCallGraph().size());

How do I programmatically call upon soot info-flow or flowdroid to conduct "**taint analysis**" on the above result callgraph (if this is even possible?) I have all my libraries(soot,info-flow,info-flowandroid etc), sourcessinks,callbacks.txt files in place.

I just cant seem to find a way to programmatically call upon flowdroid/info-flow to conduct **"taint analysis"**. Any help would be greatly appreciated. 
Thank you!

**Comment by linghui2016** [comment]
If you want to conduct "taint analysis" written by yourself you should add the analysis to "wtjp" pack and apply it as follows:

```
PackManager.v().getPack("wjtp").add(new Transform("wjtp.taintanalysis", createAnalysisTransformer()));
PackManager.v().getPack("wjtp").apply();

private Transformer createAnalysisTransformer() {
		return new SceneTransformer() {
			@Override
			protected void internalTransform(String phaseName, Map<String, String> options) {
				BiDiInterproceduralCFG<Unit, SootMethod> icfg=new JimpleBasedInterproceduralCFG(true);
				TaintAnalysis analysis = new TaintAnalysis(icfg);// you must implement it by yourself
				analysis.doAnalysis();
			}
		};
	}

```

**Comment by mbenz89** [comment]
am not quite sure I get your question. If you want to use FlowDroid for tain analysis it is sufficient to call `soot.jimple.infoflow.android.SetupApplication#runInfoflow(soot.jimple.infoflow.source.data.ISourceSinkDefinitionProvider)` or either of the other runInfoFlow methods. FlowDroid will generate the needed call graph internally, so there is no need to create it beforehand. Using the `constructCallGraph` method is a convenient way to generate a call graph with FlowDroid without having to use its taint analysis feature.

**Comment by arvind4141** [comment]
@linghui2016 @mbenz89 Thank you very much for the input, I appreciate it. I've managed to solve the issue.
