### ISSUE TITLE
Soot Android Instrumentation.

### ISSUE THREAD

**Issue by arvind4141** [Sable/soot#845]
Hello, I've followed the Android Instrumentation from here:

> https://github.com/Sable/soot/wiki/Instrumenting-Android-Apps-with-Soot

However, during the compilation process, no exceptions were thrown none whatsoever and thus it wassuccessful. But when I attempt to install run the instrumented application - it's stated as being 'corrupted' by the OS.

Any idea on how I can overcome this?
Is the example above outdated? 

@mbenz89 @StevenArzt 

Thank you for the help.

**Comment by maldil** [comment]
You may need to run it in an emulator and get the stack trace. Then only people may need to help you. (Y)

**Comment by arvind4141** [comment]
@maldil The issue may seem vague, but I strongly believe it's my code method segment where my configuration settings for Soot, callgraph generation and instrumentation are lumped together. This is due to the fact that APK I'm instrumenting on is a very basic HelloWorld application. I've seen from previous issues that you've managed to resolve your issue with Instrumentation. It would be great if you could share your code segment of sootconfig / instrumentation / callgraph generation so that I can use that as a reference point if its possible with you.

Thank you.

**Comment by arvind4141** [comment]
Case closed. For anyone who encounters the same issue as me, it could be due to your API level. This can be mitigated by:

    Options.v().set_android_api_version(23);

Thank you.
