### ISSUE TITLE
Cannot pull soot as a dependency

### ISSUE THREAD

**Issue by chandanrrk** [Sable/soot#846]
Two related issues:
1. Looks like maven repo at https://soot-build.cs.uni-paderborn.de/nexus/ is down.
2. Also the direct download URL at https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/ is unreachable.

**Comment by mbenz89** [comment]
Servers are up and running again. Sorry for any inconveniences caused.
