### ISSUE TITLE
Help is needed when Using Scene.v().getMethod without constructing the call graph 

### ISSUE THREAD

**Issue by maldil** [Sable/soot#849]
`Scene.v().getMethod` can be used to retrieve a method and analyze it's properties. If the method is not found, it fires the following exception.
`java.lang.RuntimeException: tried to get nonexistent method `

My question is how to load the classes and methods of the application without constructing the call graph?
I did few analysis on this to load the classes using following methods, but non of them fixed the problem.
```
Scene.v().loadNecessaryClasses();
Scene.v().loadBasicClasses();
Scene.v().loadDynamicClasses();  
```
If the method Scene.v().getMethod("") is called **after** constructing the callgraph, the above exception will not be fired. My question is, **how to solve the exception without constructing the call graph** ?

**Comment by maldil** [comment]
@mbenz89 I would be really grateful, if you could help me on this.

**Comment by anddann** [comment]
Hi  @maldil 
it looks like the SootClasses are not fully resovled.
To get all Bodies either run `PackManager.v().runPacks()` this also executes the cfg or
run `Scene.v().forceResolve("KLASSNAME", SootClass.BODIES)`
Hope this helps.

**Comment by maldil** [comment]
@anddann 
Thank you very much  for the help. I called the method `PackManager.v().runPacks()` before calling the method `Scene.v().getMethod`. But the exception is fired again. Can I know whether the `PackManager.v().runPacks()`  load all the classes in the android application as well as the .jar files in the class path ? Is there any difference when loading the class using `constructCallgraph `and `PackManager.v().runPacks()` ?

**Comment by anddann** [comment]
Of which class do you want to get the methods?

**Comment by maldil** [comment]
@anddann thanks for your attention on this. 
Currently I am trying to get a method in android application. This is the current problem.

**But later,** I need to get a method in a .jar file which I am trying to upload to Soot by updating the class path.

**Comment by gnom7** [comment]
Hello, to kick off `cg` phase with `PackManager.v().runPacks()` try to call at first either `Options.v().set_whole_program(true)` or `Options.v().set_whole_shimple(true)`.
Anyway it seems to me that `Scene.v().forceResolve(sootClass.getName(), SootClass.BODIES)` is better to use (at least it should be faster and will only resolve the class to the desired level without applying some transform packs you might not need to).

**Comment by maldil** [comment]
@gnom7 thank you for the update.
