### ISSUE TITLE
Checkstyle

### ISSUE THREAD

**Issue by gnom7** [Sable/soot#851]
Hello, can we please add `checkstyle` to the project to enforce one programming style?

**Comment by mbenz89** [comment]
We have plans to do that but I haven't found the time to set this up properly yet.

**Comment by hubertp** [comment]
Would something like that work for you?
https://github.com/hubertp/soot/tree/hubertp/checkstyle

The problem is the sheer amount of violations. ~500000 would mean a lot of code changes. But it seems to me necessary in the long term.

**Comment by mbenz89** [comment]
Closed due to duplicate #812
