### ISSUE TITLE
Assigning one local to another.

### ISSUE THREAD

**Issue by arvind4141** [Sable/soot#859]
Hello, based on the code below I've created two locals.

        Local jArray_standard = addJSON(body);
        jArray_standard = Jimple.v().newLocal("jArray_standard", RefType.v("org.json.JSONArray"));
        body.getLocals().add(jArray_standard);

        Local jArray_standard2 = addJSON(body);
        jArray_standard2 = Jimple.v().newLocal("jArray_standard2", RefType.v("org.json.JSONArray"));
        body.getLocals().add(jArray_standard2);

 I then proceed to initialise the first local.

       Unit t1 = Jimple.v().newAssignStmt(jArray_standard, 
       Jimple.v().newNewExpr(RefType.v("org.json.JSONArray")));
       Unit t2 = Jimple.v().newInvokeStmt(Jimple.v().newSpecialInvokeExpr(jArray_standard, 
       Scene.v().getMethod("<org.json.JSONArray: void <init>()>").makeRef()));
       chain.add(t1);
       chain.add(t2);

Now how do I go about assigning the local jArray_standard2 to jArray_standard?
Such that in the jimple code it looks like this:
       jArray_standard2 = jArray_standard;

 Should I use **Unit t6 = Jimple.v().newAssignStmt(jArray_standard2,jArray_standard);**?

Thank you for the reply!
@mbenz89 @StevenArzt @ericbodden

**Comment by mbenz89** [comment]
Yes, that's correct. Please make sure to try such simple things first before making an issue here next time.
