### ISSUE TITLE
Whole Program mode and Polyglot version

### ISSUE THREAD

**Issue by bereal** [Sable/soot#862]
I tried to run the `SimpleMethodInfoFlowAnalysis` using the code below: 

      PackManager.v().getPack("jap").add(
                new Transform("jap.myTransform", new BodyTransformer() {
                    @Override
                    protected void internalTransform(Body b, String phaseName, Map<String, String> options) {
                        ExceptionalUnitGraph g = new ExceptionalUnitGraph(b);
                        InfoFlowAnalysis flow = new InfoFlowAnalysis(true, true);
                        SimpleMethodInfoFlowAnalysis lmna = new SimpleMethodInfoFlowAnalysis(g, flow, true);
                    }

                }));

then it failed with:

    ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: No call graph present in Scene. Maybe you want Whole Program mode (-w).
    java.lang.RuntimeException: No call graph present in Scene. Maybe you want Whole Program mode (-w).
	at soot.Scene.getCallGraph(Scene.java:1222)

When I add `-w` to `soot.Main.main`, it fails with:

    soot.SootResolver$SootClassNotFoundException: couldn't find class: polyglot.frontend.Pass$ID (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:228)

I downloaded the latest version of Polyglot and added to the classpath to no success, then I went to the Polyglot repository to find that `Pass$ID` was [removed from it in 2005](https://github.com/polyglot-compiler/polyglot/commit/460198f7dafd40807a1a1102de85572ab3bdeb9d#diff-d21cfa45d16a46e5c74457f35cadc4aa). Should I use that old version of Polyglot, or am I missing something else?

**Comment by mbenz89** [comment]
What are you trying to analyze? This error is not caused by a missing dependency of Soot but rather the missing of the polyglot classes in your class path. If the application you are trying to analyze does not use polyglot, chances are high you are falsely trying to analyze Soot itself. 

In general, if you want to analyze some code without having all dependencies in the class path, you can set -allow-phantom-refs to use stubs for the missing code.

Could you post your configuration of Soot?

**Comment by bereal** [comment]
@mbenz89 thank you, that helped. I was analysing a program with itself, so that must have been somehow related. Analysing something else works fine, as well as setting `-allog-phantom-refs`.
