### ISSUE TITLE
Unexpected Nullpointer Exception thrown in FieldRefValidator

### ISSUE THREAD

**Issue by mjblackhorse** [Sable/soot#865]
An unexpected Nullpointer Exception would be thrown in the method validate() of FieldRefValidator

`	public void validate(Body body, List<ValidationException> exception) {
		SootMethod method = body.getMethod();
		if (method.isAbstract())
			return;
		
		Chain<Unit> units = body.getUnits().getNonPatchingChain();

		for (Unit unit : units) {
			Stmt s = (Stmt) unit;
			if (!s.containsFieldRef()) {
				continue;
			}
			FieldRef fr = s.getFieldRef();

			if (fr instanceof StaticFieldRef) {
				StaticFieldRef v = (StaticFieldRef) fr;
				try {
					SootField field = v.getField();
					if (field == null)
						exception.add(new UnitValidationException(unit, body, "Resolved field is null: " + fr.toString()));

					if (!field.isStatic() && !field.isPhantom()) {// Nullpointer exception would be thrown if field==null
						exception.add(new UnitValidationException(unit, body, "Trying to get a static field which is non-static: " + v));
					}
				} catch (ResolutionFailedException e) {
					exception.add(new UnitValidationException(unit, body, "Trying to get a static field which is non-static: " + v));
				}
			} else if (fr instanceof InstanceFieldRef) {
				InstanceFieldRef v = (InstanceFieldRef) fr;

				try {
					SootField field = v.getField();
					if (field == null)
						exception.add(new UnitValidationException(unit, body, "Resolved field is null: " + fr.toString()));
					
					if (field.isStatic() && !field.isPhantom()) {// Nullpointer exception would be thrown if field==null
						exception.add(new UnitValidationException(unit, body, "Trying to get an instance field which is static: " + v));
					}
				} catch (ResolutionFailedException e) {
					exception.add(new UnitValidationException(unit, body, "Trying to get an instance field which is static: " + v));
				}
			} else {
				throw new RuntimeException("unknown field ref");
			}
		}
    }`

**Comment by mbenz89** [comment]
It's hard to track down such error without knowing your configuration and input data, i.e., the classes you are analyzing.

**Comment by mjblackhorse** [comment]
I found that the bug was fixed in the updated version.
The issue should be closed.

Thank you!
