### ISSUE TITLE
Dependency Issue com.google.common.reflect

### ISSUE THREAD

**Issue by Trigon** [Sable/soot#869]
I use a [parser](https://github.com/pcj/google-options) which used Google's `guava` version 19.
And there is a conflict in the class `TypeToken` in the package `com.google.common.reflect`
I think the version of `com.google.common.reflect`  in soot may be too old?

Thank you very much

**Comment by mbenz89** [comment]
I've updated the guava version to 19. Generally, you can always use mavens exclude feature to exclude dependencies you do not need or to replace them with your own.
