### ISSUE TITLE
Unresolved Dependencies when using maven

### ISSUE THREAD

**Issue by florian-kuebler** [Sable/soot#880]
I tried to obtain the current soot snapshot using maven. Unfortunately the required dependencies to
**polyglot** and **java_cup** are neither in maven central nor in the soot-snapshot repository.

Currently I add the corresponding jars manually to my local maven repository which works, but is quiet inconvenient.

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: ca.mcgill.sable#polyglot;2006: not found
[warn] 	:: ca.mcgill.sable#java_cup;0.9.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by anddann** [comment]
Can you please post your `pom.xml` and the output of `mvn dependency:tree`

**Comment by florian-kuebler** [comment]
Well I use soot via the [SootConfig](https://github.com/stg-tud/sootconfig) project using sbt.
So my build.sbt file looks like this:
```
name := "simple-test"

version := "0.1"

scalaVersion := "2.12.4"

resolvers += Resolver.mavenLocal

resolvers += "soot snapshot" at "https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/"

libraryDependencies += "de.tu-darmstadt.stg" % "sootconfig" % "1.1"
```

The pom.xml of SootConfig can be found [here](https://github.com/stg-tud/sootconfig/blob/master/pom.xml).

The output of `mvn -version` is:
```
mvn -version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```

And finally the output of `mvn dependency:tree` in the SootConfig project prints:
```
[INFO] de.tu-darmstadt.stg:sootconfig:jar:1.1
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] +- ca.mcgill.sable:soot:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- org.smali:dexlib2:jar:2.2.2:compile
[INFO] |  |  +- org.smali:util:jar:2.2.2:compile
[INFO] |  |  |  \- com.beust:jcommander:jar:1.64:compile
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  +- org.ow2.asm:asm-debug-all:jar:5.2:compile
[INFO] |  +- xmlpull:xmlpull:jar:1.1.3.4d_b4_min:compile
[INFO] |  +- org.jboss:jboss-common-core:jar:2.5.0.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging-spi:jar:2.1.2.GA:compile
[INFO] |  +- pxb.android:axml:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- ca.mcgill.sable:polyglot:jar:2006:compile
[INFO] |  +- heros:heros:jar:1.0.0-SNAPSHOT:compile
[INFO] |  |  \- org.functionaljava:functionaljava:jar:4.2:compile
[INFO] |  +- ca.mcgill.sable:jasmin:jar:3.0.0-SNAPSHOT:compile
[INFO] |  |  \- ca.mcgill.sable:java_cup:jar:0.9.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO] |  \- org.slf4j:slf4j-simple:jar:1.7.5:compile
[INFO] \- com.google.guava:guava:jar:20.0:compile
```

**Comment by anantoni** [comment]
I don't know if my case helps you, but I had the same problem with my build.gradle file. Due to the fact that the polyglot and java_cup versions are release versions, I had to a "soot releases" resolver in my build.gradle with the release url: "https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/".

**Comment by florian-kuebler** [comment]
I deleted my local maven repo (which contained the jars of polyglot and java_cup added by hand) and cloned the SootConfig project by hand in order to provide you with the output of `mvn dependency:tree `. 
Afterwards the local maven repo contained the two projects and my sbt project worked. 

So it seems to be the case that maven is able to retrieve the dependencies to java_cup and polyglot and add them into the local maven repository, where sbt is not.

For me it is unclear where these two jars come from and why sbt is not able to retrieve them while having no problem to retrieve the rest of the dependencies.

**Comment by anddann** [comment]
Thanks @anantoni. That is the answer
I added `resolvers += "soot release" at "https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/"`

**Comment by mbenz89** [comment]
Our snapshot repository does only allow the handling of snapshot builds which java_cups is not. Generally, when using Soot's develop builds, one needs both repositories to resolve all dependencies. However, if Soot is used as a dependency, it should be sufficient to include either snapshot or release (depending if you want to use a specific release or the latest development build) since Soot's pom will take care of the underlying dependencies.

We might introduce a facade which lets both repositories appear as one to the outside, or even add the dependencies to maven central in the future.

**Comment by anddann** [comment]
Since soot and its dependencies are now available at maven central
```
  <dependency>
    <groupId>ca.mcgill.sable</groupId>
    <artifactId>soot</artifactId>
    <version>4.0.0</version>
  </dependency>
```
