### ISSUE TITLE
How to Generate PDG from JAVA Souce Code with soot?

### ISSUE THREAD

**Issue by adi-dhal** [Sable/soot#891]
I am having a hard time figuring out to export a PDG of java source code with soot

**Comment by mbenz89** [comment]
First of all, Soot's Java frontend is heavily outdated and I suggest you use the bytecode frontend. Second, I do not think there is an implementation of PDG's in Soot. We would be happy to accept an implementation if you propose a pull request for the feature.

Anyway, this is an issue tracker, please post your question on the Soot mailing list if it still persists.
