### ISSUE TITLE
Failed to load java.lang.CharSequence error

### ISSUE THREAD

**Issue by Gv1504** [Sable/soot#896]
I tried to run this command using Java version 8 on windows. 

```java -cp soot.jar soot.Main -cp ".;C:\Program Files\Java\jre1.8.0_151\lib\rt.jar" Example_4```

I keep getting: 
```Exception in thread "main" java.lang.Error: Error: Failed to load java.lang.CharSequence.``` This happens only when I have lines like System.out.print as part of my source code. Otherwise it works fine.

Source code 
```
package ExampleCodes;

public class Example_4
{
    public static void main(String[] args)
    {
        int a = 10;
        
	a++;

        if(a<10)
            a--;
        else
            a++;
	int b = a + a;
        System.out.println(a);
    }
}

```

**Comment by vmark99** [comment]
I've got the same issue. It happens when using Java functions in the class, like 
```
System.out.println();
```

Using JDK 1.8 and the latest nightly build.

**Comment by Gongxter** [comment]
Hi, so i had the same problem.
So for me the Problem got fixed by downloading and installing JDK 7u80 and setting the project SDK to this JDK7.
If you still have this problem give it a try.

**Comment by legendtang** [comment]
I've met the same issue.
https://gist.github.com/kymtwyf/a2eb7729534c776c7f0dfbc4d515632d
It is said switching to older versions can resolve the issue. But since soot is going to support Java 9, why this is still a problem?

**Comment by vmark99** [comment]
Yes, is there a solution to make it work with Java 8? 

If I compile the code to .class and run with Java 8, it works. But I can't seem to run it with .java files using Java 8.

**Comment by mbenz89** [comment]
As far as I understand, you are trying to analyze the java files directly? If so, you really should run your analysis on the class files. Soot's Java frontend is heavily outdated and I strongly discourage from its usage.

**Comment by legendtang** [comment]
@mbenz89 Thank you. Yes it works with class files. I do suggest the document should be updated to address deprecation of analyzing java files, which is somehow a little bit misleading.

**Comment by zhangysh1995** [comment]
I ran Soot directly on Java files and got the this exception. Changed to JDK7 solves the problem. I also recommend to update the docs.

**Comment by mcfatealan** [comment]
I ran into this issue when parsing there are other java files in the target directory that do not have corresponding .class files. No need to degrade to java7 actually.
