### ISSUE TITLE
Missing phase in pom.xml?

### ISSUE THREAD

**Issue by Alexandre-Bartel** [Sable/soot#908]
When I import Soot in Eclipse (following the instructions [here](https://github.com/Sable/soot/wiki/Building-Soot-with-Eclipse)) I get the following Error in pom.xml pointing at line 32:

> Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:xml-maven-plugin:1.0.1:transform (execution: default, phase: generate-resources)

```
		<finalName>sootclasses-trunk</finalName>

		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>xml-maven-plugin</artifactId>
				<version>${xml-maven-plugin.version}</version>
				<executions>
					<execution> <------------------------------- line 32
						<goals>
							<goal>transform</goal>
						</goals>
					</execution>
				</executions>
```

The fix consists in adding a phase within the execution block.

```
		<finalName>sootclasses-trunk</finalName>

		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>xml-maven-plugin</artifactId>
				<version>${xml-maven-plugin.version}</version>
				<executions>
					<execution>
						<phase>initialize-build</phase> <-------------------- new phase here
						<goals>
							<goal>transform</goal>
						</goals>
					</execution>
				</executions>
```

Is that the right phase?

**Comment by StevenArzt** [comment]
The plugin is configured to run in the generate-resources phase. This phase is not active by default. Your fix essentially moves the plugin to a different phase, which is executed by default. I'm not quite sure how that influences the build, i.e.,, whether things are still built in the right order. The phase that Soot normally uses is semantically valid for the given purpose, so I'd rather keep that. The correct fix for the Eclipse error would thus be to change your Eclipse configuration to enable the generate-resources phase.

**Comment by Alexandre-Bartel** [comment]
Is the generate-resources phase ever needed within Eclipse? I guess it is not. Following [this](https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html), I ended up adding the following  xml code (automatically generated by Eclipse in a quick fix) to the pom.xml file to make m2e happy:

```
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.codehaus.mojo
										</groupId>
										<artifactId>
											xml-maven-plugin
										</artifactId>
										<versionRange>
											[1.0.1,)
										</versionRange>
										<goals>
											<goal>transform</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
```

Do you mind if I add this to the pom.xml? Otherwise, the first thing a user importing Soot in the latest version of Eclipse sees is an error message.

**Comment by mbenz89** [comment]
The generate-resource phase is needed to create the option-classes. If we exclude it by default, users might run into unexpected issues when modifying the options. Isn't there any way to make Eclipse properly handle this phase?

**Comment by ericbodden** [comment]
Any insights on this?

**Comment by trickerkaim** [comment]
**I just Imported Soot in Eclipse as a team project set from the [link] (https://raw.github.com/Sable/soot/develop/soot.psf) In which i am getting error in pom.xml at line 135. Can you help me out why is it showing this error.**

	

> - Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-
	 resources-plugin:3.0.2:resources (execution: default-resources, phase: process-resources)

> - Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-
resources-plugin:3.0.2:testResources (execution: default-testResources, phase: process-test-resources)


                      <plugin>                                
				<artifactId>maven-resources-plugin</artifactId>
				<version>${maven-resources-plugin.version}</version>
				<executions>
					<execution>                
						<id>copy-resources</id>
						
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/doc</outputDirectory>
							<resources>
								<resource>
									<directory>${basedir}/src/main/xml/options/</directory>
									<includes>
										<include>soot_options.css</include>
									</includes>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by mbenz89** [comment]
@StevenArzt how do you cope with this in eclipse? I would rather not like to pollute the `pom` with IDE specific stuff. On the other hand, if this is a major pain, I would be ok with excluding the plugin for m2e and require users to generate the resources by invoking maven directly.

@trickerkaim I suggest importing Soot as a Maven project if you are not planning to change things in Heros/Jasmin.

**Comment by StevenArzt** [comment]
I cope with this situation by manually changing my Eclipse configuration to execute the custom phase. That needs to be done once per Eclipse installation, which is fine for me.

**Comment by mbenz89** [comment]
@StevenArzt Could you provide a short introduction in the wiki which we can use to point users at? Otherwise, I expect more of such issues coming up in the future.

**Comment by StevenArzt** [comment]
You essentially just need to click on the quick fix option in Eclipse and let it do the magic.

**Comment by mbenz89** [comment]
@trickerkaim can you try to activate the phase with the provided quick fix?

**Comment by trickerkaim** [comment]
@mbenz89 No quick fix is not working for me.
The error is still there

**Comment by mbenz89** [comment]
That's strange. Do you have m2e installed and everything up to date?

**Comment by trickerkaim** [comment]
Got it actually the problem was in m2e only i reinstalled it and problem was fixed

**Comment by liuyuanOUC** [comment]
@Alexandre-Bartel I meet the same error, and it workd for me, thank you.
