### ISSUE TITLE
How to get annotation in SootMethod?

### ISSUE THREAD

**Issue by LeadroyaL** [Sable/soot#919]
As title. Recently I'm doing static code analyze. When I want to get method which has annotation `JavascriptInterface`, I cannot find `annotation` member in `soot.SootMethod`. And I use jimple format.

So is there method to check whether a method have a certain annotation?
Thanks.

**Comment by pnest** [comment]
There is `soot.tagkit.AnnotationTag` that represent annotation. You can use `soot.SootMethod#getTag` to get annotation by name, or iterate through all tags on method using `soot.SootMethod#getTags`

**Comment by LeadroyaL** [comment]
Thanks! It works well.

**Comment by LeadroyaL** [comment]
```java
        boolean hasJsAnnotation = false;
        SootMethod sootMethod = Scene.v().getMethod("xxxxxxx")
        VisibilityAnnotationTag tag = (VisibilityAnnotationTag) sootMethod.getTag("VisibilityAnnotationTag");
        if (tag != null) {
            for (AnnotationTag annotation : tag.getAnnotations()) {
                if (annotation.getType().equals("Landroid/webkit/JavascriptInterface;")) {
                    hasJsAnnotation = true;
                    break;
                }
            }
        }
```

Add a simple example.
