### ISSUE TITLE
Transforming specific functions stop and instrumentation remains incomplete  

### ISSUE THREAD

**Issue by archer29m** [Sable/soot#924]
Hi everyone,

I am in the process of android application instrumentation. The problem is that for some applications and some functions, the process of transforming stops and doesn't go forward any more -- for other apps, usually small apps, it works well and instruments the app properly. 

Here is a piece of my transforming function:

``static void runMethodTransformationPack(){ 
PackManager.v().getPack("jtp").add(new
Transform("jtp.myInstrumenter", new BodyTransformer() {
@Override
protected void internalTransform(final Body b, String phaseName,
@SuppressWarnings("rawtypes") Map options) {
//My Instrrumenting stuff
}``

Actually my main purpose is to instrument some specific functions in an app, even when I put some 'if conditions' to only instrument those functions in the body of the above _runMethodTransformationPack_ function, again the transforming process stops at some specific functions -- I am not sure what is order of transforming the functions of an app in Soot. 

The following app is one of the examples that the instrumentation doesn't work and stops at the following function. I do not get any error or exception, only the process stops at the following transforming and nothing happens after that:

App: [http://i.meituan.com/mobile/down/meituan](url) 

Function: Transforming com.meituan.android.mtplayer.utils.a...

When I narrow the transforming process down to only some specific functions, the app somehow finishes the instrumentation process but when I install the signed app, it crashes with the following log:

****
--------- beginning of crash
E/AndroidRuntime(19897): FATAL EXCEPTION: main
E/AndroidRuntime(19897): Process: com.sankuai.meituan, PID: 19897
E/AndroidRuntime(19897): java.lang.RuntimeException: Unable to create application com.sankuai.meituan.MeituanApplication: java.lang.IllegalMonitorStateException: unlock of unowned monitor on object of type 'java.lang.Class<java.lang.String>' on thread 'Thread[1,tid=19897,Runnable,Thread*=0xb4827800,peer=0x73a86000,"main"]'
E/AndroidRuntime(19897): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
E/AndroidRuntime(19897): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
E/AndroidRuntime(19897): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
E/AndroidRuntime(19897): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19897): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19897): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(19897): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19897): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19897): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(19897): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(19897): Caused by: java.lang.IllegalMonitorStateException: unlock of unowned monitor on object of type 'java.lang.Class<java.lang.String>' on thread 'Thread[1,tid=19897,Runnable,Thread*=0xb4827800,peer=0x73a86000,"main"]'
E/AndroidRuntime(19897): 	at com.dianping.monitor.c.b(UtilTools.java)
E/AndroidRuntime(19897): 	at com.dianping.monitor.impl.b.<init>(CrashMonitorHelper.java)
E/AndroidRuntime(19897): 	at com.dianping.monitor.impl.b.a(CrashMonitorHelper.java)
E/AndroidRuntime(19897): 	at com.dianping.monitor.impl.a.<init>(BaseMonitorService.java)
E/AndroidRuntime(19897): 	at com.dianping.nvnetwork.e$2.<init>(NVGlobal.java)
E/AndroidRuntime(19897): 	at com.dianping.nvnetwork.e.a(NVGlobal.java)
E/AndroidRuntime(19897): 	at com.sankuai.meituan.init.v.c(NVGlobalInit.java)
E/AndroidRuntime(19897): 	at com.sankuai.meituan.MeituanApplication.onCreate(MeituanApplication.java)
E/AndroidRuntime(19897): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
E/AndroidRuntime(19897): 	at com.sankuai.meituan.arbiter.hook.HookedInstrumentation.callApplicationOnCreate(HookedInstrumentation.java)
E/AndroidRuntime(19897): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
E/AndroidRuntime(19897): 	... 9 more
W/ActivityManager( 1194):   Force finishing activity 1 com.sankuai.meituan/.activity.Welcome
I/OpenGLRenderer( 1194): Initialized EGL, version 1.4
W/GCoreFlp( 2469): No location to return for getLastLocation()
W/ActivityManager( 1194): Activity pause timeout for ActivityRecord{26b99d74 u0 com.sankuai.meituan/.activity.Welcome t2507 f}
W/ResourceType( 1738): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1738): Failure retrieving resources for com.sankuai.meituan: Resource ID #0x0
I/Process (19897): Sending signal. PID: 19897 SIG: 9
D/audio_hw_primary(  188): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
D/OpenGLRenderer( 1194): endAllStagingAnimators on 0x9f256280 (RippleDrawable) with handle 0xaefb37a0
W/InputMethodManagerService( 1194): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@3eeb6c04 attribute=null, token = android.os.BinderProxy@11f1c229
I/ActivityManager( 1194): Process com.sankuai.meituan (pid 19897) has died
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.JobSchedulerEngine$PhoneskyJobSchedulerJobService.onStartJob(9): onJobSchedulerWakeup
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.p.a(22): Scheduling fallback in 43199994 (absolute: 394380238)
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.p.a(22): Scheduling fallback in 64799995 (absolute: 415980244)
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.w.handleMessage(32): DeviceState: DeviceState{currentTime=1523047354767, isCharging=true, isIdle=false, netAny=true, netNotRoaming=true, netUnmetered=true}
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.r.a(88): Running job: 1 (12)
I/Finsky  (15292): [1] com.google.android.finsky.ah.c.a(41): ContentSyncJob started
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.r.a(160): RunningQueue size: 1
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.r.a(161): PendingQueue size: 0
I/Finsky  (15292): [3092] com.google.android.finsky.n.c.a(24): Completed 0 account content syncs with 0 successful.
I/Finsky  (15292): [1] com.google.android.finsky.ah.c.a(5): Installation state replication succeeded.
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.aq.b(12): jobFinished: 1 12
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.r.a(185): Job 1 (12) finished
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.r.a(160): RunningQueue size: 0
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.r.a(161): PendingQueue size: 0
I/Finsky  (15292): [1] com.google.android.finsky.scheduler.w.handleMessage(220): Executor finished
****

I would be really grateful if anyone can help me on this. Please let me know if you need any more details about my code or sample apps that do not work properly.

**Comment by StevenArzt** [comment]
I cannot reproduce the problem. If I run the application through Soot without making any changes to the code, Soot finishes in 1 minute and 39 seconds. Can you double-check whether there is a  bug in your instrumentation code? Run Soot with your instrumentation code in a debugger. When the program seems stuck, pause the debugger and see which code is currently running. That may give you an idea where the problem is. I suspect that your instrumentation code either takes very long or has an infinite loop. For the prob lem of the crashing app, please comment out your instrumentation code and try again. If the problem disappears, it's your instrumentation code that breaks the app.

**Comment by mbenz89** [comment]
No response after suggesting a solution.
