### ISSUE TITLE
JBCO - Jasmin syntax error

### ISSUE THREAD

**Issue by randombyte-developer** [Sable/soot#927]
I am running
```
java -cp soot-3.0.0-20180411.152449-306-jar-with-dependencies.jar soot.jbco.Main -jbco:verbose -w -t:wjtp.jbco_mr -t:wjtp.jbco_fr -process-dir entity-particles-2.1.jar -d ./sootOutput -pp -allow-phantom-refs
```

It runs fine, but just at the end there is a 'syntax error': https://pastebin.com/59iT7RBq

What further information do you need to help me?

**Comment by ericbodden** [comment]
Thanks for the note. Can you paste a download URL for entity-particles-2.1.jar? That will help us debug this.

BTW, as a side note: JCBO is heavily outdated, I am not sure how well it still works - but that should not be the source of this bug.

**Comment by randombyte-developer** [comment]
Update, I got it running:

```
java -cp soot-3.0.0-20180411.152449-306-jar-with-dependencies.jar soot.jbco.Main -jbco:verbose -w -t:wjtp.jbco_fr -process-dir entity-particles-2.1.jar -d ./sootOutput -cp spongeapi-7.0.0-shaded.jar -allow-phantom-refs -pp -asm-backend
```

I added `-asm-backend` which seems to completly replace Jasmin, I don't really know the internals of Soot but it seems to be that Jasmin doesn't support all kinds/variants of `invokedynamic`. Kotlin might use this rare kind.
I also had to add the core API(spongeapi) which this jar uses to the classpath. Otherwise some fields of the API got renamed and couldn't be found at runtime. It surprises me, that only one/two fields where renamed which shouldn't: `Text.EMPTY` got `Text.Ill1Il1` or so. It is a constant field but that shouldn't mean to be renamed. Don't know, adding the API to the classpath solved this problem.
Another API which is not in the classpath seems to stay unrenamed, so `-allow-phantom-refs` does it job the right way this time.

**Comment by ericbodden** [comment]
Oh I see. Yes in fact the Jasmin backend is no longer properly maintained. I would have thought, though, that ASM by now is our default. @mbenz89 is that not the case?

Regarding the renaming I am not sure which effect might be causing this.

**Comment by mbenz89** [comment]
@ericbodden I just checked this and while ASM is the default bytecode frontend, Jasmin remains the default backend.
I'll put fixing this on my todo list.

@randombyte-developer I suggest renaming this issue in hope that someone familiar with JBCO might help you with this issue. The user `pnest` is currently handing in a lot of updates to JBCO, so he might have an idea.

**Comment by randombyte-developer** [comment]
There are quite some bugs with jbco and crashes. I will create separate issues for these once I figured out how to reproduce with a minimal setup and remove any other issued that play into it.
