### ISSUE TITLE
Move soot website to Github

### ISSUE THREAD

**Issue by ericbodden** [Sable/soot#93]
Important elements of the old Soot website at
http://www.sable.mcgill.ca/soot/
should be moved to Github. This page gives information about how to create web pages on Github:
http://pages.github.com/

Please discuss the layout and structure of the new website with Eric and prepare a first version in a separate Git branch. Next we should then discuss the website on the mailing list. Once the website is approved, we will publish it and remove the old website.

**Comment by StevenArzt** [comment]
That has been done by now, so I close the issue.
