### ISSUE TITLE
JBCO - Duplicate methods

### ISSUE THREAD

**Issue by randombyte-developer** [Sable/soot#934]
When using the class renamer from JBCO sometimes weird things happen like this:

```
    @NotNull
    public final ConfigHolder<GeneralConfig> getGeneral() {
        return this.general;
    }

    public SSSS5 getGeneral() {
        throw new Error("Unresolved compilation error: Method <de.randombyte.<secret>.plugin.config.I1IIl: de.randombyte.<secret>.plugin.SSSS5 getGeneral()> does not exist!");
    }
```

So one getter was duplicated, but with another return type. `SSSS5` is the obfuscated class name. And when running the jar:

```
Caused by: java.lang.ClassFormatError: Duplicate method name "getGeneral" with signature "()Lde.randombyte.<secret>.plugin.SSSS5;" in class file de/randombyte/<secret>/plugin/config/I1IIl
```

Pinging @pnest because he is interested in JBCO related stuff.

I don't have a clue what to do, any help?

**Comment by ericbodden** [comment]
JBCO is no longer maintained. We still do accept patches but cannot provide any support. Sorry.

**Comment by pnest** [comment]
@randombyte-developer It is wired. I am not sure if I will be able to reproduce this bug: no sources. Could yo provide any test case?
I've noticed that `final` modifier has gone. Is it a typo or actual code?

**Comment by randombyte-developer** [comment]
That's not a typo. I don't have anything set up yet anymore. I switched to proguard and some custom scripts that produce very heavy obfuscation mappings.
