### ISSUE TITLE
Android: initialization values of static non-final fields missing in Jimple representation

### ISSUE THREAD

**Issue by jpstotz** [Sable/soot#937]
I encounter a problem with static fields in the Android/DEX part of Soot. Consider the following simple class:

    public class SimpleClass {
       public static String A = "!AABBCCDD!";
    }

If I compile this class to SimpleClass.class and then generate the Jimple code from it everything is fine.
`java -cp  soot-3.1.0-20180424.084712-9-jar-with-dependencies.jar soot.Main -w -f jimple  -cp target/classes/;"%JAVA_HOME%\jre\lib\rt.jar";"%JAVA_HOME%\jre\lib\jce.jar" SimpleClass`

The generated Jimple code contains the correct `<clinit>`:
    
    static void <clinit>()
    {
         <SimpleClass: java.lang.String A> = "!AABBCCDD!";
         return;
    }

If I do the same using a DEX file containing this class the `<clinit>` misses the initial value of the field:

    static void <clinit>()
    {
        return;
    }

I did this using different versions of Soot from the [Snapshot repository](https://soot-build.cs.uni-paderborn.de/nexus/#browse/browse/components:soot-snapshot). It does not matter if I use the oldest or the newest (3.1) version the result is always the same as above.

For making sure that the variable is really present in the dex code I also decompiled the APK using different versions of `apktool` and checked the Smali code - the initialization value was always present:

    # static fields
    .field public static A:Ljava/lang/String; = "!AABBCCDD!"

**Comment by MarcMil** [comment]
For the case that this field is not final, I would suggest adding an appropriate assign statement to the *start* of the <clinit> method of the same class to emulate old behavior.
Some classes might assume that the presence of a constant tag (even on a non-final field) means that the corresponding field is in fact a constant and cannot be changed.

**Comment by StevenArzt** [comment]
Soot normally uses tags to deal with such data. Have you tried to call getTags() on the SootField instance? You should then find an object of a class derived from ConstantValueTag, i.e., IntegerConstantValueTag, which contains the initialization value from the bytecode. If these tags are missing, that's a bug. If these tags are there, client analyses should evaluate them and no changes to the static initializer are required.

In fact, we have code that enforces that these tags are available. The Dexpler frontend loads the constant table from the dex bytecode. If we load Jimple files from disk (Jimple doesn't have a constant pool), we even infer the tags from the code in the static initializer. In the end, there should always be a tag - but not necessarily a static initializer,

**Comment by jpstotz** [comment]
Sorry Steven but you are wrong. This only happens for final fields, but we are talking about non-final fields here.

**Comment by StevenArzt** [comment]
Ah, I overlooked that. In that case, we might still want to re-use some of the existing code that already deals with modifying the clinit method in the ConstantValueToInitializerTransformer class. Maybe we need to refactor that code into a separate utility class or allow for parameters in the existing transformer.

**Comment by qc1iu** [comment]
I have the same problem. When using apk as the input, the out put apk not work since missing initialization for static field.

**Comment by jpstotz** [comment]
@StevenArzt: I tried to find a way to integrate a new tag for the initial value into Soot by re-using existing code as you suggested. However I have to say that the class `ConstantValueTag` and sub-classes make it near to impossible to re-use anything. 

The only mitigative aspect I can say on that class structure is that is 14 years old (and therefore was coded in the pre-generics era of Java). All the other properties of these classes I would like to summarize  this way: "OMG this is the entry into the type cast hell".
Especially the fact that we have 5 subclasses that don't have a common interface for retrieving the actual value is causing ugly code like https://github.com/Sable/soot/blob/e98fba5a9272780dbb45178a81db542ae5024619/src/main/java/soot/toolkits/scalar/ConstantValueToInitializerTransformer.java#L97-L112
which reduces IMHO re-usability to zero.

Therefore I am giving up to re-use anything existing. I only see two ways from here: Create a parallel structure for initial values or throw away the existing ConstantValueTag` class hierarchy and start fresh with something usable.

**Comment by StevenArzt** [comment]
Since we cannot throw away existing structures, the only chance I see is to create a somewhat new structure. Idea: Have new classes IntegerValueTag, LongValueTag, etc. with IntegerConstantValueTag derived from IntegerValueTag. In other words, we extend the type hierarchy. Those new middle classes essentially represent the fact that there is a value in the constant pool. The leaf classes (which are the existing classes) represent the fact that this value is constant. This should not break existing code, but allows us to re-use at least some parts, e.g. you only need to cast to the intermediate class to get a value if you don't care whether it is final/constant or only pre-initialized.

**Comment by ericbodden** [comment]
Hi all. I wonder... why don't we go down the road that @MarcMil proposed, i.e., to generate appropriate initialization code in the class initializer? IMHO that would be much better because it would be backwards compatible to existing code. Spark, for instance, will find the alloc site for the string if we do it that way, but it won't if we simply use tags. Hence this might lead to incomplete points-to information.

**Comment by ericbodden** [comment]
Also note that we had a pull request for this...
https://github.com/Sable/soot/pull/944

**Comment by jpstotz** [comment]
The changes of PR #1044 did solve this problem for me (respectively applying the updated ConstantValueToInitializerTransformer before starting my analysis). 

Thank you @MarcMil and @StevenArzt.
