### ISSUE TITLE
how soot works with java project by Spring Framework?

### ISSUE THREAD

**Issue by jacoryjin** [Sable/soot#942]
I want to analysis a java project with Spring Framework, but get CallGraph failed, anyone help me?
the code likes:(the code run ok, but only get the Application cg)
public static final String path = "F:/test-webservice-1.3.0.jar";
soot.G.reset();
Options.v().set_process_dir(Collections.singletonList(path));
Options.v().set_allow_phantom_refs(true);  
Options.v().set_prepend_classpath(true);  
Options.v().set_validate(true);  
Options.v().set_whole_program(true);
Options.v().set_app(true);  
Options.v().set_src_prec(Options.src_prec_class);
Scene.v().loadNecessaryClasses();
SootClass appclass = Scene.v().loadClassAndSupport("com.eproject.microservices.testcase.Application");
appclass.setApplicationClass();
PackManager.v().runPacks();
CallGraph cg = Scene.v().getCallGraph();
... ....

**Comment by mbenz89** [comment]
What do you mean with "but only get the Application cg"?
The cg will always only contain application classes. If you want to model libraries not included in the jar file, you will have to propose those libraries to Soot as well.

**Comment by ericbodden** [comment]
Closing for now. Please reopen with a clearer description of the question.
