### ISSUE TITLE
Installing Eclipse Plugin

### ISSUE THREAD

**Issue by LordArma** [Sable/soot#948]
Hello.
I tried to install Eclipse plugin on Eclipse Oxygen on a Xubuntu x64 machine. I couldn't find "Other option" in "Customize Perspective" window.
So I thought ّI must install Eclipse Luna. I have a same problem with this version of Eclipse too.
I'm trying to install this plugin as this tutorial says:
https://github.com/Sable/soot/wiki/Eclipse-Plugin-Installation
Do you have any idea?
Do I must try to install an older version?
How I can enable this plugin feature on my Eclipse IDE?

**Comment by mbenz89** [comment]
As far as I know, the plugin hasn't been updated for at least 6 years and is not supported anymore. If you really want to give it a try, you might want to use an Eclipse version of that time and be ready to fix some things.
