### ISSUE TITLE
Extract Java Major/Minor version from bytecode and use extracted version for output

### ISSUE THREAD

**Issue by mbenz89** [Sable/soot#968]
Discussed in #956 

Test with default interface method.

**Comment by qc1iu** [comment]
Maybe the  #991 related to this issue?

Before using soot, the input class file major version is 52.
After using soot, the output class file major version is 46, then the error occur.

**Comment by ReedOei** [comment]
@qc1iu Did you change the version in the class file manually and see if that fixed the issue? See #956 for details on how to do that. If so, for a temporary workaround, you can use the -javaversion 1.8 flag to force Soot to output version 8.

**Comment by qc1iu** [comment]
@RedOei thanks. I changed the version but it doesn't work. Is't still verify error. In Issue #991, I offered  my test case. By check the byte-code generate by soot manually, there has a problem exactly.

**Comment by anddann** [comment]
this is solved, isn't it @mbenz89
