### ISSUE TITLE
Problem when building with maven

### ISSUE THREAD

**Issue by ericbodden** [Sable/soot#983]
I tried to build Soot using mvn today, and got this error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.132 s
[INFO] Finished at: 2018-07-05T21:33:03+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project soot: Could not resolve dependencies for project ca.mcgill.sable:soot:jar:3.1.0-SNAPSHOT: Failed to collect dependencies at pxb.android:axml:jar:2.0.0-SNAPSHOT: Failed to read artifact descriptor for pxb.android:axml:jar:2.0.0-SNAPSHOT: Could not transfer artifact pxb.android:axml:pom:2.0.0-SNAPSHOT from/to soot-snapshot (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by mbenz89** [comment]
From the [wiki](https://github.com/Sable/soot/wiki/Building-Soot-from-the-Command-Line-(Recommended)):

> Soot's nexus server https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/ is reachable via https using let's encrypt certificates. Some older java versions do not include them out-of-the-box.
Thus, we recommend using java >= 1.8.0_144.

Normally, this is caused by an outdated Java version. If for some reason you have to use an older Java version, there are certainly ways to add Let's encrypt's root CA to Java's certification chain.
